docs/setup.md

Update require hook extensions to include '.es'

---

docs/setup.md

Add shell invocation usage for make

---

docs/usage/browser.md

Options URL.

---

docs/usage/browser.md

WRT [this](https://github.com/6to5/6to5.github.io/pull/34#discussion_r22770607) //cc @thejameskyle

Relative path.

---

docs/tour.md

Typo fix in Tour.md

---

scripts/repl.js

@thejameskyle via our recent convo, ping me with any questions/concerns.

modularize REPL

---

docs/using-6to5.md

Spent a while struggling with this last night.
Wrote a comment on an issue [here](https://github.com/6to5/6to5/issues/351#issuecomment-71346319).

add nodemon argument swallowing information

---

docs/usage/cli.md

add 6to5-node options

---

scripts/repl.js

@thejameskyle @hemanth  Looking for another pair of :eyes:   This is a simple abstraction to separate concerns from the REPL (not having to know as much about the storage implementation/etc.

Storage abstraction

---

docs/usage/experimental.md
docs/usage/loose.md
docs/usage/modules.md
docs/usage/playground.md
docs/usage/runtime.md
docs/usage/transformers.md
docs/using-6to5.md

* Use shell script syntax for commands
* Use dollar sign for commands

Fix markdown syntaxes

---

404.html
package.json
scripts/repl.js

This PR changes some of the remaining 6to5 mentions to Babel.

change a few 6to5 mentions to babel

---

_posts/2015-02-15-not-born-to-die.md

Correct grammar in “Not Born to Die”

---

scripts/repl.js

As per @sebmck's [suggestion](https://gitter.im/babel/babel?at=54e40cde48b72ed530955d28).

Error messages on access to exports/module/require

---

scripts/repl.js

WRT [this](https://github.com/babel/babel.github.io/pull/142/files#r25051238)

Better looking error message.

---

_posts/2015-02-23-babel-loves-react.md

I quickly wrote up this blog post to post tomorrow. @sebmck thoughts?

Add Blog post: Babel <3 React

---

docs/usage/transformers/index.md

Docs: minor fixes

---

scripts/repl.js

Repl isn't working at the moment because of a SyntaxError

fucnsion -> function

---

.gitignore
docs/faq.md

Searched the project for any other references, didn't see any.

Fixes #191 - Link to missing comparison page.

---

index.html

See https://rawgit.com/faq#rawgit-com-in-production

Use cdn.rawgit.com instead of rawgit.com

---

docs/usage/jsx.md

mention compatibility with react 0.13

---

docs/faq.md

I may be wrong, but this sentence reads incorrectly in my mind. Also - sorry for the annoying grammar nit PR.
Thanks for babel!

replace is with are in plural context

---

_posts/2015-03-31-5.0.0.md

Looks like a copy/paste mistake.

fixes blog post usage example

---

docs/usage/modules.md

Output of default exports was changed since v5.0.

fix CommonJS interop section in modules doc

---

docs/usage/require.md

Spotted this and thought I could fix it. :)

Fix broken link in `require hook` docs.

---

docs/usage/experimental.md
docs/usage/transformers/index.md

There.  Is there any other place I should add it to?

Add docs for the es7.trailingFunctionCommas transformer

---

_posts/2015-03-31-5.0.0.md

Use the rectified example from babel/babel/issues/1310

Fix decorator example code

---

_data/tools.yml
_includes/tools/jspm/install.md
_includes/tools/jspm/usage.md

From the suggestions in https://github.com/babel/babel.github.io/pull/281.
Thanks @codylindley for getting this going. Feedback very welcome.

Add jspm guidelines

---

_includes/tools/jspm/usage.md

Thanks for the quick merge! Apologies for the typo.

React -> JSX

---

_includes/tools/jspm/usage.md

One of those days apparently... last one with some luck!

quote -> callout

---

_posts/2015-05-14-function-bind.md
_sass/pages/_blog.scss

@sebmck @RReverser @zenparsing Is everything here correct?

Blog Post: Function Bind Syntax

---

docs/usage/transformers/index.md

Also re-order the list a bit to conform to alphabetical order

Add es7.functionBind

---

docs/advanced/transformers/es6/spec-symbols.md
docs/advanced/transformers/index.md
docs/usage/experimental.md

For https://github.com/babel/babel.github.io/pull/307#issuecomment-105988645
Ref #307

fix redirect

---

docs/advanced/transformers/index.md
docs/advanced/transformers/other/comprehensions.md
docs/learn-es6.md
docs/usage/experimental.md

Comprehensions are ES7.

---

.editorconfig

Updated the `.editorconfig` to match the code style used.

Update `editorconfig` to match reality

---

docs/advanced/plugins/index.md
docs/advanced/plugins/manipulation.md
docs/advanced/plugins/scope.md
docs/advanced/plugins/visiting.md

update plugin docs to use 5.6.0+ plugin api

---

docs/usage/cli.md

Resolves #397
cc @sebmck since I stole your words

Add babel-node production warning

---

docs/usage/require.md

 Added note that all options can be passed in to require hook

---

docs/advanced/plugins/index.md

Added examples for different ways to add plugins

added examples for in browser environment (and other cases)

---

docs/advanced/caveats.md
docs/advanced/plugins/index.md
docs/advanced/transformers/index.md
docs/usage/modules.md
docs/usage/runtime.md

Life is like a box of chocolates.

Run, Forrest. Run!

---

_config.yml
_includes/footer.html
_includes/head.html
_includes/scripts.html
_layouts/docs.html
_layouts/post.html
docs/setup.md
index.html
repl.html
scripts/index.js
scripts/social.js

- Closes #19
- This PR is based on work done in https://github.com/babel/babel.github.io/pull/194 by @peterblazejewicz

Move loading of all JavaScript close to the end of body tag

---

docs/learn-es6.md

It's standardized now! I think this is a good first step.
(Bad storm here, trying to make sure I can make the PR while there still is power...)

Clarify, update Learn ES2015 page.

---

scripts/repl.js

have "experimental" disabled by default

---

docs/advanced/transformers/index.md
docs/advanced/transformers/optimisation/react/constant-elements.md
docs/advanced/transformers/optimisation/react/inline-elements.md

Optional optimisation transformers as featured in
https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html#compiler-optimizations

Add docs for react 0.14.x transformers

---

docs/usage/polyfill.md

As it's not just node / Browserify that this is relevant to.

Added reference to webpack

---

docs/usage/experimental.md

See https://github.com/babel/babel/pull/2464.

move async functions to stage 3 (docs)

---

_data/tools.yml
_includes/tools/rollup/install.md
_includes/tools/rollup/usage.md

via https://github.com/rollup/rollup/issues/178#issuecomment-150951265
Thanks!

add Rollup instructions

---

docs/plugins/transform-async-to-generator.md

Thanks babel. The amazing tool!! Just help to fix some v6 document.

fix doc: transform-async-to-generator

---

docs/usage/options.md

presets description referenced plugins instead of presets
plugins description referenced presets instead of plugins

Fix the Options description for presets and plugins

---

_includes/tools/babel_register/install.md
_includes/tools/babel_register/usage.md
_includes/tools/mocha/usage.md
docs/usage/require.md

update to use babel-core/register

---

docs/usage/cli.md

Fix the CLI Options description for presets and plugins

---

_posts/2015-10-29-6.0.0.md
docs/faq.md
docs/plugins.md
docs/plugins/preset-stage-0.md
docs/plugins/preset-stage-1.md
docs/plugins/preset-stage-2.md
docs/plugins/preset-stage-3.md

Ref https://github.com/babel/babel/pull/2649
should publish the npm packages when merging this

add preset-stage-x docs

---

docs/learn-es6.md
docs/plugins/preset-stage-0.md
docs/plugins/preset-stage-1.md
docs/plugins/preset-stage-2.md
docs/plugins/preset-stage-3.md
index.html

Fixes #500, #501 
Also removed comprehensions mention
Oh part of this in done in https://github.com/babel/babel.github.io/pull/487

fix preset-stage-x links, etc

---

docs/plugins.md

Ref https://github.com/babel/babel.github.io/issues/485

add some subcategories

---

docs/plugins.md

Ref https://github.com/babel/babel/issues/2710

add some docs about plugin options

---

docs/plugins.md

Fixes https://github.com/babel/babel.github.io/issues/509

redirect usage/modules to plugins

---

_posts/2015-10-31-setting-up-babel-6.md

Blog Post: Setting up Babel 6

---

docs/usage/browser.md

Not sure what you need to add to the `.babelrc` - can update instead of that's correct

fix usage/browser docs

---

docs/usage/options.md

Ref https://github.com/babel/babel.github.io/issues/493

link to plugins/presets

---

docs/setup.md

See https://github.com/babel/babel.github.io/issues/571

Added an extra warning to the Setup page

---

docs/usage/require.md

based on [/packages/babel-register/src/node.js#L54-L57](https://github.com/babel/babel/blob/e96f3544f6a82345a469fe55b3b05c7f54536f11/packages/babel-register/src/node.js#L54-L57)

Explain how babelrc works with require hook

---

docs/usage/options.md

- Ref: https://github.com/babel/babel/blob/4e82edb6d0c9e7a8ba2c51d6baf3e170824ed285/packages/babel-core/src/transformation/file/options/config.js#L142
- Fixes #620.

Document `.babelrc` option for transformation

---

docs/plugins.md

@loganfsmyth In response to https://phabricator.babeljs.io/T6817

Document community maintained presets

---

docs/usage/cli.md

Add note about advanced usage in the CLI

---

_includes/tools/babel_register/usage.md

according to  https://phabricator.babeljs.io/T6940

Add message about usage of babel-register in production

---

docs/plugins.md

Add plugin development handbook link

---

docs/setup.md

Just adding the cli commands in setup if that makes it clear

Inline install instructions setup

---

docs/plugins.md

anything => something
Make it sound more natural.

Minor gramma fix

---

_layouts/page.html

Otherwise you get an unfriendly message saying you need to fork the repo and you don't even get to see the file.

Go to blob rather than edit page

---

docs/learn-es6.md

Ref https://github.com/babel/babel.github.io/issues/624

Update to reflect the fact TCO is removed in babel 6.

---

docs/plugins/transform-async-to-module-method.md
docs/plugins/transform-es2015-arrow-functions.md
docs/plugins/transform-es2015-classes.md
docs/plugins/transform-es2015-computed-properties.md
docs/plugins/transform-es2015-for-of.md
docs/plugins/transform-es2015-modules-commonjs.md
docs/plugins/transform-es2015-spread.md
docs/plugins/transform-es2015-template-literals.md
docs/plugins/transform-react-jsx.md
docs/plugins/transform-regenerator.md
docs/plugins/transform-runtime.md
docs/plugins/transform-strict-mode.md

Same as https://github.com/babel/babel/pull/3345

Add plugin opts

---

users.html

Or we just remove the issue part since we ask them to make a PR anyway
@thejameskyle

Add a link to submitted users PRs

---

docs/plugins.md
docs/plugins/preset-es2015.md
docs/plugins/transform-es2015-computed-properties.md
docs/plugins/transform-es2015-duplicate-keys.md

add docs for dup keys plugin

---

scripts/repl.js

I guess we want the REPL to work in ES5 environments?
So if we want to write it in ES6, it should be transpiled :-)

make repl work in ES5

---

_includes/tools/browserify/usage.md

Docs: replaced usage of old babel 5 with new one in browserify usage doc

---

README.md

fixed #782 
@hzoo could you take a look?

added instruction to install ruby as prerequisites

---

docs/plugins.md

From https://github.com/babel/babel.github.io/blob/5.0.0/docs/usage/experimental.md

Add back information on the tc39 proposal process

---

_includes/tools/webpack/usage.md

Fix formatting in webpack usage example "babel-loader"} ~> "babel-loader" }

Fix formatting in webpack usage example "babel-loader"} ~> "babel-loader" }

---

docs/usage/polyfill.md

add webpack config example

---

docs/usage/polyfill.md

just to be consistent with `babel-cli` and `babel-preset-es2015` install command

update polyfill install command to use save-dev option

---

repl.html
scripts/repl.js

Ref https://github.com/babel/babel.github.io/pull/449
cc @spicyj

line wrap option in repl

---

docs/plugins/transform-es2015-modules-systemjs.md

As discussed in https://github.com/babel/babel/pull/3482#issuecomment-219545753.

document systemGlobal option

---

docs/plugins.md

such as how its the 2nd step in babel's 3 steps for more context

Add some more information about plugins

---

users.html

we removed the instructions from the issue - or will they understand it from the examples? - @thejameskyle

Add a comment about image size/format

---

docs/learn-es6.md

Fix explanation of __proto__ in object literal

---

docs/plugins/preset-stage-2.md
docs/plugins/preset-stage-3.md

See matching pull request https://github.com/babel/babel/pull/3522

Promote trailing-function-commas to stage 3

---

docs/learn-es6.md

ES2015 is no longer the newest version of the language.

Edited for accuracy

---

README.md

Specifically about bundler"
Running `make build` results in an echo.
```bash
❯ make build
if [ ! -d ./node_modules ]; \
then npm install; \
fi
if [ ! -d ./_sass/bootstrap ]; \
then cp -r ./node_modules/bootstrap-sass/assets/stylesheets/bootstrap ./_sass/bootstrap; \
fi
```

Add more explicit setup directions

---

docs/plugins.md

See https://github.com/babel/babel.github.io/pull/895/files#r76295818

Fix indentation on plugins page

---

_data/navigation.yml
docs/faq.md

- will add more stuff from twitter/phab/slack when I remember

Add the FAQ back, add some more questions

---

repl.html
scripts/pretty-format.js
scripts/repl.js

ref #175
Could try to setup webpack but just inlined it for now (transpile+move into 1 file) @thejameskyle

add pretty-format as global - fixes #172, closes gh-175

---

docs/plugins/preset-stage-2.md
docs/plugins/preset-stage-3.md

updated the stage-2, stage-3 docs for object-rest-spread

fix stage-2 incorrectly lists object-rest-spread #932

---

docs/plugins/transform-class-properties.md

Just noticed a one-letter typo.

fix a minor typo

---

docs/plugins/transform-es2015-shorthand-properties.md

Mentioned that transform-es2015-shorthand-properties transforms both properties and methods and added examples.

Updated documentation for transform-es2015-shorthand-properties

---

docs/plugins/transform-react-constant-elements.md

Add composite component deopt for react-constant-elements

---

_posts/2016-10-24-6.18.0.md

Fix error msg in post

---

docs/usage/options.md

Added note about sourceMaps option - #918

---

docs/usage/cli.md

Added --copy-files option instructions

Update cli documentation

---

docs/usage/cli.md

Document --no-babelrc in correct section

---

_sass/bootstrap/_scaffolding.scss
scripts/docs.js

Or do it like react with a separate hashtag link thing

add link for all headings

---

_sass/_variables.scss
scripts/repl.js

Fixes https://github.com/babel/babel.github.io/issues/923
Based on https://github.com/sindresorhus/refined-github/blob/2463f184d2f6f2023b49d67a3bc265bfd66c11b9/extension/custom.css#L29
cc @vramana

default to Operator, Fira, Ubuntu Mono

---

_data/tools.yml
_includes/tools/browser/install.md
_includes/tools/browser/usage.md

Fixes https://github.com/babel/babel.github.io/issues/170

Add browser usage

---

scripts/docs.js

add animated scrolling on anchor links

---

scripts/docs.js

set location.hash after smooth scroll

---

docs/plugins/check-es2015-constants.md

According to #997 and a follow up to babel/babel#4908

Link check-es2015-constants's doc to its package's README

---

index.html

Just noticed this and thought it'd be helpful to make it a link.

docs: format and link plugins

---

docs/faq.md

For #1002 
Cleanup & fix `plugins/`

Cleanup plugins code snippets

---

README.md

Contributing to the website in README

---

docs/plugins/transform-object-rest-spread.md

https://github.com/babel/babel/pull/4755#issuecomment-265071657

Remove caveat from transform-object-rest-spread.md

---

_posts/2016-12-07-the-state-of-babel.md

Fixes link to BabelJS slack room

Fix link to slack

---

docs/editors.md

Add vim syntax highlighting support to editor docs

---

users.html

add extra comment

---

docs/plugins/external-helpers.md
docs/plugins/transform-runtime.md

duplicate text coming from package readme

---

_data/packages.yml
_includes/package_readme.html
_layouts/page.html
docs/plugins/minify-constant-folding.md
docs/plugins/minify-dead-code-elimination.md
docs/plugins/minify-empty-function.md
docs/plugins/minify-flip-comparisons.md
docs/plugins/minify-guarded-expressions.md
docs/plugins/minify-infinity.md
docs/plugins/minify-mangle-names.md
docs/plugins/minify-numeric-literals.md
docs/plugins/minify-replace.md
docs/plugins/minify-simplify.md
docs/plugins/minify-type-constructors.md
docs/plugins/transform-inline-consecutive-adds.md
docs/plugins/transform-inline-environment-variables.md
docs/plugins/transform-member-expression-literals.md
docs/plugins/transform-merge-sibling-variables.md
docs/plugins/transform-minify-booleans.md
docs/plugins/transform-node-env-inline.md
docs/plugins/transform-property-literals.md
docs/plugins/transform-regexp-constructors.md
docs/plugins/transform-remove-console.md
docs/plugins/transform-remove-debugger.md
docs/plugins/transform-simplify-comparison-operators.md
docs/plugins/transform-undefined-to-void.md

Moved the `from` variable from the include up to the page and added a mapping of source to GH url

Fix babili github links

---

README.md

Update contributing to the website

---

_data/navigation.yml

Slight re-ordering to make things look a little better:

Tweak docs menu items

---

index.html

Since #1084 is merged the page is available.

Fix preset-env doc link

---

docs/plugins/preset-env.md

To be consitent with http://babeljs.io/docs/plugins/preset-latest/ and http://babeljs.io/docs/plugins/preset-es2016/.

Update preset-env header

---

docs/setup.md

Change lastest with env preset

---

docs/plugins/syntax-flow.md
docs/plugins/syntax-jsx.md

Add missing description in syntax flow and jsx

---

_sass/components/_featurette.scss
index.md

I want to make some modifications to improve the readability of the page:
* Increased the space between sections:
* Removed big buttons since they are in the menu anyway:
Related to #1100

Some updates in the main page

---

.gitmodules
_data/packages.yml
docs/core-packages.md
docs/core-packages/babylon.md

Add Babylon documentation

---

_data/navigation.yml
docs/core-packages.md
docs/core-packages/code-frame.md
docs/core-packages/helpers.md
docs/core-packages/register.md
docs/core-packages/template.md
docs/core-packages/types.md

Fix trailing slash in core-packages

---

docs/plugins/check-es2015-constants.md
docs/plugins/transform-es2015-arrow-functions.md
docs/plugins/transform-es2015-block-scoped-functions.md
docs/plugins/transform-es2015-block-scoping.md
docs/plugins/transform-es2015-classes.md
docs/plugins/transform-es2015-computed-properties.md
docs/plugins/transform-es2015-destructuring.md
docs/plugins/transform-es2015-duplicate-keys.md
docs/plugins/transform-es2015-for-of.md
docs/plugins/transform-es2015-function-name.md
docs/plugins/transform-es2015-literals.md
docs/plugins/transform-es2015-object-super.md
docs/plugins/transform-es2015-parameters.md
docs/plugins/transform-es2015-shorthand-properties.md
docs/plugins/transform-es2015-spread.md
docs/plugins/transform-es2015-sticky-regex.md
docs/plugins/transform-es2015-template-literals.md
docs/plugins/transform-es2015-typeof-symbol.md
docs/plugins/transform-es2015-unicode-regex.md

Fixed some inconsistencies in pages.
Related fixes babel/babel#5111

ES2015 transform consistent doc

---

docs/usage/babelrc.md

Together with <https://github.com/babel/babel/pull/5101>.

Clarify how to disable babelrc lookup behavior

---

_data/navigation.yml
docs/core-packages.md
docs/usage/babel-register.md

Move babel-register back under usage

---

_posts/2017-02-13-6.23.0.md

Fix bug in bug fix section

---

_sass/components/_featurette.scss
_sass/components/_hero.scss
index.md
scripts/index.js

Fixes #1144
(note, gif above has some visual artifact issues)
Desktop:
Mobile:
Just some polish items to tweak.
Would love feedback, and/or additional examples to use in the demo?
TODO:

Add mini-repl

---

index.md

Fixes #1168
cc: @existentialism

Updates latest post on homepage automatically

---

docs/plugins.md
docs/plugins/preset-flow.md

Add babel-preset-flow on the website.
Page is at: `/docs/plugins/preset-flow/` and uses the README in Babel/babel.

Add flow preset

---

_data/tools.yml
_includes/tools/webpack/usage.md
_includes/tools/webpack2/install.md
_includes/tools/webpack2/usage.md

Changed loaders to webpack new syntax rules.
This fixes issue [#1188](https://github.com/babel/babel.github.io/issues/1184).

Changed loaders to rules in webpack setup

---

docs/plugins/transform-react-constant-elements.md
docs/plugins/transform-react-display-name.md
docs/plugins/transform-react-inline-elements.md
docs/plugins/transform-react-jsx-compat.md
docs/plugins/transform-react-jsx-self.md
docs/plugins/transform-react-jsx-source.md
docs/plugins/transform-react-jsx.md

Added description for React plugins.

Added description

---

_data/navigation.yml
faq.md

Move faq to root

---

_sass/components/_featurette.scss

Get started seciton: Prevent h3 breaking.

---

_includes/header.html

add donate link

---

scripts/repl.js

Removed preset-latest from the repl

---

docs/plugins.md

added link to thefeedbackloop.xyz articles for explaning stage-x

---

index.md
repl.html

Disable unpkg scripts for now

---

index.md
repl.html

Reverts babel/babel.github.io#1231

Revert "Disable unpkg scripts for now"

---

docs/plugins/syntax-dynamic-import.md

I needed that one for jest, and I spent some time PRing the webpack one before finding it existed in a separate project...

Mention dynamic-import-node

---

_posts/2017-03-01-upgrade-to-babel-7.md

Add template literals revision upgrade post

---

repl.html
scripts/repl.js

Fixes https://github.com/babel/babel/issues/5657

Place env debug to a separate container.

---

faq.md

Minor grammar fix

---

7.html
scripts/7.js

7.0.0-alpha.15

---

_posts/2017-03-01-upgrade-to-babel-7-for-tool-authors.md

https://github.com/babel/babel/pull/5923

Note updated getFunctionParent behaviour

---

7.html

Same fix as https://github.com/babel/babel.github.io/pull/1298

Remove redirect_from from 7 repl

---

_posts/2017-08-09-babel-and-summer-of-code.md

If anyone wants to review (don't have to), or maybe you did already 😄

add soc post

---

_sass/pages/_repl.scss
js/repl/CodeMirrorPanel.js
js/repl/ReplOptions.js

Admittedly some of this is a bit hacky, but I didn't want to edit the surrounding styles much (at least not yet 😁 )

Tweaked REPL styles to accommodate for surrounding Babel site CSS

---

js/repl/CodeMirror.js

Fixed CodeMirror placeholder style

---

.eslintrc
js/repl/CodeMirror.js
js/repl/CodeMirrorPanel.js
js/repl/PluginConfig.js
js/repl/PresetLoadingAnimation.js
js/repl/Repl.js
js/repl/ReplOptions.js
js/repl/StorageService.js
js/repl/Svg.js
js/repl/UriUtils.js
js/repl/compile.js
js/repl/index.js
js/repl/loadPlugin.js
js/repl/loadScript.js
js/repl/replUtils.js
js/repl/scopedEval.js
js/repl/styles.js
js/repl/types.js
package.json
yarn.lock

fixes #1310
There is one problem though
```
Error: js/repl/index.js:10
10:   module.hot.accept();
^^^^^^^^^^^^^^^^^^^ call of method `accept`. Method cannot be called on
10:   module.hot.accept();
^^^^^^^^^^ property `hot` of unknown type
```
and honestly I aint how to handle this. The hacky way that I have figured out is this
```js
class module {
static hot: {
accept: Function,
}
}
```
but its obviously hacky and ugly. Any ideas?
cc @bvaughn

Prepared a precommit hook, flow + prettier

---

_redirects

Follow-up from [this comment](https://github.com/babel/website/pull/1348#issuecomment-325497275).
~~Going to wait and try this out on Netlify to see if it works~~ Seems to work okay on Netlify 😁

Redirect preview links to the new REPL

---

js/repl/ReplOptions.js
js/repl/styles.js

Sidebar tweaks

---

scripts/download-readmes.js

Missed this in https://github.com/babel/website/pull/1363, smh

Fix downloading readmes from specific branches

---

_layouts/post.html
_sass/pages/_blog.scss

Before/After:
Also included https://github.com/babel/website/pull/1373
/cc: @hzoo

Tweak blog line-height and margins

---

_posts/2017-03-01-upgrade-to-babel-7.md

* https://github.com/babel/babel/pull/6280
* https://github.com/babel/babel/pull/6251

Mention babel-node move and use-strict injection changes in upgrade post.

---

env.md

add env docs

---

js/repl/Repl.js
js/repl/replUtils.js
js/repl/types.js

Distinguish between no and default presets in REPL

---

js/repl/PluginConfig.js
js/repl/Repl.js
js/repl/UriUtils.js
js/repl/compile.js
js/repl/replUtils.js
js/repl/types.js

Fixes #1388.
Maybe revisit with a more lightweight prettier-as-a-service call?

Remove prettier from REPL

---

package.json
yarn.lock

Bump react to 16 release

---

repl.html

Fixes (some?) of https://github.com/babel/website/issues/1409.
Comment/Uncomment and bracket jumping/skipping now works.

Enable additional codemirror addons

---

js/repl/replUtils.js

Output module transform with preset-env debug

---

README.md

Changing **babel.github.io -> website**

Minor issue fix in Readme

---

_data/navigation.yml
docs/community/videos.md

Fixes https://github.com/babel/website/issues/27
Ref https://twitter.com/left_pad/status/918654512377851904
Just a start, can make new issues to add more.
Added some from https://www.youtube.com/playlist?list=PLUjGYjn761TW_j4HlBcq_qnJoaSMTlJOH, https://www.youtube.com/watch?v=Q_ncaTYEizc

add videos page

---

docs/community/videos.md

Ref https://github.com/babel/website/issues/1418

add videos

---

_data/navigation.yml
_data/team.yml
_includes/member.html
_sass/_main.scss
_sass/pages/_team.scss
team.md

#1381 - Team page

---

_data/team.yml
_includes/member.html

1. Typo In team member GitHub handle (EmmaMDeacon => EmmaDeacon)
2. Show twitter and github section if handle is present

Changes in Team page

---

_data/videos.yml

Fix incorrect video date

---

_data/videos.yml

add some things from Kent

---

_data/videos.yml
videos.html

I've added a year field, hopefully fixes issue #1439.

Add video date field

---

js/repl/PluginConfig.js
js/repl/ReplOptions.js

Fixes #1446.
I'm also finishing a refactor/cleanup PR for all this config.package/config.label checking we have everywhere now :(

Fix minify/evaluate options in REPL

---

_data/areas.yml
_data/team.yml
_includes/member.html
_sass/pages/_team.scss
team.md

https://twitter.com/left_pad/status/923871156305846273
Adjusted whitespace in second commit, additions are in 8781960.
Closes #1444

 Add V8 members, @keithamus, and @azz

---

_data/videos.yml

I've just added some more videos. 🤓

Add more videos

---

_posts/2017-11-03-nearing-the-7.0-release.md

Only really needs to be loaded once and it's going to hook into all the tweets automatically :ok_hand:

Only include Twitter widget.js once in 7.0 beta post

---

_posts/2017-09-11-zero-config-with-babel-macros.md

The package has been renamed :)

rename babel-macros -> babel-plugin-macros

---

js/repl/types.js

Make package for PluginConfig type mandatory.

---

js/repl/CircleCI.js
js/repl/PluginConfig.js
js/repl/Repl.js
js/repl/UriUtils.js
js/repl/replUtils.js
js/repl/types.js

New proposed changes for REPL

---

_layouts/post.html

Doesn't seem necessary anymore?

remove comments from posts

---

_posts/2017-03-01-upgrade-to-babel-7-for-tool-authors.md

Ref: https://github.com/babel/babel/issues/6773, https://github.com/istanbuljs/istanbuljs/pull/125

Add note about ArrowFunctionExpression#expression in upgrade guide

---

website/pages/en/users.js
website/static/css/babel.css
website/static/css/users.css

updated the users styles.  https://github.com/babel/website/issues/1528
Addition:
added a hover effect, please drop review for that too. Also let me know if needs to reverted. 🙂

added styles for user

---

_redirects
website/core/Footer.js

Add link to old site, redirect env

---

website/pages/en/404.js
website/static/css/error.css

Fixes https://github.com/babel/website/issues/1526
So not sure if I'm missing a step. I created a class base component that renders the HTML as it was on the legacy page.   Do we need a class base component? or is it ok if its pure;y functional? 
I haven't hooked up the component into anything, need your feedback to what the next steps should be.
``

Adding 404 page

---

website/i18n/en.json
website/pages/en/setup.js
website/static/css/setup.css
website/static/scripts/tools.js

I completed the following functions:
* component optimization
* fix code snippets style
* rm jquery, use javascript
* add translate
See #1527
@hzoo Please review.

fix(setup): rm jquery, use javascript

---

js/repl/ExternalPlugins.js
website/pages/en/index.js
website/static/css/babel.css
website/static/css/index.css

* Fix colour contrast ratio (`level AA` requires a contrast ratio of 4.5:1 for normal text)
* Fix missing alt tags
Fix #1579

Fix color contrast and missing alt tags

---

website/i18n/en.json
website/pages/en/index.js
website/static/css/babel.css
website/static/css/minirepl.css

Ported over the hero styles from the current website.
Also fixed a bug with smaller viewports and the mini-REPL:

Tweak home page hero styles

---

website/data/team.yml

Should at least add @xtuc and @existentialism here (we have so many awesome people) - been doing this for a long time now, attending/setting up meetings, etc!

add sven/brian

---

js/repl/ExternalPlugins.js

fix(externalPlugins): make sure the input is focusing correctly in Safari (old site)

---

js/repl/ExternalPlugins.js

I didn't test this in a browser, but will use the deploy preview. 
fixes #1610
Also ran this file through prettier on their repl and it seems to be a little bit different than what it originally was formatted as, I can revert those lines if needed

fix(externalPlugins): make sure the input is focusing correctly in Safari

---

website/package.json
website/yarn.lock

Fixes #1614 
Looks like this release also added warnings for invalid header fields in the front matter of docs, so I guess we'll have to remove them as well.

docusaurus@1.0.11

---

js/repl/compile.js

Don't use decoratorsLegacy with Babel 6

---

js/repl/compile.js

https://github.com/babel/website/pull/1629, #1632

Port #1629 and #1632 to the old site

---

docs/v7-migration.md

https://github.com/babel/babel/blob/v7.0.0-beta.46/packages/babel-plugin-proposal-export-default-from/package.json#L2
https://github.com/babel/babel/blob/v7.0.0-beta.46/packages/babel-plugin-proposal-export-namespace-from/package.json#L2

Fix typos in both @babel/plugin-proposal-export-*-from packages

---

js/repl/AccordionTab.js
js/repl/ExternalPlugins.js
js/repl/Repl.js
js/repl/ReplOptions.js
js/repl/types.js
package.json
yarn.lock

Part 1 of many of extracting our Smooshpack-powered branch to make the review easier.

Refactor sidebar tab expanded state

---

.babelrc
js/repl/index.js
package.json
yarn.lock

refs: https://github.com/babel/website/issues/1627
I've added "babel-polyfill" to make REPL work as Henry suggested.
There is another error is still being thrown but it doesn't affect REPL page:
https://github.com/babel/website/issues/1627#issuecomment-391074217

Fix REPL for IE11 at new site

---

js/repl/ExternalPlugins.js
js/repl/Repl.js
js/repl/ReplOptions.js

Implement functionality for "Remove added plugin" task from #1656

Add remove external plugin button to the REPL

---

js/repl/PluginConfig.js
js/repl/WorkerApi.js
js/repl/compile.js
js/repl/types.js

I had to tweak the plugin loading a bit because of how Prettier works in the browser now :)

Update to Prettier 1.13

---

docs/polyfill.md

add polyfill doc 7

---

docs/parser.md
docs/plugin-proposal-decorators.md
docs/plugin-syntax-decorators.md

pr: https://github.com/babel/babel/pull/8113

decoratorsBeforeExport defaults to false

---

js/repl/PluginConfig.js
js/repl/Repl.js
js/repl/ReplOptions.js
js/repl/UriUtils.js
js/repl/compile.js
js/repl/types.js

Add source type dropdown to REPL

---

.babelrc
js/repl/index.js
package.json
yarn.lock

refs: https://github.com/babel/website/issues/1627
I've added "babel-polyfill" to make REPL work as Henry suggested.

Fix REPL for IE 11 at old site

---

docs/tools/browserify/install.md

Fixes #1452
https://deploy-preview-1455--babel.netlify.com/docs/setup/#installation

Add babel-core to browserify install guide

---

docs/plugin-proposal-pipeline-operator.md

Related to https://github.com/babel/babel/pull/8196

Update pipeline-operator documentation

---

js/repl/compile.js

While testing https://github.com/babel/website/pull/1717
cc @mAAdhaTTah

hardcode pipelineProposal for now

---

docs/plugin-proposal-object-rest-spread.md
website/versioned_docs/version-6.x/plugin-transform-object-rest-spread.md

Mentioned in babel/website#1730

doc(object-rest-spread): fix links to moved spec & proposal

---

docs/plugin-transform-typescript.md

Just noticed this while reading the docs!

Small grammar fix.

---

docs/preset-minify.md
website/versioned_docs/version-6.x/preset-minify.md

Fix links (404) on preset-minify page: https://babeljs.io/docs/en/babel-preset-minify

fix preset-minify plugins links

---

docs/v7-migration.md

Typo in v7-migration.md

---

docs/parser.md

Two separate commits, otherwise this PR looks more complex than it is.

Update babel-parser docs

---

website/core/Footer.js
website/i18n/en.json
website/siteConfig.js
website/static/css/hide-footer.css
website/static/scripts/hide-footer.js

I found that the footer of the project has disappeared.

fix: footer css pollutes the whole

---

_redirects
docs/core-packages.md
website/i18n/en.json
website/versioned_docs/version-6.x/babelrc.md

* Fixes #1716
* Fixes some other links that are not directly linked to the mentioned issues
* Disables babylon redirect (for now)

Disable babylon redirect and fix some broken links

---

js/repl/AccordionTab.js
js/repl/ReplOptions.js
package.json
website/pages/en/index.js
website/pages/en/repl.js
website/pages/en/versions.js
website/siteConfig.js
yarn.lock

Upgrade prettier and run `eslint --fix 'js/**/*.js' 'website/**/*.js'`. Just for the sake of being up-to-date.

Upgrade prettier

---

website/package.json
website/static/css/minirepl.css
website/static/css/users.css
website/yarn.lock

docusaurus@1.3.3

---

docs/preset-env.md

Initial work at simplifying/improving env's docs... still need to work on the useBuiltIns stuff.

Rewrite env docs

---

website/blog/2018-08-27-7.0.0.md

add modern targets by kris

---

website/data/team.yml

Add myself to team.yml

---

website/blog/2018-08-27-7.0.0.md

short summary to the beginning?

add summary

---

website/versioned_docs/version-7.0.0/preset-env.md

Followup to https://github.com/babel/website/pull/1823

Sync env doc fix to version-7.0.0

---

docs/options.md

Add docs for https://github.com/babel/babel/pull/8660

Add documentation for the new rootMode option.

---

website/blog/2018-09-14-7.1.0.md
website/blog/2018-09-17-7.1.0.md

Should be pretty short, link to https://github.com/babel/website/pull/1825
Rendered: https://deploy-preview-1830--babel.netlify.com/blog/2018/09/17/7.1.0

add 7.1.0 post

---

docs/configuration.md

Fixed a few details that triggered my ocd :)

Fixed typos & grammar in docs

---

docs/options.md

Super small docs update, but I think it's useful (I've been burned a few times).
Happy to make any changes.

Adds note to options.md about passing cli options

---

docs/types.md

Add `TSUnknownKeyword`

---

docs/v7-migration.md

to Stage Preset Deprecations section

add blog post to v7 migration

---

website/static/css/code-blocks.css

Use inherited overflow-x for code snippets

---

website/siteConfig.js
website/static/css/code-blocks.css
website/versioned_docs/version-7.0.0/preset-stage-0.md
website/versioned_docs/version-7.0.0/preset-stage-1.md
website/versioned_docs/version-7.0.0/preset-stage-2.md
website/versioned_docs/version-7.0.0/preset-stage-3.md

Fixes #1863.
Would like to improve the design of these messages later, but think the content is most important.

Add additional deprecation instructions to stage-x docs

---

website/core/Footer.js
website/siteConfig.js

Hello @hzoo,
This was the video link we were talking about at the hacktoberfest event. Fairly simple contribution, tested out responsiveness, and works as expected. Hopefully this makes the content page more discoverable and easier to get to?

Add videos link in header and footer

---

docs/config-files.md

Fix typo in config-files.md

---

website/siteConfig.js

add update time for docs, defer attributes

---

website/data/team.yml

add nicolo

---

docs/tools/webpack/usage.md

updating webpack setup from `loaders` to `rules`

webpack setup: updating loaders to rules

---

docs/config-files.md
website/versioned_docs/version-7.1.0/config-files.md

Add documentation for monorepo configuration.

---

website/data/team.yml

Adding @gyujincho and @sujinleeme!

add rsgoc 2018

---

website/blog/2018-12-03-7.2.0.md

See https://github.com/babel/website/commit/6ea04ffe934e0e7b1da6c96e4d20f285f0760184#commitcomment-31546504.

Note about other smart-pipeline placeholders

---

js/repl/PluginConfig.js
js/repl/Repl.js
js/repl/ReplOptions.js
js/repl/Utils.js
js/repl/compile.js
js/repl/replUtils.js
js/repl/types.js

Depends on https://github.com/babel/babel/pull/8649
Preview: https://deploy-preview-1816--babel.netlify.com/repl#?build=master

Add support for decorator options in presets

---

docs/tools/babel_cli/install.md

added instructions in docs to use babel 7 packages

fixes #1928

---

docs/config-files.md
website/versioned_docs/version-7.1.0/config-files.md

Changes the word 'that' to 'than' in order for the sentence to read correctly.

- Change 'that' to 'than'

---

docs/config-files.md

I think "which having" is supposed to be "without having".

fix typo: which -> without

---

website/data/sponsors.yml
website/pages/en/index.js
website/pages/en/support.js
website/siteConfig.js
website/static/css/index.css
yarn.lock

Could be better but the current site takes too much space anyway? Should do a separate donator page as well (feel free to modify though)

update sponsors, modify view

---

docs/plugin-transform-named-capturing-groups-regex.md

https://github.com/babel/babel/pull/7105

Docs for @babel/plugin-transform-named-capturing-groups-regex

---

website/blog/2019-01-21-7.3.0.md

Also https://github.com/babel/website/pull/1954

7.3.0 post

---

docs/template.md
website/versioned_docs/version-6.26.3/babelrc.md
website/versioned_docs/version-7.0.0/template.md

Fix broken links

---

website/versioned_docs/version-7.0.0/parser.md
website/versioned_docs/version-7.2.0/parser.md
website/versioned_docs/version-7.3.0/plugin-proposal-pipeline-operator.md

smart for parser was added in 7.2 and the transform for smart in 7.3

Fix docs for pipeline

---

docs/core.md

docs(core): Fix typo

---

docs/plugin-proposal-private-methods.md
docs/plugins.md
website/versioned_docs/version-7.2.0/plugin-proposal-private-methods.md
website/versioned_docs/version-7.2.0/plugins.md
website/versioned_docs/version-7.3.0/plugin-proposal-private-methods.md

Fixes https://github.com/babel/website/issues/1966.

Add missing docs for proposal-private-methods

---

website/package.json
website/siteConfig.js
website/yarn.lock

Last updated by and scroll to top!

docusaurus@1.7.2

---

website/versioned_docs/version-7.0.0/plugin-transform-flow-strip-types.md
website/versioned_docs/version-7.0.0/preset-flow.md

Closes https://github.com/babel/website/issues/1973

Add `all` option to flow plugin docs

---

docs/parser.md
docs/plugin-proposal-partial-application.md
docs/plugin-syntax-partial-application.md
docs/plugins.md
docs/types.md

This PR adds the documentation for #1974 Partial Application proposal
It addresses the following:
- @babel/parser - Add partialApplication plugin
- @babel/types
- @babel/plugin-syntax-partial-application
- @babel/plugin-proposal-partial-application

Documentation for Partial Application proposal

---

docs/template.md

Babel PR: https://github.com/babel/babel/pull/9648

Add docs for template placeholders

---

website/siteConfig.js
yarn.lock

Also lock file was not up2date, simply calling yarn changed it

Disable git calls to make build way faster

---

website/pages/en/versions.js

Add key to array of elements

---

docs/v7-migration.md

This badge doesn't seem like it's really needed:

Remove unneeded badge

---

docs/plugin-transform-typescript.md
website/versioned_docs/version-7.0.0/plugin-transform-typescript.md

Closes https://github.com/babel/babel/issues/9681

Document alternatives to tsconfig.json

---

docs/config-files.md

Changed `api.env` text to reference `api.cache` correctly.

Updated copy in config-files.md

---

docs/core.md
website/versioned_docs/version-7.0.0/core.md

Add DEFAULT_EXTENSIONS  export to the documented list of features.

docs(core): Add DEFAULT_EXTENSIONS export

---

website/pages/en/index.js

Just some quick styling changes to the intro paragraphs above the sponsors section. What looks like content changes is just prettier.

Update main page styles

---

docs/config-files.md
website/versioned_docs/version-7.0.0/config-files.md
website/versioned_docs/version-7.1.0/config-files.md

Fixes: https://github.com/babel/babel/issues/10052

Document should not use api.cache and api.env together

---

website/versioned_docs/version-7.4.0/polyfill.md

Fixes https://github.com/babel/website/issues/2039

Add deprecation message to polyfill@7.4.0

---

docs/cli.md
website/versioned_docs/version-6.26.3/cli.md
website/versioned_docs/version-7.0.0/cli.md

corrected error docs page for babel-cli.

corrected similar error in versioned docs

---

docs/plugin-transform-typescript.md

Documentation for https://github.com/babel/babel/pull/9785

Add TypeScript namespaces documentation

---

website/blog/2019-06-26-7.5.0.md
website/blog/2019-07-03-7.5.0.md
website/static/css/code-blocks.css

Other docs/repl PRs to merge before v7.5.0:
Rendered version: https://deploy-preview-2051--babel.netlify.com/blog/2019/06/26/7.5.0

v7.5.0 blog post

---

website/yarn.lock
yarn.lock

Upgrades all dependencies to fix security warnings

chore(deps): Upgrade all dependencies

---

docs/types.md
website/versioned_docs/version-6.26.3/types.md
website/versioned_docs/version-7.0.0/types.md
website/versioned_docs/version-7.2.0/types.md
website/versioned_docs/version-7.4.0/types.md

For https://github.com/babel/babel/issues/10195

template element value type

---

docs/learn.md

Breaking it in two lines makes it true.

Expression was false

---

docs/plugin-transform-react-jsx.md

Fix @babel/plugin-transform-react-jsx example output

---

docs/index.md
docs/learn.md
docs/plugin-transform-flow-comments.md

Not necessarily fix broken links, but make things a bit more consistent.

Fix old and inconsistent links

---

docs/parser.md

https://github.com/babel/babel/pull/10363

Add docs parser error recovery

---

docs/parser.md
website/versioned_docs/version-7.7.0/parser.md

Fixed link to `proposal` of `topLevelAwait`.

docs: parser: fix link

---

docs/configuration.md

Fix minor typos in configuration.md

---

website/blog/2020-01-10-7.8.0.md

Feel free to directly edit the contents.

7.8.0 release post

---

website/data/tools/jest/usage.md

Update the link to `jest/babel-jest` repo.

Update link to current version (fixes #2169)

---

docs/plugin-proposal-object-rest-spread.md
docs/plugin-transform-modules-amd.md
docs/plugin-transform-modules-commonjs.md
docs/plugin-transform-modules-systemjs.md
docs/plugin-transform-modules-umd.md
website/versioned_docs/version-7.0.0/plugin-proposal-object-rest-spread.md
website/versioned_docs/version-7.0.0/plugin-transform-modules-amd.md
website/versioned_docs/version-7.0.0/plugin-transform-modules-commonjs.md
website/versioned_docs/version-7.0.0/plugin-transform-modules-systemjs.md
website/versioned_docs/version-7.0.0/plugin-transform-modules-umd.md

Closes https://github.com/babel/babel/issues/11127

docs: add caveats for commonjs modules transform

---

docs/editors.md
website/versioned_docs/version-6.26.3/editors.md

Update broken link to VSCode extension

---

docs/options.md
website/versioned_docs/version-7.0.0/options.md
website/versioned_docs/version-7.1.0/options.md
website/versioned_docs/version-7.8.0/options.md
website/versioned_docs/version-7.8.4/options.md

Should be a bookmark/document fragment identifier.

Fix Broken "Merging" Link

---

docs/plugin-transform-typescript.md
website/versioned_docs/version-7.5.0/plugin-transform-typescript.md
website/versioned_docs/version-7.7.0/plugin-transform-typescript.md
website/versioned_docs/version-7.8.0/plugin-transform-typescript.md

isolateModules -> isolatedModules
https://www.typescriptlang.org/docs/handbook/compiler-options.html

@babel/plugin-transform-typescript: Fix typo 

---

docs/preset-env.md
website/versioned_docs/version-7.0.0/preset-env.md
website/versioned_docs/version-7.4.0/preset-env.md
website/versioned_docs/version-7.8.0/preset-env.md

It was moved in babel/babel#10899.

Update link to plugin-features.js

---

docs/plugin-transform-react-jsx-source.md

Docs PR to go with https://github.com/babel/babel/pull/11139

react-jsx-source: add columnNumber property

---

docs/preset-env.md

I will also add this to the repl once it's released.

Add docs for preset-env's bugfixes option

---

docs/plugin-transform-async-to-generator.md
website/versioned_docs/version-7.0.0/plugin-transform-async-to-generator.md

add caveat to async-to-generator

---

website/blog/2020-03-16-7.9.0.md

As usual, feel free to edit/suggest edits!
> Preview: https://deploy-preview-2204--babel.netlify.com/blog/2020/03/16/7.9.0

7.9.0 release post

---

docs/options.md
website/versioned_docs/version-7.0.0/options.md
website/versioned_docs/version-7.1.0/options.md
website/versioned_docs/version-7.8.0/options.md
website/versioned_docs/version-7.8.4/options.md

Refer to parser/generator options in `parserOpts`/`generatorOpts` descriptions.

refer parser and generator options

---

website/yarn.lock
yarn.lock

Bump some deps for audit

---

docs/node.md
website/versioned_docs/version-6.26.3/cli.md
website/versioned_docs/version-7.0.0/node.md
website/versioned_docs/version-7.8.0/node.md

The debug option is depracated

[docs] update `--debug` to `--inspect` in node.md

---

js/minirepl.js

Update the landing page mini-repl settings to a modern one.
Added external helpers and loose mod to minimize the code size, since it is mini-repl.

polish: update landing page minirepl config

---

js/repl/PluginConfig.js

fix(repl): bump prettier to version 2

---

js/repl/PluginConfig.js
js/repl/Repl.js
js/repl/WorkerApi.js
js/repl/loadPlugin.js

hotfix: use unpkg.com

---

docs/preset-env.md
website/versioned_docs/version-7.0.0/preset-env.md
website/versioned_docs/version-7.4.0/preset-env.md
website/versioned_docs/version-7.8.0/preset-env.md
website/versioned_docs/version-7.9.0/preset-env.md

Fixes https://github.com/babel/website/issues/2241.

Fix preset-env caveat link

---

js/repl/ReplOptions.js

While doing #2257 I noticed we have this misspelled prop in one place.

Fix decorators mode picker

---

docs/preset-env.md

Docs companion for https://github.com/babel/babel/pull/11451

feat: add class features to shippedProposals

---

website/blog/2020-05-25-7.10.0.md

https://deploy-preview-2260--babel.netlify.app/blog/2020/05/25/7.10.0

7.10.0 blog post

---

docs/standalone.md

Just a minor spelling update in the docs :)

Update Doc Spelling

---

package.json
webpack.config.js
yarn.lock

Fixes #2254 
To check, please visit https://deploy-preview-2269--babel.netlify.app/repl

fix: output ascii code

---

docs/standalone.md

Related: https://github.com/babel/babel/pull/11594, https://github.com/babel/babel/pull/8831

add passing options example on @babel/standalone

---

package.json
website/pages/en/repl.js
yarn.lock

chore: update codemirror

---

website/package.json
website/yarn.lock

Fixes #2323
To validate the fix, please click https://deploy-preview-2324--babel.netlify.app/docs/en/config-files and click "6.x vs 7.x .babelrc loading" in the TOC.

chore: bump docusaurus

---

js/repl/ExternalPlugins.js
js/repl/PresetLoadingAnimation.js

Fix loading animation for external plugins

---

docs/plugin-transform-typescript.md
website/versioned_docs/version-7.5.0/plugin-transform-typescript.md
website/versioned_docs/version-7.7.0/plugin-transform-typescript.md
website/versioned_docs/version-7.8.0/plugin-transform-typescript.md
website/versioned_docs/version-7.9.0/plugin-transform-typescript.md

Remove unused and dupe defs in transform-typescript

---

website/data/tools/rollup/install.md

fix rollup babel installation command

---

website/blog/2020-10-15-7.12.0.md

PREVIEW: https://deploy-preview-2395--babel.netlify.app/blog/2020/10/15/7.12.0

Blog post for 7.12.0

---

js/repl/Repl.js
js/repl/ReplOptions.js

I was tired of env being impossible to disable.

Properly persist env preset state

---

docs/plugin-proposal-class-static-block.md
docs/plugin-syntax-class-static-block.md
docs/plugins.md

Add docs about `@babel/proposal-class-static-block` introduced in Babel 7.12

add class static block

---

docs/generator.md

Add docs for decorator before export in babel generator

---

docs/helper-plugin-test-runner.md
docs/parser.md
docs/roadmap.md
docs/v7-migration.md
website/blog/2017-09-12-planning-for-7.0.md

Update source references to the `main` branch.

chore: update Babel source links

---

README.md

This PR reverts #2368, since Hactober is finished.

Reverts #2368

---

website/pages/en/setup.js

Update tools page instructions

---

docs/preset-env.md

Fixes https://github.com/babel/babel/issues/12581

docs: recommend to use decimal corejs versions

---

docs/usage.md

Resolves https://github.com/babel/babel/issues/12617.

polish: mention preset-env docs in usage.md

---

docs/preset-env.md

Please forgive me if I'm misunderstanding the current version (english is not my native language), but it let me thinks that I have to choose one of the three described options to polyfill stable features.

Clarify options to polyfill proposals

---

docs/plugin-proposal-record-and-tuple.md

Docs for https://github.com/babel/babel/pull/12145
cc @rickbutton

Docs for `@babel/plugin-proposal-record-and-tuple`

---

docs/parser.md

https://github.com/babel/babel/pull/12469#issuecomment-782122509

Add `moduleBlocks` to parser plugins

---

website/blog/2021-02-22-7.13.0.md

Fix table layout in the release log. The table is now split evenly.
https://deploy-preview-2455--babel.netlify.app/blog/2021/02/22/7.13.0

fix: make it 50-50

---

docs/preset-env.md

Closes https://github.com/babel/babel/issues/12878.

docs: clarify targets.node candidate values

---

docs/traverse.md

remove $ at start of install command since coping the line also adds $ to the start of the line in the command

Edit to doc traverse.md

---

docs/options.md

https://github.com/babel/babel/pull/13031#pullrequestreview-617888976

Specify how `browserslistConfigFile` paths are resolved

---

js/minirepl.js
website/pages/en/index.js
website/static/css/minirepl.css

Improves [CLS](https://web.dev/cls/) caused by minirepl in index page with to put dummy transparent div.
**before:**
https://user-images.githubusercontent.com/14838850/113466481-33711480-9477-11eb-995a-86694de5b1d6.mp4
**after:**
https://user-images.githubusercontent.com/14838850/113466474-2522f880-9477-11eb-9be2-2a71f8b09b38.mp4

Improves CLS caused by minirepl in Index page

---

docs/plugin-proposal-class-properties.md
docs/plugin-proposal-private-methods.md
docs/plugin-transform-modules-amd.md
docs/plugin-transform-modules-commonjs.md
docs/plugin-transform-modules-systemjs.md
docs/plugin-transform-modules-umd.md
docs/plugin-transform-regenerator.md
docs/preset-env.md

Fixes #2483
Missed adding the note to class-properties for some reason, thanks @thernstig! Also private-methods. Also changed preset-env note as well

add note about preset-env to a few missed plugins

---

docs/index.md

Change https://babeljs.io/docs/en/ to state “… (through core-js/stable)” instead of "... (through @babel/polyfill". Solves #2240

Update index.md to promote core-js/stable instead of @babel/polyfill

---

docs/preset-env.md

tweak corejs 2 config example

---

js/repl/Repl.js
js/repl/UriUtils.js
js/repl/replUtils.js
js/repl/types.js

Fix REPL builtins option

---

docs/features-timeline.md
website/blog/2021-04-26-7.14.0.md
website/blog/2021-04-29-7.14.0.md

Preview: https://deploy-preview-2508--babel.netlify.app/blog/2021/04/26/7.14.0

Babel 7.14.0 blog post

---

docs/assumptions.md

Fixes https://github.com/babel/babel/issues/13257#issuecomment-832120670
/cc @ehoogeveen-medweb

docs: update mutableTemplateObject docs

---

docs/preset-env.md

update shippedProposals docs

---

docs/preset-env.md

https://babeljs.io/docs/en/babel-preset-env#shippedproposals
Related PR: #2528

shippedProposals version wrapper fix

---

website/pages/en/index.js

`v7.14.0` was released some time ago, would be amazing to update version on [babel.dev](https://babel.dev/) :).

Updated link to latest version blog post: 7.13.0 -> 7.14.0

---

website/data/sponsors.yml
website/pages/en/index.js
website/siteConfig.js

Can do this until we figure out the github api to get sponsors data like for OC (it comes through OC as "github" vs individualized which makes sense)

add manual github sponsors

---

js/repl/Repl.js
js/repl/ReplOptions.js
js/repl/UriUtils.js
js/repl/compile.js
js/repl/replUtils.js
js/repl/types.js

fixes #2532 
Preview: https://deploy-preview-2539--babel.netlify.app/repl

Add assumptions to repl UI

---

docs/plugin-proposal-private-property-in-object.md
docs/plugins-list.md
website/sidebars.json

Docs for https://github.com/babel/babel/pull/13554

Add docs for private brand checks in `preset-env`

---

scripts/download-sponsors.js

This was a breaking change in the GraphQL API that caused our website builds to fail - https://github.com/opencollective/opencollective-api/pull/6178

Fix GraphQL query in the download-sponsors script

---

docs/generator.md
docs/parser.md
docs/plugin-proposal-pipeline-operator.md
docs/plugin-syntax-pipeline-operator.md

See babel/babel#13191 and babel/babel#13416.

Proposal: Hack pipes

---

website/blog/2021-07-26-7.15.0.md

Add 7.15.0 blog post

---

docs/options.md
docs/preset-env.md

related https://github.com/babel/babel/issues/12903#issuecomment-838261027

docs: clarify how `esmodules: true` works with `browserslist` config

---

docs/parser.md

Update docs for https://github.com/babel/babel/pull/13713

Update docs for static blocks in `parser`

---

docs/plugin-transform-typescript.md

remove some outdated caveats for TS const enum

---

js/repl/PluginConfig.js
js/repl/loadPlugin.js
js/repl/types.js

closes #2587
https://bundle.run/@babel/polyfill@7.x is available

fix: @babel/polyfill@7 is broken on bundle.run

---

docs/parser.md
docs/plugin-transform-typescript.md
docs/preset-typescript.md

https://github.com/babel/babel/pull/13838

Add docs for `disallowAmbiguousJSXLike`

---

website/pages/en/index.js

New version of `Babel` released 🥳 !

index: 7.15.0 -> 7.16.0

---

docs/config-files.md

fixes a little typo in the docs

Update config-files.md to fix typo

---

docs/preset-env.md

docs: fix target link

---

docs/preset-env.md

no-targets link is broken, this fixes it

docs: fix no-targets link

---

js/repl/PluginConfig.js
js/repl/Repl.js
js/repl/ReplOptions.js
js/repl/compile.js
js/repl/replUtils.js
js/repl/types.js

Companion PR: https://github.com/babel/babel/pull/14004

feat: support decorators 2021-12

---

website/blog/2022-02-02-7.17.0.md

http://github.com/benjamn/regjsgen → https://github.com/bnjmnt4n/regjsgen

Fix link in blog post

---

website/pages/en/index.js

Congrats with the [new release](https://github.com/babel/babel/releases/tag/v7.17.0) 🎉!

index: 7.16 -> 7.17

---

website/blog/2017-09-11-zero-config-with-babel-macros.md

Fixes a minor typo in "Zero-config code transformation with babel-plugin-macros"

Fix minor typo

---

website/pages/en/index.js

Congratulations 🎉  , that’s amazing 🎈!

feature: index: Babel 7.17 -> 7.18

---

docs/plugin-proposal-destructuring-private.md
docs/plugin-syntax-destructuring-private.md

[Transform plugin preview](https://deploy-preview-2631--babel.netlify.app/docs/en/babel-plugin-proposal-destructuring-private)
[Syntax plugin preview](https://deploy-preview-2631--babel.netlify.app/docs/en/babel-plugin-syntax-destructuring-private)

Add destructuring-private docs

---

docs/preset-env.md

I tried with #2655 before but GitHub's Web UI said nope.
Similar to the section on include above, I went with picking up the term here.
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>

Replace blacklisting with less jargon. Fixes #2654

---

docs/options.md

Fixes https://github.com/babel/website/issues/2658

Update caveats link

---

docs/helper-module-imports.md

maybe typo, add some notes by the way .

typo: addDefault typo

---

docs/configuration.md

Fix: indicates the file type

---

docs/parser.md

Docs for https://github.com/babel/babel/pull/14744

Update R&T docs for 7.19.0

---

website/blog/2022-09-05-7.19.0.md

Preview: https://deploy-preview-2675--babel.netlify.app/blog/2022/09/05/7.19.0

v7.19 blog post

---

docs/plugin-transform-property-literals.md

24588d64 changed this documentation so that it said nothing changed.
I don't know if it also changed anything else.

Restore changes in example

---

js/repl/Repl.js
js/repl/Worker.js
js/repl/WorkerApi.js
js/repl/loadPlugin.js
js/repl/loadScript.js

Allow trying from multiple sources, and add `https://packd.liuxingbaoyu.xyz`.
Fixes: #2651

fix `bundle.run` 502

---

js/repl/PluginConfig.ts
js/repl/compile.ts
js/repl/types.ts

fix `useBuiltIns`

---

docs/parser.md
docs/plugin-syntax-explicit-resource-management.md
docs/plugin-syntax-import-reflection.md

- Added `importReflection` docs
- Added `explicitResourceManagement` docs

Add docs for new parser syntax supported by Babel 7.20

---

website/blog/2022-10-27-7.20.0.md

Fixed typo. Greetings with a new release 🎉!

docs: blog: withuot -> without

---

docs/plugin-proposal-duplicate-named-capturing-groups-regex.md
docs/plugins-list.md

duplicated → duplicate; this is the name the package is published under.

Fix name of plugin-proposal-duplicate-named-capturing-groups-regex

---

js/repl/Repl.tsx
js/repl/ReplOptions.tsx
js/repl/StorageService.ts

feat: Add reset button

---

docs/index.md

fix jsx example syntax error

---

docs/plugin-transform-react-jsx.md
docs/preset-react.md

Per https://github.com/babel/babel/issues/15353#issuecomment-1396675266.
Also added a fragment transform output example for the automatic runtime.

docs: state pragma and pragmaFrag requirements

---

docs/config-files.md

Sorry for using the wrong branch. :)

Add docs about `@babel/core` support for `.cts`

---

docs/assumptions.md

Add docs for `privateFieldsAsSymbols`

---

docs/plugin-proposal-dynamic-import.md
docs/plugin-syntax-dynamic-import.md
docs/plugin-syntax-import-meta.md
docs/plugin-syntax-top-level-await.md
website/sidebars.json

Closes #2737.
Preview link: https://deploy-preview-2740--babel.netlify.app/docs/babel-plugin-proposal-dynamic-import

Add proposal-dynamic-import docs

---

docs/plugin-proposal-async-do-expressions.md
docs/plugin-proposal-do-expressions.md
docs/plugin-proposal-duplicate-named-capturing-groups-regex.md
docs/plugin-proposal-function-sent.md
docs/plugin-proposal-partial-application.md
docs/plugin-proposal-private-methods.md
docs/plugin-proposal-record-and-tuple.md
docs/plugin-proposal-regexp-modifiers.md
docs/plugin-syntax-pipeline-operator.md
website/sidebars.json

Also add supported plugins to the sidebar and applied npm2yarn remarks.
Preview link: https://deploy-preview-2746--babel.netlify.app/docs/babel-plugin-proposal-regexp-modifiers

Add proposal-regexp-modifiers docs

---

docs/preset-env.md

Closes #2250.
Edited from https://github.com/babel/website/pull/2250#issuecomment-629665485

clarify preset-env include plugins format

---

docs/helper-validator-identifier.md
website/sidebars.json

Preview link: https://deploy-preview-2752--babel.netlify.app/docs/babel-helper-validator-identifier
Fixes https://github.com/babel/website/issues/2521.

add helper-validator-identifier docs

---

docs/plugin-proposal-unicode-sets-regex.md
website/docusaurus.config.js
website/src/css/custom.css

Companion of https://github.com/babel/babel/pull/15474.
Preview link: https://deploy-preview-2751--babel.netlify.app/docs/babel-plugin-proposal-unicode-sets-regex
(oh, at first glance the new netlify logo is just like a never-ending spinner.)

add more unicode-sets-regex examples

---

docs/editors.md

Today I used Emacs 27.0 to create my first React app and found it .

add Emacs editor

---

docs/helper-environment-visitor.md
docs/plugin-proposal-unicode-sets-regex.md
website/docusaurus.config.js
website/src/css/custom.css

Closes https://github.com/babel/website/issues/2611
Preview link: https://deploy-preview-2754--babel.netlify.app/docs/babel-helper-environment-visitor

Add helper environment visitor docs

---

website/docusaurus.config.js

Now we can mark the flow code with
<pre>```flow
flow code
```</pre>

add flow syntax highlight

---

docs/plugin-proposal-decorators.md

Updated the spec link from the legacy version to the latest version.

update decorator proposal spec link

---

docs/types.md

Includes changes from https://github.com/babel/babel/pull/15802.

Regenerate types docs

---

docs/v8-migration.md

Docs PR for https://github.com/babel/babel/pull/15585

update Babel 8 node requirements

---

docs/v8-migration-api.md

Docs PR for https://github.com/babel/babel/pull/15869.

add migration note on createConfigItem

---

docs/v8-migration.md

Docs for https://github.com/babel/babel/pull/15810.

Add migration note for syntax plugins removal

---

website/blog/2023-09-25-7.23.0.md

I assume that's what was meant.

Fix typo in blog post

---

docs/plugin-transform-instanceof.md

Fixes https://github.com/babel/babel/issues/13225

remove the note since it is not included in preset-env

---

docs/v8-migration-api.md

Docs PR for https://github.com/babel/babel/pull/16114

Add migration note to ImportExpression changes

---

docs/preset-env.md

https://github.com/babel/babel/pull/16095

[babel 8] Enforce specifying proper core-js version 

---

docs/standalone.md

Docs for https://github.com/babel/babel/pull/11696

Add docs for Babel.packages in standalone

---

docs/preset-flow.md

Docs for https://github.com/babel/babel/pull/16309

Fix `preset-flow` `ignoreExtensions` docs

---

docs/plugin-transform-runtime.md

Docs for https://github.com/babel/babel/pull/16241

Add docs for transform-runtime's `moduleName` option

---

docs/plugin-proposal-decorators.md
docs/v8-migration.md
js/repl/PluginConfig.ts
js/repl/Repl.tsx
js/repl/ReplOptions.tsx
js/repl/compile.ts
js/repl/types.ts

Also added initial REPL support.

Add decorator `2023-11` docs

---

website/blog/2024-02-28-7.24.0.md

Preview: https://deploy-preview-2869--babel.netlify.app/blog/2024/02/28/7.24.0

Add 7.24.0 release post

---

website/blog/2024-02-28-7.24.0.md

Thanks to a user who reported this issue in slack.

Fix wrong links in 2024-02-28-7.24.0.md

---

website/data/tools/node/usage.md

Change broken link going to usage api that doesn't exist to usage  docs.

[FIX] broken link

---

docs/plugin-proposal-optional-chaining-assign.md

Fixes https://github.com/babel/babel/issues/16395

Fix usage on plugin-proposal-optional-chaining-assign

---

docs/plugin-transform-runtime.md
docs/v8-migration.md

Docs for https://github.com/babel/babel/pull/16311

Docs updates for `transform-runtime` cleanup

---

docs/v8-migration-api.md

Ref: https://github.com/babel/babel/pull/16521

[Babel 8] Migration guide for `extra.shorthand`

---

docs/plugin-proposal-duplicate-named-capturing-groups-regex.md
docs/plugin-transform-dotall-regex.md
docs/plugin-transform-named-capturing-groups-regex.md
docs/plugin-transform-unicode-property-regex.md
docs/plugin-transform-unicode-regex.md
docs/plugin-transform-unicode-sets-regex.md

Closes https://github.com/babel/babel/issues/16502

Document that regexp plugins only handle regexp literals

---

docs/v8-migration-api.md

https://github.com/babel/babel/pull/16655

[Babel 8] Doc for removing some `NodePath` methods

---

_redirects
docs/plugin-proposal-duplicate-named-capturing-groups-regex.md
docs/plugins-list.md
website/sidebars.js

Docs PR for https://github.com/babel/babel/pull/16445

Add duplicate-named-capturing-groups to ES2025

---

docs/plugin-proposal-json-modules.md

Docs for https://github.com/babel/babel/pull/16579

Add docs for `uncheckedRequire` option

---

docs/generator.md
docs/parser.md

Resolves https://github.com/babel/babel/issues/16707

improve Babel generator docs

---

docs/preset-react.md

Updated Broken Link Broken Link #2934

---

docs/node.md
docs/v8-migration.md

For https://github.com/babel/babel/pull/16706

[babel 8] Docs for babel/node args order

---

docs/v8-migration.md

https://github.com/babel/babel/pull/16741

[Babel 8] doc: Remove `decimal` from parser

---

docs/v8-migration-api.md

https://github.com/babel/babel/pull/16733

[Babel 8] doc: Split `typeParameter` of `TSMappedType`

---

docs/helper-environment-visitor.md
docs/v8-migration.md
yarn.lock

The code block titles should be wrapped in quotes.

Fix codeblock titles

---

docs/parser.md
docs/v8-migration.md
website/docusaurus.config.js

For https://github.com/babel/babel/pull/16770

Docs for `importAssertions` and `importReflection` removal

---

docs/plugin-proposal-import-attributes-to-assertions.md

Updated the legacy import assertions compat data now that engines begins shipping the attributes syntax.

update import assertions compat data

---

website/docusaurus.config.js

googleapis cannot be accessed in China. :)
Fixes https://github.com/babel/babel/discussions/16985

Using unpkg instead of googleapis

---

docs/v8-migration-api.md

Docs PR for https://github.com/babel/babel/pull/17008

add TSTypeReference migration note

---

docs/v8-migration-api.md

https://github.com/babel/babel/pull/16997

Add docs for `superTypeParameters` -> `superTypeArguments` rename

---

docs/v8-migration-api.md

Docs PR for https://github.com/babel/babel/pull/17012

add migration note to TSTypeQuery typeArguments

---

docs/v8-migration-api.md

https://github.com/babel/babel/pull/16731

[Babel 8] doc: Migration for `TSClassImplements` and `TSInterfaceHeritage`

---

docs/v8-migration-api.md

Docs for https://github.com/babel/babel/pull/17014

add migration note for `TSAbstract` AST change

---

website/src/theme/Footer/index.js

- Updated the Twitter Profile URL from `twitter.com/babeljs` to `x.com/babeljs`.
- As per the request from @nicolo-ribaudo  ,  I have also added a link to the Bluesky account for BabelJS.
- **Here's what the footer looks like after changes:**
- **Here's what the udpated code looks like:**

Updated Twitter URL to x.com and added Bluesky profile link in footer (#2932)

---

website/data/sponsors.yml
website/src/pages/index.js

fix: Correctly display sponsor Igalia

---

docs/v8-migration-api.md

Docs PR for https://github.com/babel/babel/pull/17139

docs: TSHeritageBase expression change

---

js/repl/Repl.tsx

Fix REPL loader style

---

docs/options.md
docs/preset-env.md
docs/v8-migration.md

Docs PR for https://github.com/babel/babel/pull/17188

Update preset env docs

---

docs/parser.md

https://github.com/babel/babel/pull/17149

Add `allowYieldOutsideFunction`

---

docs/v8-migration-api.md

Docs PR for https://github.com/babel/babel/pull/17217

Add variable declarator validation changelog

---

docs/v8-migration.md

Docs PR for https://github.com/babel/babel/pull/17242

add R&T discontinue note

---

docs/v8-migration.md

Docs for https://github.com/babel/babel/pull/17237

Add migration docs for the global `regeneratorRuntime` transform

---

docs/v8-migration.md

This PR is mostly moving things around to find them easier to use:
- rather than splitting the breaking changes in "config" and "compilation", that are highly related to each other anyway, it just splits them based on which packages are affected
- it sorts the packages by:
- core, parser, generator (which are used by everybody)
- preset-env
- preset-react and JSX packages
- preset-typescript and TS packages
- preset-flow and dlow packages
- other -transform- plugins
- other -proposal- plugins
- other packages (eslint-parser and node)

Another pass through v8 migration docs

---

docs/generator.md

Fixes https://github.com/babel/website/issues/3090

Add docs for generator result

---

docs/v8-migration-api.md

Docs for https://github.com/babel/babel/pull/16624

Add docs for Scope references/uids set

---

js/repl/Monaco.tsx
js/repl/Repl.tsx

Fixes: #3100
The linked issue only occurs when the browser is zoomed.

Fix scrollbar issues for REPL

---

website/src/components/repl/ExternalPlugins.tsx
website/src/components/repl/Monaco.tsx
website/src/components/repl/Repl.tsx
website/src/components/repl/lib/loadPlugin.ts
website/src/components/repl/lib/pluginConfig.ts
website/src/components/repl/lib/replUtils.ts
website/src/components/repl/lib/types.ts
website/src/components/repl/lib/uriUtils.ts
website/src/components/repl/lib/workerApi.ts

Only the last commit is new, I will rebase after https://github.com/babel/website/pull/3118 is merged.

Integrate configuration files with the UI
