- scripts/repl.js
Instead of monkey patching `console.log`, we create a console wrapper
and monkey patch that, passing it as an argument to the generated
function so it will always be in scope.
We keep track of the current console wrapper so that any async calls
from previous evaluations will no longer cause output.
Closes #15.
> Fix async calls to console.log.

- docs/usage/modules.md
The flag was changed to be plural in PR 6to5/6to5#190
> Corrected amd-module-id => amd-module-ids (plural) flag per 6to5/6to5#190

- _config.yml
Just a suggestion.
I was browsing the site and thought REPL isn't the most obvious title for this page (accurate though it is).
Something along the lines of "Try it out" or "Live demo" would be more self explanatory, IMO.
Could also be moved to a separate section of the nav to stand out more, but that's a bigger change so wanted to get feedback on this first.
> Clearer title for REPL page

- index.html
Your link on the homepage to the caveats documentation was broken! I went ahead and fixed it for you :kissing_cat:.
> fix caveats link

- docs/learn-es6.md
When ran in the context of a browser, `print()` will call `window.print()` which opens a print dialog. It's very confusing pasting example code into the REPL only to have it open several print dialogs :)
> Change `print` to `console.log` in example code

- docs/usage/caveats.md
This changed in this commit: https://github.com/6to5/6to5/commit/c509d06bc2d74b58b8edf38597b13bc278896c71
> Array destructuring now requires Symbol

- _includes/head.html
- _layouts/docs.html
- index.html
- repl.html
@thejameskyle Let me know if this is roughly what you had in mind and/or if there are other resources that need to be considered.  Note that I used the date_to_xmlschema filter because it puts the timestamp in ISO8601 format, which should be URL safe.  The site.time Jekyll site variable should reflect when the Github Pages server spins up a new site after a publish.
> Cache bust resources via appended timestamp, fixes #6

- scripts/repl.js
@thejameskyle First cut. Let me know if this approach is OK with you. WRT #71
> localStorage support.

- scripts/repl.js
@thejameskyle This is a hotfix to the recent localstorage enhancement.  There is an issue when you first come into the REPL with a browser that supports local storage (i.e. it sets the state to null, then state.code throws).
> fix null state error on initial visit

- scripts/repl.js
Note: This will also "fix" bogus URLs coming in with invalid parms (upon persisting state)
> parseQuery should ignore irrelevant query params

- docs/faq.md
I would wager that this is **the** question people will be most interested in. As such, I've placed it at the top of the FAQ. If you think it'd be better placed somewhere else on the page, nbd, just lemme know and I can move it down.
> Add browser compatibility to the FAQ page.

- docs/usage/transformers.md
Otherwise a link to https://6to5.org/docs/usage/transformers/#self-contained won't show it.
> Move 6to5-runtime box to after the selfContained header

- docs/usage/require.md
The origin code in the repo would create this link address: http://6to5.org/docs/usage/require/polyfill , and it's 404 page.
So the code in the `[]` should be `/docs/usage/polyfill` or `./polyfill`
> Fix invalid link address in the doc/usage/require

- docs/using-6to5.md
If you concatenate the code second, the code be like:
``` js
"use strict";
var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };
var Proxy = function Proxy() {
_classCallCheck(this, Proxy);
};
"use strict";
var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };
var App = function App() {
_classCallCheck(this, App);
};
```
But if you concatenate first, your code is all:
``` js
"use strict";
var _classCallCheck = function (instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } };
var Proxy = function Proxy() …
```
> If you concatenate first, 6to5 won't duplicate code like _classCallCheck

- docs/usage/external-helpers.md
This adds documentation for injecting the `babelHelpers` into window and global.
> Update external helpers doc with global injection

- index.html
Currently, JSX and React example doesn't work.
https://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=%0A%0Aexport%20default%20React.createClass%28{%0A%20%20getInitialState%28%29%20{%0A%20%20%20%20return%20{%20num%3A%20this.getRandomNumber%28%29%3B%20}%3B%0A%20%20}%2C%0A%0A%20%20getRandomNumber%28%29%3A%20number%20{%0A%20%20%20%20return%20Math.ceil%28Math.random%28%29%20*%206%29%3B%0A%20%20}%2C%0A%0A%20%20render%28%29%3A%20any%20{%0A%20%20%20%20return%20%3Cdiv%3E%0A%20%20%20%20%20%20Your%20dice%20roll%3A%0A%20%20%20%20%20%20{this.state.number}%0A%20%20%20%20%3C%2Fdiv%3E%3B%0A%20%20}%0A}%29%3B%0A%0A
This pull request fix this:
https://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=%0A%0Aexport%20de …
> fix "JSX and React" example

- docs/usage/modules.md
Was linking to the wrong section heading.
> Fix link on Modules page

- index.html
AFAIK, it's "CommonJS", not "Common.js", per [their wiki](http://wiki.commonjs.org/wiki/CommonJS).
> Common.js => CommonJS

- docs/usage/runtime.md
Looks like this has been asked for several times by me https://github.com/babel/babel/issues/895 and previously in https://github.com/babel/babel/issues/638. Adding a note about the runtime not supporting AMD might help reduce future duplicates of this.
> Add note about the runtime not supporting AMD

- docs/learn-es6.md
For consistency and readability.
> Docs: added spaces around `==` operator

- docs/usage/transformers.md
- http://babeljs.io/docs/usage/transformers/#utility-inline-expressions
This pull request fixes the result of `utility.inlineExpressions`.
```
$ babel -V
4.6.4
$ cat inline.js
var foo = 5 * 5;
$ babel --optional utility.inlineExpressions inline.js
"use strict";
var foo = 25;
```
> fix the result of `utility.inlineExpressions`

- docs/learn-es6.md
Am I wrong, or should this note mention *all* the collections, not just WeakMaps?
> Update es6 collection polyfill note

- docs/learn-es6.md
The list wasn't actually being displayed as a list on the site, due to the lack of a blank line above the first item:
> Add newline under Module Loaders heading

- docs/usage/cli.md
- docs/usage/external-helpers.md
Formats section was more detailed but I have decided to shorten it to minimum since everybody can simply type it into console and check the output. Sorry that it took so long.
> add docs for double dash and new babel-external-helpers options

- docs/using-babel.md
This PR adds Windows/Linux version of `find` text feature keyboard shortcut.
Thanks!
> Add Windows/Linux version of text find shortcut. Closes #56

- docs/learn-es6.md
* Iterators rely on `Symbol.iterator`
* Generators rely on Regenerator
* Reflect is just an API
> Iterators, Generators, and the Reflect API require the Babel polyfill

- docs/faq.md
- docs/usage/loose.md
- docs/usage/require.md
- docs/usage/runtime.md
Noticed a few typos in the documentation as I was browsing.  Figured I'd fix them as I came across them.
> Fix some minor documentation spelling errors.

- scripts/repl.js
So it's possible to overwrite those in the browser's console for testing. Examples:
```javascript
window.module = {};
window.module.exports = window.exports = {};
window.require = console.log.bind(console, 'require:');
```
> Allows commonjs getters to be defined

- docs/usage/experimental.md
- docs/usage/transformers/index.md
`es7.objectSpread` was changed to `es7.objectRestSpread` in v3.3.10 (https://github.com/babel/babel/commit/39fe737cb619357d321517f925cc3a3cf0004356), although it was not included in the [CHANGELOG](https://github.com/babel/babel/blob/master/CHANGELOG-6to5.md#3310).
> fix references to es7.objectRestSpread

- docs/usage/require.md
When writing a library, it's clear a polyfill should be used and that the require hook automatically includes the polyfill. The warning that the require hook is not suitable for libraries offers no correct alternatives so this pull request updates the documentation on require hooks to point you to the recommend solution of compiling your library and depending on the babel-runtime.
> Specify compilation and the babel-runtime for ES6 libraries

- docs/learn-es6.md
Just replaced it by `ES5` as the doc title also uses the acronym - thought about adding `(commonly referred to as 'JavaScript')` but imho that's too much for these comments and should be treated as a prerequisite to learn ES6.
> Update learn-es6 to clarify 'JavaScript'

- _includes/tools/rails/usage.md
- _includes/tools/sprockets/usage.md
Previous repo mentioned in docs is now 404. Might be something @josh might provide more info about. //cc @TannerRogalsky
> Update repo for sprockets-es6

- _sass/components/_buttons.scss
Prevent overflowing text in featured button on mobile (See image, 1 current, 2 after change).
> Prevent overflowing text in featured button on mobile

- docs/usage/modules.md
The docs showed the body of _interopRequire as being
```javascript
var _interopRequire = function (obj) {
return obj && (obj["default"] || obj);
};
```
But the code in [https://github.com/babel/babel/blob/v5.3.3/src/babel/transformation/templates/helper-interop-require.js](helper-interop-require.js) shows:
```javascript
function (obj) {
return obj && obj.__esModule ? obj.default : obj;
}
```
> Fix _interopRequire to match actual code

- docs/usage/options.md
- docs/usage/require.md
I looked up how the `only` option is treated in code to address #246.
`opts.only = util.arrayify(opts.only, util.regexify);`
`if (opts.only != null) onlyRegex = util.regexify(opts.only);`
`util.regexify` epects:
* glob (this can also be an explicit path)
* rexexp
* array of strings to match **exactly** 
Thus the `register` method currently can't handle an array of glob/regexp.
Corner case is currently passing in an array of arrays of strings to the cli, as these are joined by logical or (`|`) and escaped by `lodash`'s `excapeRegExp` instead of `minimatch`'s `makeRe`.
(But how do you pass an array of arrays via command line?)
> Clarifies "only" option

- docs/advanced/transformers/index.md
The link to the runtime transformer in the "Other" header on [this page](http://babeljs.io/docs/advanced/transformers/#optional) 404's.  The actual page is [here](https://babeljs.io/docs/usage/runtime/).
> Fix runtime transformer link

- Makefile
The babel repo seems to have changed the target dist file for minified browser builds a while ago.
> Include browser.min.js, not babel.min.js.

- _includes/tools/gulp/usage.md
The concat operation should come after the babel transpilation step as seen here:
https://www.npmjs.com/package/gulp-babel
If someone was copying this doc as a gulpfile they could get errors when using modules.
> Fix gulp task sequence. Put concat() after babel()

- scripts/repl.js
If you use setTimeout/setImmediate your console can end up flipping between the current run and previous/outdated runs.
Reproducing:
1. Navigate to the repl (http://babeljs.io/repl/)
2. Ensure "Evaluate" is ticked
3. set the code to:
```js
setInterval(function () {
console.log('fooooooo');
}, 1000)
```
4. Wait a couple of seconds
5. set the code to
```js
setInterval(function () {
console.log('barrrrrrrrr');
}, 1000)
```
6. Observe the console flipping between lots of "fooooo" and lots of "barrrrrr"
> Prevent REPL console flip-flopping

- docs/advanced/external-helpers.md
`metadataUsedHelpers` is now on by default (as per 32f19aff99559e36c3d4fbb946af378a8126b8bf)
Also, the title should be in title case :)
> Remove `metadataUsedHelpers` flag from External Helpers page

- _includes/tools/brunch/usage.md
The key for the plugin's config is just `babel`. It appears to have been listed as `ESbabel` because of a find/replace on the original key name `ES6to5`.
> Fix brunch config example

- _includes/tools/meteor/install.md
- _includes/tools/meteor/usage.md
ICYMI, Babel is installed by default for all new Meteor apps!
> Update setup instructions for Meteor

- docs/usage/experimental.md
Quite a small change! The proposal has moved from https://gist.github.com/jeffmo/054df782c05639da2adb to https://github.com/jeffmo/es-class-properties, as it is indicated inside the gist.
> Update link to ES7 classProperties proposal

- docs/advanced/transformers/other/react.md
According to the JSX documentation
> Since JSX is JavaScript, identifiers such as `class` and `for` are discouraged as XML attribute names. Instead, React DOM components expect DOM property names like `className` and `htmlFor`, respectively.
Edited docs to reflect current JSX standards.
> Update example to match JSX documentation

- docs/advanced/plugins/manipulation.md
I have this following warning `Path#remove has been renamed to Path#dangerouslyRemove, removing a node is extremely dangerous so please refrain using it.`. I'm assuming the doc is not up to date.
> [Manipulation] Replace remove by dangerouslyRemove

- _data/tools.yml
- _includes/tools/jasmine/install.md
- _includes/tools/jasmine/usage.md
Hi @sebmck and @thejameskyle!
By this PR I wil try to explain, how to use Babel.js with Jasmine project.
Often I will setup unit tests by run command `jasmine init`.
This command creates simple json, eg:
```json
{
"spec_dir": "spec",
"spec_files": [
"**/*[sS]pec.js"
],
"helpers": [
"helpers/**/*.js"
]
}
```
I would like to use ES6 syntax with my unit tests but without compiling it is imposible.
I love Babel.js and will try to help people how to (by adds simple line) write specs in ES6.
```json
{
"helpers": [
"../../node_modules/babel-core/register.js",
"helpers/**/*.js"
]
}
```
After adding reference to `register.js` my specs (written in ES6) are properly parsed.
What are thinking about this?
> Setup Babel.js with Jasmine

- _posts/2015-10-29-6.0.0.md
Thanks for the hard work, Babel team! I love using it. 
Just wanted to help in the tiniest of ways by cleaning up a few insignificant typos in the big v6 announcement.
> Fixes trivial typos

- docs/plugins/transform-class-properties.md
- docs/plugins/transform-decorators.md
- docs/plugins/transform-exponentiation-operator.md
- docs/plugins/transform-export-extensions.md
- docs/plugins/transform-function-bind.md
- docs/plugins/transform-object-rest-spread.md
I was having a difficult time figuring out what features some plugins add. I think a "Learn more" section with either a code example or a link would be helpful so people can read more about the feature. Would it be okay if I start adding this section to a few of the plugin's documentation that I know about?
> Add link to blog post about function bind syntax

- _data/tools.yml
- _includes/tools/dotnet/install.md
- _includes/tools/dotnet/usage.md
- _includes/tools/msbuild/install.md
- _includes/tools/msbuild/usage.md
Add mention of ReactJS.NET for C# and MSBuild support. Eventually I'd like to split ReactJS.NET into a smaller project that isn't actually explicitly for React, but this will do for now. This part of ReactJS.NET isn't actually specific to React in any way, it's just wrapping Babel in the V8 or Chakra/MSIE engine (similar to the Ruby integration)
> Add mention of ReactJS.NET

- index.html
Link was originally in Markdown syntax.
> Fix "ES2015 Preset" Link

- docs/usage/require.md
Just updated the [Require Hook](http://babeljs.io/docs/usage/require/) usage page.
Should now be `babel-register` instead of `babel-core/register`
> Updated require hook usage to use babel-register

- docs/setup.md
See https://phabricator.babeljs.io/T6711
tl;dr: I'm trying out Babel and wanted to set up a one shot shell session. I thus skipped the `.babelrc` section (no need for a permanent config file at this point) and ended up surprised that vanilla Babel is just a JS syntax validator.
Update: accidently a whole word (still absent in the commit message title, hopefully you won't mind).
> Move the "no default transformations in v6" note to the usage section.

- _includes/tools/babel_cli/install.md
- _includes/tools/babel_cli/usage.md
- _includes/tools/webstorm/install.md
- docs/usage/cli.md
- Followup of https://github.com/babel/babel/pull/3150
- Fixes https://github.com/babel/babel.github.io/issues/632
> Fix documentation to not install babel-cli globally

- _sass/bootstrap/_navbar.scss
Position: fixed adds a lot of repaint on scroll to the page. Adding `will-change: transform` will promote it to it's own layer.
> add will-change property to sticky header

- docs/usage/polyfill.md
Currently, the docs suggest the user to just use `require("babel-polyfill");` at the top of the entry point into their application. This can lead to confusion and difficult to debug bugs with the polyfill not being loaded if the entry point later uses ESE6's `import` syntax to load other app dependencies.
Because `import`s are hoisted to the top of the file, having an application entry point that looks like this:
```javascript
require("babel-polyfill");
// routes uses polyfilled features in definition (such as creating Sets, etc)
import routes from 'routes';
...
```
would cause the `import` statement to be hoisted above the `require` statement and cause errors in `routes.js`.
> Add note in docs for importing babel-polyfill with ES6 import syntax

- docs/usage/options.md
This option doesn't exist in Babel@6:
https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/options/config.js
This PR is to add that feature back but until it is merged and released the docs should be corrected. Ideally this could be merged right away and that PR can add the doc back when it is released.
https://github.com/babel/babel/pull/3155
> Remove invalid Babel6 option

- docs/usage/polyfill.md
Currently https://babeljs.io/docs/usage/polyfill/ says 'ensure the polyfills are loaded first: javascript import "babel-polyfill";' in one line.
> Fix rendering bug on babeljs.io website

- _includes/tools/babel_register/install.md
and seems to conflict with `docs/usage/require.md`
> global flag doesn't work

- docs/plugins/external-helpers.md
Ref - https://github.com/babel/babel/pull/3205
- Fixes #658
> Renamed babel-plugin-external-helpers-2 to babel-plugin-external-helpers

- scripts/repl.js
I use the Babel REPL website a lot, and I also use <kbd>⌘</kbd> + <kbd>L</kbd> a lot to focus the browser address bar. In the Babel REPL site I can't because the editor hijacks this shortcut, as well as the browser Find command under <kbd>⌘</kbd> + <kbd>F</kbd>.
Neither of these features make sense for a REPL that's most typically used to play around with small snippets of code.
> Get rid of REPL keyboard hijacking annoyances.

- docs/setup.md
Babel 6's new tool `babel-doctor` [requires users to be using npm >= 3.3](https://github.com/babel/babel/blob/e75f2ef5bb340e71ec413709eaa1311beed2a834/packages/babel-cli/src/babel-doctor/rules/npm-3.js). It is not clear in any docs or blog posts whether or not Babel has officially dropped support for npm 2.x but if this is true it should be very prominently displayed in the docs.
Thanks for all the great work!
> Warn users that npm >= 3.3.0 is required to use babel 6.x

- docs/learn-es6.md
Someone showed me [an example](https://docs.google.com/presentation/d/1uYY4UzjU8QAojLylGod2JUp691JaXGqSCgtQYRnxfGE/edit#slide=id.ged7eaf7f0_0_131) of this but couldn't find it in the docs. Turned out to be invalid syntax.. 
An example might be nice.
> Added Destructuring + default arguments example

- docs/plugins/external-helpers.md
This fixes missing Github link and leads to the correct and newest external helpers plugin in npm.
> Fix external helpers plugin package link

- docs/plugins/preset-react.md
The react preset [includes babel-plugin-transform-react-display-name](https://github.com/babel/babel/blob/master/packages/babel-preset-react/index.js#L7) but this wasn't reflected in the doc page.
> Update react preset doc to include displayName transform

- _layouts/page.html
Saw a lot of other docs sites have this - I think it's good so it's easy for others to fix typos, etc.
We can change the wording too (or move it somewhere else if you don't like that).
@thejameskyle
> Add link to edit docs page in github

- docs/plugins.md
I think it's probably better to move the transform plugins first since people probably will want to see those more.
Also just added `Plugin` in front of the headers
> move plugin sections around

- _includes/tools/babel_register/usage.md
- Added newline above es6 example
Newline needed so it renders as code block and not as inline code.
It seems that [Github's markdown rendering](https://github.com/babel/babel.github.io/blob/master/_includes/tools/babel_register/usage.md) works without this newline but jekyll doesn't in the [live site](http://babeljs.io/docs/setup/#babel_register).
> Make code block render in babel-register usage docs

- docs/setup.md
URL contains a trailing slash which results in a 404
> Invalid URL

- _includes/tools/jasmine/usage.md
According to the [example project](https://github.com/piecioshka/test-jasmine-babel/blob/master/test/jasmine.json) and [Jasmine code](https://github.com/jasmine/jasmine-npm/blob/793b7bb4f3ba4f420c7183b825ec477ebcf6eb52/lib/jasmine.js#L82), the root path of the helpers is not `spec/support` but `spec/`.
> Correct the helpers path in Jasmine

- _includes/tools/make/usage.md
Changes to `.babelrc` should trigger a rebuild.
> Update usage of Make

- docs/usage/require.md
I was initially confused by the existing language, thinking I needed the polyfill any time I used `babel-register`. This attempts to clarify things, based on my rudimentary understanding.
> Clarify polyfill dependency

- repl.html
Fixes #748
Generator functions no longer throw an error about regeneratorRuntime not being loaded. Example URL: [http://localhost:4000/repl/#?evaluate=true&presets=es2015&experimental=false&loose=false&spec=false&code=function*%20a()%20%7B%0A%20%20yield%201%3B%0A%20%20yield%202%3B%0A%7D&playground=true](http://localhost:4000/repl/#?evaluate=true&presets=es2015&experimental=false&loose=false&spec=false&code=function*%20a()%20%7B%0A%20%20yield%201%3B%0A%20%20yield%202%3B%0A%7D&playground=true)
> Switch to NPMCDN for REPL, and load polyfill

- docs/plugins/preset-stage-1.md
- docs/plugins/syntax-decorators.md
- docs/plugins/transform-decorators.md
> Add decorators warning

- _data/tools.yml
- _includes/tools/ava/install.md
- _includes/tools/ava/usage.md
Hello everyone, this is my first PR! :smile: 
While trying out AVA, I've noticed that there's no reference on the site for this test framework which heavily uses Babel for transpiling test files.
Thanks!
> Add documentation for AVA test framework

- docs/plugins/transform-react-inline-elements.md
The [output changed](https://github.com/babel/babel/blob/3232c30f61c2d321f7813ec406d8b28392bcadc0/packages/babel-plugin-transform-react-inline-elements/test/fixtures/inline-elements/component-with-props/expected.js) since this example was written.
> Update the docs of transform-react-inline-elements

- index.html
I know we may not want to go for this but figured I could do it for a suggestion. (The idea is to explain the simplest way to use it without clicking on anything else)
Current:
Proposed (or something similar):
@jmm @loganfsmyth
> An more realistic example on homepage

- _config.yml
to mitigate ...
```
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
```
> added jekyll-paginate to _config.yml/gems

- docs/setup.md
I find it annoying to scroll to reach the installation/usage step when I select a tool, I tried to address that in this PR, scroll to the installation step when a tool is selected, please refer the behavior in the attached gif.
> scroll to the installation step when a tool is selected

- index.html
Add some more links?
I kind of want to switch the babel blueprint picture out with just an example plugin like on astexplorer?
> add more plugins + link them to plugin pages, fix typo, misc

- docs/learn-es6.md
This line: 
```js
alert("2π = " + exp(pi, e));
```
* Result = `23.14070064895278` == e^π
* `2π`  should be `e^π`
* `exp` expects only one argument
> Fix math in Modules example

- docs/usage/cli.md
Include a callout to inform users that ES6-style module loading is not supported in `babel-node`.
> Inform about babel-node limitations.

- package.json
As [`bootstrap` is being tracked and checked in](https://github.com/babel/babel.github.io/tree/master/_sass/bootstrap), I guess `make:build` is not required, thus ...
* removed package.json:scripts.build
* added package.json:scripts.serve
* removed the bootstrap-sass from package.json:devDependencies
* in fact removed package.json:devDependencies
Please close the PR if it sound inappropriate. Thanks!
> removed make:build as bootstrap is being tracked

- docs/plugins/transform-remove-console.md
> transform-remove-console: fix typo

- _includes/footer.html
- Forked @developit's version and fixed the urls https://developit.github.io/babel-legacy-docs/ (the relative links are broken)
http://henryzoo.com/babel.github.io/
annoying that its changing to my cname though. or can pr their version and link to that
> Link to a built version of the Babel 5 docs rather than the repo

- docs/plugins/external-helpers.md
In the source, the helpers are assigned to `self`, not `this`.
https://github.com/babel/babel/blob/5b89849f432cfc034860f495b5001039123e7754/packages/babel-helpers/src/helpers.js#L297
> External helpers doc: this → self

- scripts/repl.js
Opera had problems with this. If you create a new `<input>` element, its type defaults to  `text`. You can set a `value` now, but when you alter the type afterwards to `checkbox` the value will get replaced by the string `"on"`. Which is not a known babel preset :-/
This fix just sets the `.type`  before the `.value` to make it work again.
> fix checkbox creation

- docs/usage/cli.md
Adds an example of how to use the `--ignore` option on the cli, as mentioned in https://github.com/babel/babel.github.io/issues/286
Also removes `#` from heading that seemed inconsistent with others.
> Add usage example for ignoring files

- docs/usage/babelrc.md
Had to dig into the code to find out that it uses lodash's `mergeWith` for merging the options. Figured I might not be the only one searching for that clarification :)
> Add a note on merging env options

- _includes/tools/ava/usage.md
Hello,
I've updated the AVA documentation, pointing the "more information" link to the AVA recipe "Configuring Babel".
@sindresorhus the AVA default Babel configuration, still includes the `"espower"` and `"transform-runtime"`plugins? Because I didn't see the being mentioned anywhere in the recipe.
Thanks!
> Update AVA documentation

- docs/plugins/preset-stage-1.md
- docs/plugins/preset-stage-2.md
See: https://github.com/babel/babel/pull/3613
TL; DR:
> TC39 advanced decorators to stage 2, w/ crucial open questions re:
> function, param, & property decorators needing good answers for
> progress.
- @BrendanEich
> Move decorators, transform-class-properties from stage-1 to stage-2 preset docs

- docs/plugins/transform-es2015-arrow-functions.md
Formatting based on the existing documentation for template-literals.
> Document the `spec` option for arrow functions

- docs/plugins.md
This makes the `preset-latest` plugin a bit more prominent on the page.
---
Not sure if this was intentionally left out of the list, but I think a bunch of folks would be interested in using it.
> Add latest plugin link to plugins page

- docs/plugins.md
This updates the structure to reflect ES2016 and ES2017
I removed the plugins from the preset section and instead created new sections in the plugins section for ES2016 and ES2017.
Also changed the syntax plugins to be separated into active/deprecated and the ones that are now active by default.
> Restructure the plugins/presets

- _sass/pages/_repl.scss
- repl.html
- scripts/repl.js
Updates the REPL to contain the new presets (es2016, es2017, latest). Since the list of presets was getting pretty long, I moved it to be a dropdown list:
Live demo: http://babeldev.dan.cx/repl/
I had to hack around Bootstrap a bit. Its dropdowns close whenever an item within them is clicked, so I needed to add an event handler to avoid that happening. Additionally, using `<label>` tags messes up the dropdown styling, so I just used an `<a>` and handle that in the event handler. #yolo
> Update REPL to contain new presets

- repl.html
- scripts/repl.js
Adds Babili to the REPL. It is lazy-loaded, only if the "Babili" checkbox is checked.
Ideally #899 should be merged before this, as it collapses the preset list into a dropdown leaving more room for extra checkboxes like this. Both PRs are separate and can be merged individually though.
This is how it looks with both #899 and this PR:
> Add Babili to REPL

- docs/plugins/preset-es2017.md
`preset-es2017` does not have `transform-exponentiation-operator`.
Seems it should be fixed another example like `async/await`.
> Fix incorrect example in `preset-es2017.md`

- scripts/repl.js
I use the babel repl many times a day, and it's always been a pain that `console.clear()` and `console.error()` did not proxy to the _real_ console.
This obviously solves that.
So the common usage of adding `console.clear()` to the top of your code between REPL iterations will now clear the real console, as you would expect in JSBin, etc.
> proxy console.clear() and console.error() to the real console

- docs/plugins/preset-es2016.md
babel-preset-es2016 does not include es2015
> fix misinformation

- docs/usage/babelrc.md
Based on https://phabricator.babeljs.io/T2173, I think it's a good idea to explicitly state this in the docs
> Clarify that callback options cannot be expressed in .babelrc files

- _data/navigation.yml
Clicking the FAQ link in the navbar currently results in a 404 page because `_data/navigation.yml` has the url in upper case.
> Fix lettercase for FAQ path in navbar

- scripts/repl.js
This also removes a duplicate call to the real console that was introduced in https://github.com/babel/babel.github.io/commit/8925d2259195f1c13ddd43080252b52ba6460ef1#diff-abe23564b3ea7bb6b8680951a5f778d3R362
> proxy other console methods to their corresponding real methods

- docs/usage/caveats.md
https://github.com/facebook/regenerator/blob/master/runtime.js indicates it's moved.
> caveats: update regenerator-runtime link

- index.html
In this case we want to use it as a verb. "Babel Setup" would make more sense if "setup" was kept.
> Change to "Set up Babel" from "Setup Babel"

- docs/learn-es6.md
Adding a note + example about arrow functions' lexical `arguments` to spare others the [emotional distress of learning this the hard way][3].
With reference to [this][1] and [this][2]. 
Credits to @empyrical at https://github.com/lukehoban/es6features/pull/87
[1]: https://twitter.com/left_pad/status/737620004003155968
[2]: https://twitter.com/left_pad/status/737717067147825153
[3]: https://twitter.com/panda_whisperer/status/736791933142454273
> Add Arrow Function lexical `arguments` example

- _config.yml
Paul Irish says that `//` is now an anti pattern.
Primarily, I came here to update lodash in the REPL
Thanks!
> Upgrade lodash from 2.4.1 to 4.13.1 & change from // to https

- docs/plugins/transform-async-generator-functions.md
Add a newline between Example Usage and usage code.
Ref: http://babeljs.io/docs/plugins/transform-async-generator-functions/
> Fix markdown formatting

- docs/faq.md
- Add links for build instructions and contributing. I expected to find these links on the github.io site already but couldn't.
> add build and contribute links

- _sass/components/_buttons.scss
- docs/setup.md
- index.html
Idea: moving the buttons to the first part of the page? (had to change the color too)
the Setup color is on hover/active
> move setup/try buttons

- _layouts/docs.html
This is related to #802 - same idea but reuses the [Discourse Site](https://discuss.babeljs.io).
Unfortunately I can't test this locally - localhost needs to be an embeddable host. We'd also have to add `babeljs.io` as a host.
It would take minimal work to integrate with the existing discourse server. If nobody is willing to take the time I can do so if credentials are provided - please email if so.
[Integration Instructions](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963)
> Integrate Discourse on doc pages.

- _layouts/docs.html
- _layouts/post.html
- scripts/social.js
Disqus was still referring to 6to5.
> Remove outdated Disqus from posts; add Discourse

- docs/usage/cli.md
[The docs](https://babeljs.io/docs/usage/cli/) currently just warn people against using `babel-node` in production.
> You should not be using `babel-node` in production.
While this may make sense to Node.js veterans, for newbies like myself it would help greatly to see an example or reference implementation of using Babel in a production deployment. Since there's already an "official" [example-node-server](https://github.com/babel/example-node-server) repo, mentioning this repo as a reference in the same warning block I believe will help more people get started with using Babel correctly.
> Link to Example Node Server w/ Babel

- _includes/scripts.html
Seems to be because docs is in _layouts so its not a `page` and the variable needs to be `layout`.. wow and I thought it was something else the whole time.
https://github.com/babel/babel.github.io/blob/83283169456d0f7c869a1eff9ab663c184692ed9/_layouts/docs.html#L3-L4
> Fix docs sidebar

- docs/learn-es6.md
1. Missing let throws, number is not defined
2. square is equal to _(number*number)_ not _(number*2 )_
> Missing let, square function actually doubles

- docs/usage/options.md
Fixes https://github.com/babel/babel/issues/4749
This option doesn't actually have any effect when using the Node API. Goal of this PR is to clarify that this is a CLI option only.
> Clarify no-babelrc docs

- docs/usage/cli.md
I had to check this out before compiling to `lib` because my `lib` already had other files I didn't want to overwrite.
> Assure --outfile doesn't overwrite other files in lib directory

- .gitmodules
- _includes/package_readme.html
- docs/plugins/transform-minify-booleans.md
Refers to #999.
I wanted the API to be consistent from #990 and for #997. `from` parameter points to the source repository (`from="babel"` is by default).
> Include docs for babili

- _sass/pages/_repl.scss
- repl.html
- scripts/repl.js
Solves #825 
Makes resizable editor columns (10px transparent zone).
Size set in percent, panel minimum size - 20%.
> Make REPL editors resizable by width.

- _includes/package_readme.html
As pointed out in #1010.
`strip_html` was not a good idea since some snippets (JSX for example) contains HTML.
For now, only `<br />` will be removed from snippets.
> Fix package_readme.html include

- docs/core-packages/types.md
- docs/internals/types.md
PR related to #1006.
Babel-handbook section for `babel-types` points to the package README on Github ([see](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md#babel-types)).
Since #990, I guess more `internal` package will be published on the website. I suggest the `/docs/internals/` path.
> Create Babel-types page

- docs/plugins/minify-constant-folding.md
- docs/plugins/minify-dead-code-elimination.md
- docs/plugins/minify-empty-function.md
- docs/plugins/minify-flip-comparisons.md
- docs/plugins/minify-guarded-expressions.md
- docs/plugins/minify-infinity.md
- docs/plugins/minify-mangle-names.md
- docs/plugins/minify-numeric-literals.md
- docs/plugins/minify-replace.md
- docs/plugins/minify-simplify.md
- docs/plugins/minify-type-constructors.md
- docs/plugins/transform-inline-consecutive-adds.md
- docs/plugins/transform-inline-environment-variables.md
- docs/plugins/transform-member-expression-literals.md
- docs/plugins/transform-merge-sibling-variables.md
- docs/plugins/transform-minify-booleans.md
- docs/plugins/transform-node-env-inline.md
- docs/plugins/transform-property-literals.md
- docs/plugins/transform-regexp-constructors.md
- docs/plugins/transform-remove-console.md
- docs/plugins/transform-remove-debugger.md
- docs/plugins/transform-simplify-comparison-operators.md
- docs/plugins/transform-undefined-to-void.md
Hey @hzoo - Ready for a review - Updated the babili plugin documentation on the github pages website to eliminate duplication of documentation. Also added plugin files which weren't there.
Let me know if you need anything re-named, or changed.
Thanks,
Geordi
> Update babel.github.io babili plugin docs

- docs/editors.md
Babel ES6/ES7 extension originally referenced is outdated and does not correctly scope many JS contexts.
> Update VS Code babel extension

- _posts/2016-12-07-the-state-of-babel.md
Shortcuts in the main page doesn't work. This is not perfect because links are hardcoded (it will break if the domain change ) but it should work
> Fix Broken links

- _config.yml
Ref #1046 
It appears that [jemoji](https://github.com/jekyll/jemoji) is one of the [very few plugins](https://pages.github.com/versions/) supported by github pages 💥
Tested it by adding the changelog page:
> add support for GitHub emojis

- docs/plugins.md
`remove-console`, `remove-debugger`, `simplify-comparison-operators`, `undefined-to-void` were showing up twice on the list of plugins.
> remove duplicate transforms

- scripts/docs.js
Currently, because we have two headings with the text "Experimental" we get:
This concats the parent's hash to fix this issue:
And, the headings linkable:
./docs/plugins/#transform-plugins-experimental
./docs/plugins/#syntax-plugins-experimental
> Fix bug with duplicate heading hashes

- _data/navigation.yml
- _includes/header.html
- _sass/components/_navbar.scss
Fixes #1060
Given #1042 this is a quick fix.
Navigation data has a bit changed:
* actual item
* subnav
* name (optionnaly set a group name)
* items
* actual item
> Grouping elements in navbar

- _layouts/page.html
Since #1069 we assume all the edit links are pointing to some package.
I added a condition to ensure this.
> Fix edit page link

- _posts/2015-10-31-setting-up-babel-6.md
- docs/setup.md
- index.html
Has the same behavior as latest without options so might as well if we are going to recommend later.
> reference preset-env instead of latest

- docs/usage/babelrc.md
POSIX shells won't pass variables as environment variables unless they are explicitly exported, with the exception of the `$PATH` variable.
> babelrc.md: export env variables in example

- _posts/2015-07-07-react-on-es6-plus.md
`var`s are only supposed to be in ES5 examples, I think 😄
> Use const instead of var in ES6+ example

- index.md
I found a malformed <p> tag in the index page, on the "ES2015 and beyond" section. This is just a simple pull request to fix it :)
> Fix malformed <p> tag in index

- _data/navigation.yml
It appears that URLs are treated differently if they contain a trailing slash. `/docs/core-packages/babel-register` works, `/docs/core-packages/babel-register/` results in a 404.
> Fix 404 for babel-register menu item

- _includes/header.html
People that don't have experience with Discourse would be confused by the current link. People don't really care that Babel is using Discourse for the forum, just that it actually **is** a forum. Discourse is just an implementation detail, it could just as easily be SMF or phpBB or something else.
As examples from elsewhere in life, you'd say "send me an email" not "send me a Gmail", and "give me a phone call" not "contact me via the AT&T network", so this link should read "Forum" or "Discuss" rather than "Discourse".
@hzoo
> Rename "Discourse" link to "Forum"

- docs/usage/babelrc.md
"Serializable JSON" doesn't make much sense to me: JSON is a serialized format, while this sentence sounded like you could serialize JSON further. Perhaps, this wording would be better?
> Reword "serializable JSON"

- scripts/repl.js
If cookies are disabled, merely accessing `window.localStorage`
throws an error. So the REPL would fail to load when creating its
StorageService instance. This change moves the `localStorage`
property access inside the try-catch blocks, so the REPL can
still load even if `localStorage` is unavailable.
| Before | After |
|---|---|
| ![Before](http://i.imgur.com/WlnkbMr.png) | ![After](http://i.imgur.com/QLNJa4T.png) |
> Make the REPL work when cookies are blocked.

- _data/users.yml
The user with this url "https://github.com/kobezzza/Snakeskin/" is not accessible, Github returns 404
> The link to a user webpage is 404

- _posts/2015-07-07-react-on-es6-plus.md
This creates syntax error and it's against current spec.
> Trailing comma after object rest assignment in blog (React on ES6+)

- _posts/2017-03-01-upgrade-to-babel-7.md
`legacy-decorators` has been moved into the `transform-decorators` in https://github.com/babel/babel/pull/5290:
the source code has been moved, tests structure has been modified (like in other packages), `chai` -> `assert`
/cc @hzoo
> Fix PR number (legacy-decorators)

- docs/plugins.md
I guess the link for the const plugin should point to the transform plugin, as with the others links around it ... this fixes this.
> fix link to const plugin

- docs/usage/cli.md
Came up in https://github.com/babel/babel/issues/1965.  I don't have knowledge on strictly what conditions `NODE_NO_READLINE=1` or `--always-readline` are required.  They have been important on macosx at varying times in the past.
> usage with rlwrap

- docs/plugins.md
Since preset-latest now has this install warning on npm:
> 💥  preset-latest accomplishes the same task as babel-preset-env. 🙏  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env 👌. And let us know how you're liking Babel at @babeljs on 🐦
This switches to preset-env being recommended instead. I also moved preset-flow down to the bottom so preset-latest was next to the other yearly presets in the list.
> Recommend preset-env

- _data/navigation.yml
Fixes #1228 
https://babeljs.io/docs/usage/api/ and https://babeljs.io/docs/core-packages/ are showing the same README.
> Add API usage page in menu

- _sass/pages/_repl.scss
- repl.html
- scripts/repl.js
With evaluate:
With huge output (scrollable):
`debug` option is appearing only when env preset was selected (like built-ins).
> Add debug option if env preset selected.

- _includes/scripts.html
- index.md
- scripts/index.js
Hey guys :wave:
Tracing site a bit I found a place for opportunity.
Using [pwmetrics](https://github.com/paulirish/pwmetrics) were made some measurements and noticed that Time to Interactive happens too late after First Meaningful Paint.
Also, I traced stuff on a Mi Redmi 3 phone with 3G network throttling.
Here the trace - https://chromedevtools.github.io/timeline-viewer/?loadTimelineFromURL=drive://0B0c67TI7mLzEN0VMYkJhdW1UZjQ
`FCP` ~ `3,1sec`
`TTI` ~ `6,8sec`
Not nice :(
----
~After digging in, it turned out that there were no `defer` attributes for scripts, moreover no minified css and uglified js where used.
For minifying assets [jekyll-assets](https://github.com/jekyll/jekyll-assets) was used (it was playing with magic).~
So after adding defer
`FCP` ~ `3sec` (saved 100ms)
`TTI` ~ …
> Performance improvements

- docs/plugins/transform-regenerator.md
- docs/usage/polyfill.md
old link is being deprecated: https://github.com/facebook/regenerator/blob/master/runtime.js
closes https://github.com/babel/babel/issues/5692.
> update links for regenerator-runtime/runtime

- docs/plugins/preset-es2015.md
- docs/plugins/preset-es2016.md
- docs/plugins/preset-es2017.md
The `preset-es*` pages still point to `preset-latest` in a banner at the top of the page, even though it has been deprecated. This PR changes that to `preset-env`.
> Switch links to preset-env from deprecated preset-latest

- repl.html
- scripts/repl.js
This gives a reduction in url size of up to 60% while maintaining backwards compatibility (`code` will be accepted uncompressed, but the next-generated URL will use `code_lz`).
Some results:
|           | URL Before | URL After | Query Before | Query After | URL Comp. % | Query Comp. % |
|-----------|------------|-----------|--------------|-------------|-------------|---------------|
| [Example 1 (Kent Dodds ES6 workshop)](https://babeljs.io/repl/#?evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&experimental=true&loose=false&spec=false&playground=true&code=%2F%2F%20default%20parameters%0Afunction%20sum(x%2C%20y%20%3D%2012)%20%7B%0A%20%20%2F%2F%20y%20is%2012%20if%20not%20passed%20(or%20passed%20as%20undefined)%0A%20%20return%20x%20%2B%20y%0A%7D%0Aconsole.log(%0A%20%20'default% …
> Compress code in repl querystring with LZString

- _includes/tools/jest/usage.md
Replace deprecated scriptPreprocessor with transform config option.
```
Deprecation Warning:
Option "scriptPreprocessor" was replaced by "transform", which support multiple preprocessors.
Jest now treats your current configuration as:
{
"transform": {".*": "<rootDir>/node_modules/babel-jest"}
}
Please update your configuration.
Configuration Documentation:
https://facebook.github.io/jest/docs/configuration.html
```
> Jest usage update: Deprecated scriptPreprocessor fix

- _sass/components/_sidebar.scss
The sidebar contains more items then can be displayed on some pages, the sidebar cannot be scrolled.
I've added a bottom-position and overflow:auto to the sidebar when it's fixed.
The sidebar is now scrollable.
[![demo of the feature](http://img.youtube.com/vi/GvyDnd50I1U/0.jpg)](http://www.youtube.com/watch?v=GvyDnd50I1U "Demo of feature")
> Sidebar to overflow when fixed

- php.html
See https://github.com/Rich-Harris/packd/issues/10
I didn't change the 7 REPL since https://github.com/babel/babel.github.io/pull/1280 will remove the dependencies from `packd.now.sh` .
> Use CDN in REPL

- 7.html
This is temporary since https://github.com/babel/babel.github.io/pull/1280 will remove the scripts.
See https://github.com/Rich-Harris/packd/issues/10
> Use bundle.run in 7 REPL

- repl.html
I think this is breaking the REPL on Netlify. If we do want to redirect people hitting `/repl.html`, we can configure a Netlify redirect in `_redirects` for that (which is a true server-side redirect).
> Remove redirect_from in REPL

- _posts/2017-07-02-gsoc-peey-1.md
- _posts/2017-08-11-gsoc-peey-1.md
From medium: https://medium.com/@peey/personal-experiences-at-babel-1-a-pr-with-unusually-high-number-of-reviews-5cb49ee71897
cc @hzoo
> Add the gsoc blog post

- 7.html
- _config.yml
- _redirects
- scripts/7.js
This PR adds a new "circleci_build" parameter to the Babel v7 REPL page. When provided, this is treated as a CircleCI build number and `babel-standalone` is loaded from the CircleCI build artifacts rather than from unpkg. The idea is that we can have a bot that runs as a CircleCI webhook and automatically comments on all Babel PRs with a link to the REPL to allow easy testing of changes.
The new parameter is passed like this:
```
/repl/?circleci_build=123
```
The `lazyLoadScript` function added in this PR is a generalised version of the `hasBabiliLoaded` function in the current `repl.js`.
Depends on https://github.com/babel/babel/pull/6029 ("Move babel-standalone into main Babel repo"). We can't test this with real Babel PRs until the other PR lands. 
cc @hzoo
> Allow loading babel-standalone from CircleCI to enable easy testing of PRs

- _config.yml
If you build the new REPL, the Jekyll build hangs as it tries to build all ~20,000 files in its node_modules directory.
This was the reason @bvaughn was having difficulty with Jekyll. It took a while to track down - I only figured it out after watching exactly what the Ruby process was doing and noticing that it was reading a large number of Markdown files from `node_modules`:
I'm working on adding the new REPL to the site and integrating it into the Jekyll build, but in the meantime this will unblock anyone that wants to try the new REPL locally *and* still be able to build the site. 😛
> Ignore js/repl/node_modules in Jekyll build

- js/repl/Repl.js
- js/repl/compile.js
- js/repl/scopedEval.js
Maybe we should consider evaling code within a web worker to be safer, but this PR is at least a step in a better direction. We now mask globals to prevent evaled code from accidentally interacting with the Babel website or the REPL.
After this change the following code snippets will no longer mess up the REPL:
```js
document.body.innerHTML = ''
```
```jsx
ReactDOM.render(
<div/>,
document.getElementById('root')
);
```
Potentially resolves #1329
> Mask global variables before eval-ing REPL code

- js/repl/Repl.js
- js/repl/compile.js
- js/repl/scopedEval.js
- js/repl/types.js
This PR adds a couple of improvements to the new REPL:
* `eval` is now done within an `iframe` rather than a context-less `new Function` so that compiled code can access `window` without potentially clobbering the REPL itself.
* Inline source maps are passed to `eval` so errors will map to pre-compiled code. This works fine on Safari and Firefox but I can't get it working on Chrome. I'm aware of some issues with this (see [459499](https://bugs.chromium.org/p/chromium/issues/detail?id=459499#c22) and some potential workarounds (see [`EvalSourceMapDevToolModuleTemplatePlugin.js`](https://github.com/webpack/webpack/blob/3f79150d6ab2ad7a614b94e55c9314adf581b07a/lib/EvalSourceMapDevToolModuleTemplatePlugin.js#L65) but I'm not having much luck.
Potential downsides:
* The inline source maps do …
> REPL attaches source maps to eval()

- js/repl/Repl.js
- js/repl/compile.js
- package.json
- yarn.lock
Since we used controlled inputs, `state` changes for their values must remain synchronous. The actual compilation can be debounced though. I think this PR seems to do the tricky? 😅  I initially expected it to be more complicated than this.
Resolves #1316
Note that I'm moving discussion of moving compilation to a worker to #1342. I think it's worth separating from debounce.
> Debounce compilation and plug-in changes

- scripts/docs.js
**Steps to reproduce:**
1. Open any Docs page. Example: https://babeljs.io/docs/plugins/
2. Scroll to page bottom.
**Expected result:**
Sidebar doesn't flickering.
**Actual result:**
Sidebar flickering.
**Before fix:**
**After fix:**
> Fix sidebar flickering when scroll reaches page bottom

- js/repl/CodeMirrorPanel.js
- js/repl/Repl.js
- js/repl/ReplOptions.js
- js/repl/Worker.js
- js/repl/WorkerApi.js
- js/repl/WorkerUtils.js
- js/repl/compile.js
- js/repl/loadBabel.js
- js/repl/replUtils.js
- js/repl/types.js
- package.json
- webpack.config.js
- yarn.lock
Resolves #1342
Here's a super-unscientific example of processing a [large UMD file](https://unpkg.com/react-virtualized@9.9.0/dist/umd/react-virtualized.js) while scrolling around the page.
> Move Babel to web-worker

- js/repl/UriUtils.js
The underlying issue was that "Try" links don't use lz compression. I wrote the REPL expecting that the `code` search param would always be compressed as `code_lz`. I've updated the REPL now to accept `code` too- and to defer to `code_lz` when it's present.
Resolves #1349
> Fixed "Try" links to REPL

- js/repl/AccordionTab.js
- js/repl/ReplOptions.js
- js/repl/styles.js
Resolves #1347 
**TODO**:
* Lift accordion expanded state up so that collapsing/expanding the sidebar doesn't reset which accordions are expanded.
* Don't let `textarea` in "Env" section cause the nav size to change when opened.
> Refactored sidebar to use accordions

- _posts/2017-03-01-upgrade-to-babel-7-for-tool-authors.md
This enhances the blog post for tool authors to better show what changed and how a possible fix might look like.
I changed the Overall heading from `Babylon` to `AST changes` as otherwise it might sound like you are only affected when you are using babylon, but actually every babel-plugin is affected.
> WIP: Better document breaking changes for the AST

- js/repl/loadBabel.js
REPL should load `babel.min.js` rather than `babel.js`. This is what the old REPL did: https://github.com/babel/website/blob/master/repl-old.html#L9
> Load minified Babel in REPL when using release builds

- scripts/download-readmes.js
Until we get [6.x/7.x doc switching](https://github.com/babel/website/issues/1261) (or just fully switch to 7.x), this prevents site build from breaking due to lack of `babel-preset-latest` now that master is `7.0`.
(Sidenote, since `babel-preset-latest` now resides in `babel-archive`, we should decide how to handle this later).
> Download READMEs from babel@6.x for now

- js/repl/Repl.js
- js/repl/WorkerApi.js
- js/repl/loadPlugin.js
- js/repl/loadScript.js
- js/repl/scopedEval.js
- js/repl/types.js
This is done so that helper methods like regeneratorRuntime are accessible as globals on the iframe's `contentWindow`.
While adding this feature, I discovered that Firefox behaves differently than Chrome and Safari when a new iframe is appended- it (asynchronously) loads "about:blank" and clobbers any (synchronously) appended script tags. So we also check the `iframe.contentDocument.readyState` before appending.
This has been tested on the following:
Browser | OS
:---|:---
Chrome | OSX
Firefox | OSX
Safari | OSX
Brave | Android
Safari | iOS
Resolves #1350
> Load runtime polyfill into scoped-eval iframe

- _posts/2017-09-05-planning-for-7.0.md
Title: "What's in 7.0"
> If you didn't know already, we're planning on releasing a 7.0 version soon! I'd like to go over some notable changes and a few things we are still working out!
Should mention our WIP upgrade guide, project sustainability?
Also check out https://github.com/babel/babel.github.io/pull/1146
> Planning for 7.0

- js/repl/compile.js
Resolves #1369 
I believe this change resolves the differences in behavior between classic and legacy Repl with regard to async functions.
> Removed transform-regenerator plugin from hard-coded transform options

- .babelrc
- js/repl/AccordionTab.js
- js/repl/CodeMirror.js
- js/repl/CodeMirrorPanel.js
- js/repl/ErrorBoundary.js
- js/repl/PresetLoadingAnimation.js
- js/repl/Repl.js
- js/repl/ReplOptions.js
- js/repl/Svg.js
- package.json
- yarn.lock
This is a fairly straightforward conversion so I thought I'd give it a shot. emotion uses Babel to optimize for performance and developer experience so I thought it would be fitting to use it on the Babel repl.
repl.js size
master - **105kB**
<details>
</details>
---
emotion - **89kB**
<details>
</details>
---
Bonus: I wanted to see how source maps behaved when using a glamor like api. Only works in development.
Pretty awesome!
Thanks for taking a look!
> Migrate REPL css-in-js library from glamor to emotion.

- js/repl/AccordionTab.js
Double clicking the chevron cause text to be selected. I figured there's no good reason for this to be selectable anyway.
> Make area non-user-selectable

- _includes/tools/babel_cli/install.md
- docs/usage/cli.md
This removes all global `babel` usage, instead using the locally installed node module with `npx`. Closes babel/babel#4066.
> Update cli usage

- _includes/tools/mocha/usage.md
https://github.com/mochajs/mocha/wiki/compilers-deprecation
Mocha will deprecate `--compiler` syntax
> Update mocha `--compiler` deprecation syntax

- js/repl/PluginConfig.js
- js/repl/ReplOptions.js
- js/repl/replUtils.js
- js/repl/types.js
The issue presented in #1365 asks to delete the package key from `presetPluginConfigs`
@Daniel15 
I'm not sure if that was the exact task to be done or if there is something more here. Checking `js/repl/ReplOptions.js`, it looks like the presetPluginConfig needs the package key in order for http://babeljs.io/repl/# page to handle its state.
Currently I just deleted the hardcoded package key and generated after the object is created, so that the `package` key is still used in `ReplOptions.js`
Happy to help on the issue in any way I can :)
> generate package in presetPluginConfigs (fixes #1365)

- _layouts/page.html
Since we changed the repo name the edit links doesn't work anymore.
> Fix edit links

- js/repl/loadBabel.js
Fixes using the REPL with the latest v7 build, since the 7.0 branch is now master.
Right now, http://babeljs.io/repl/build/7.0 is mapping to circle's last known `7.0` branch build ([v7.0.0-alpha.20](https://circleci.com/gh/babel/babel/tree/7.0)).
Now:
https://deploy-preview-1426--babel.netlify.com/repl/build/7.0
> Map /build/7.0 to master in REPL

- faq.md
As far as I understand [babel-preset-es2015 is deprecated](http://babeljs.io/env), so we should not mention installing it anywhere in the docs. Please let me know if I'm misunderstanding :)
> Update FAQ, babel-preset-es2015 → babel-preset-env

- docs/plugins.md
It doesn't work properly, so remove mention of this plugin.
For example, it results in the following error:
```
ERROR in ./demo/react/main.jsx
Module build failed: BabelLoaderError: /home/ubuntu/workspace/demo/react/main.jsx: Reference to undeclared variable "props"
11 | class Demo extends Component { 
12 |     constructor(props) {
> 13 |         super(props)
|               ^
14 |         this.state = {
```
> Remove mention of babel-plugin-undeclared-variables-check

- _includes/member.html
Protocol-relative URLs are an antipattern. https://github.com/konklone/cdns-to-https#background
This patch also avoids a redirect from e.g. www.twitter.com → twitter.com.
> Use HTTPS for member links to Twitter/GitHub

- _posts/2016-12-07-the-state-of-babel.md
- docs/plugins.md
Fixes permalinks broken by [move of 2016 to own folder](https://github.com/babel/notes/commit/8c7bbafec22c4f577c2794569df096bc04cd4451).
Found by chance while investigating a bug on preset ordering 😄 
https://babeljs.io/docs/plugins/#plugin-preset-ordering
> For more information, see [notes on potential traversal API changes](https://github.com/babel/notes/blob/master/2016-08/august-01.md#potential-api-changes-for-traversal).
> Fixes permalinks broken by move of 2016 to own folder

- js/repl/PluginConfig.js
- js/repl/Repl.js
- js/repl/ReplOptions.js
- js/repl/Worker.js
- js/repl/WorkerApi.js
- js/repl/loadBabel.js
- js/repl/replUtils.js
- js/repl/types.js
Supersedes/Closes https://github.com/babel/website/pull/1360.
Only real difference is presets marked with `isPreLoaded` inside `presetPluginConfigs` are now  checked against `availablePresets` from `@babel/standalone` to prevent the invalid/missing preset errors (i.e. trying to load Flow/TypeScript preset with 6.x)
Examples:
[6.26.0](https://deploy-preview-1462--babel.netlify.com/repl#?babili=false&browsers=&build=&builtIns=false&code_lz=PTAEAEDMBsHsHcBQA3AhgJ1ADwFygM4Au6AlgHYDmoAvKAOSSywBGGdA3EA&debug=false&circleciRepo=&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-2&targets=&version=6.26.0) (no flow/ts)
[7.0.0-alpha.15](https://deploy-preview-1462--babel.netlify.com/repl#?babili=false&browsers=&build=&builtIns=false&code_lz=PTAEAEDMBsHsHcBQA3AhgJ1ADwFygM4Au6AlgHYDmoAvKAOSS …
> Add flow and typescript presets to repl

- docs/usage/babelrc.md
The `BABEL_ENV` env variable was mistakenly written as `NODE_ENV` in the babelrc.md doc file.
> Changed NODE_ENV to BABEL_ENV in .babelrc.md

- js/repl/CircleCI.js
- js/repl/PluginConfig.js
- js/repl/Repl.js
- js/repl/UriUtils.js
- js/repl/compile.js
- js/repl/replUtils.js
- js/repl/types.js
Follow up for PR #1395
Looks like Prettier v1.7.0 broke for the browser with the error "_cosmiconfig requires at least version 4 of Node_" and v1.8.0 broke with the error "_os$2.homedir is not a function_". Version 1.6.1 was working before though, so I'm re-enabling and pinning us to that version for the time being.
Note that I'm seeing 3 Flow errors in this branch when I run `yarn flow` locally, but I also see those 3 errors on master. ☹️  Seems like this got broken at some point?
> Re-enable prettier v1.6.1

- docs/usage/polyfill.md
The previous link led to a disambiguation page on Wikipedia.
> Fix link to Wikipedia

- _posts/2017-11-03-nearing-the-7.0-release.md
progress updates
I just copied part of the stuff from the older post
- name for integrations
- peerDep on babel-core
- versioning
- scoped packages
- removing the `-es2015-` part of some transforms
- moved babylon/preset-env repos into this repo
- transform -> proposal for Stage x proposals
- deprecated es20xx presets
> 7.0 updates

- env.md
See my thread here:
https://mobile.twitter.com/dan_abramov/status/950385471846264833
Beginners see this message regardless of whether they use Babel directly. The advice on this page encourages them to always install this preset. In case of tools like Create React App this can actually break their setups (due to version incompatibility).
> Add a section explaining how to tell if you depend on deprecated presets or not

- _posts/2017-09-11-zero-config-with-babel-macros.md
Because people think that `babel-plugin-macros` === `code in strings` && `preval` === `code in strings` and that turns people off to both tools.
> change example to use preval.require

- scripts/docs.js
The current approach to create ids from `h2`'s id and `h3`'s text content has some problems.
1. Same anchor links work for only one of the website or README pages on GitHub. https://github.com/babel/babel/pull/7214#issuecomment-357510259
2. Algolia doesn't work well with the ids. It seems to index ids in HTML, which are generated by kramdown.
3. The current way of creating ids misses a `-` when `h3` starts with <code>`</code>.
https://github.com/babel/website/pull/1035 tried to fix an issue of duplicated ids in a page by prefixing an `h3` id with its parent `h2` id. However, kramdown already solves this by suffixing ids with `-1`, `-2`, and so on. GitHub seems to do the same for markdown files. e.g., https://github.com/babel/website/blob/master/docs/plugins.md#experimental-1
Also, adding …
> Use heading ids generated by kramdown

- js/repl/loadBundle.js
If Babel is 7 and preset-env is 6, use Babel current version.
cc @existentialism
> Fix version overriding for preset-env.

- website/siteConfig.js
- website/static/css/code-blocks.css
- website/static/css/highlight-js-theme.css
This adds the styling of code block on the old website back onto the new one. Due to a glitch on Docusaurus, the Tomorrow theme needed to be added manually for Highlight.js
> Add styling for Code Blocks

- website/static/css/code-blocks.css
Fix #1549 
The code snippets were cut off on small screens. This is not a bug with Docusaurus, since removing the custom CSS for `.hljs` at https://github.com/babel/website/blob/3ec8a278bb9416bd1ebf604d6b9fc96fc1f77346/website/static/css/code-blocks.css#L2 and https://github.com/babel/website/blob/3ec8a278bb9416bd1ebf604d6b9fc96fc1f77346/website/static/css/code-blocks.css#L13 brings in a scroll bar. I believe the reason for the snippets being cut off is `.h1js::before`, which is unique to the babel website. Also, other sites like [jest](https://facebook.github.io/jest/) use Docusaurus and they automatically get scroll bars.
Because we want a custom header like thing for the snippets, we'll have to make do with wrapped text and won't be able use a scroll bar. So, just adding a way to …
> Fix snippets cut off in mobile

- README.md
Just a small thing.
You need to run `npm install` when you pull the repo for the first time.
It throws an error otherwise since in the MAKE file you're calling `download-readmes.js`
> Update setup doc

- docs/tools/gulp/install.md
`babel-core` is now listed as a peer dependency in `gulp-babel`, therefore it needs to be explicitly installed.
Following the issue referenced here: https://github.com/babel/gulp-babel/issues/124
> Add babel-core to the gulp-babel install

- website/static/css/babel.css
Fixes #1536 
This applies to the docs sidebar only. Blog sidebar stays as before.
> Make main docs sidebar fixed

- docs/babelrc.md
Instead of, 'You can alternatively choose', you could use, 'Alternatively, you can choose'.
> Sentence reordering

- js/repl/ExternalPlugins.js
The value is still working for both `keywords` and `computedKeywords`, but I want to put the handling of special keywords like babel plugins in there alone and remove the messing with `keywords` in the index.
cc @xtuc
> external repl plugin search: use computedKeywords

- js/repl/compile.js
The repl currently is broken because of https://github.com/babel/babel/pull/7734. This PR should fix it.
> Use legacy decorators

- docs/v7-migration.md
* Fix a typo or two.
* Add a few commas
* Make the text in a few lines more readable.
> Improve readability in a few lines for babel 7 migration doc.

- scripts/download-readmes.js
Don't know how I missed this before. My "comments" were showing up in pages like [this](https://new.babeljs.io/docs/en/next/babel-preset-stage-3.html)
> Hide markdown comment from pages

- website/pages/en/team.js
Currently, on the [team page](https://babeljs.io/team) when clicking 'Edit this page', it'll link to a not found page on Github. This PR fixes that.
> Fix broken link on team page

- docs/v7-migration.md
Since support for Node.js 4 and 5 have been dropped, migration documentation should reflect that. This will prevent people digging into errors such as the `@babel/cli` running on Node.js 4 (I'm mentioning this here for search-ability purposes):
```sh
...node_modules/@babel/cli/lib/babel/dir.js:172
function sequentialHandle(filenames, index = 0) {
^
SyntaxError: Unexpected token =
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/home/travis/build/amercier/npm-package-skeleton/node_modules/@babel/cli/lib/babel/index.js:54:35)
at …
```
> Add Node.js 4 and 5 dropped support in migration docs

- docs/index.md
- docs/usage.md
Removed the "last 2 versions" example in favor of an explicit list of browsers. And some minor changes like moving the use cases paragraph to the index doc.
> Usage guide change: replace browsers example

- js/repl/AccordionTab.js
- js/repl/ReplOptions.js
Small tweaks:
* Reduced some caret density by moving the section expanded status to the left of the label
* Tweaked style of the source type dropdown
> Tweak repl sidebar design

- docs/core.md
- website/static/css/babel.css
The long headings in https://babeljs.io/docs/en/next/babel-core.html don't work well with the on-page navigation.
I'm moving them in blockquotes (not ideal) as a quick fix: https://deploy-preview-1694--babel.netlify.com/docs/en/next/babel-core.html
> Fix babel-core headings

- docs/plugin-transform-react-constant-elements.md
Should be `style` instead of `width` :) in the babel-plugin-transform-react-constant-elements example for mutable properties
> Fix documentation example for mutable properties

- docs/parser.md
align to middle looks so strange.
> docs: styling babel-parser

- website/blog/2018-06-25-on-consuming-and-publishing-es6+-packages.md
- website/blog/2018-06-26-on-consuming-and-publishing-es2015+-packages.md
Rendered: https://deploy-preview-1705--babel.netlify.com/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages
Purpose: bring up a discussion on how library authors should publish ES6+ and ESM as well as how this is dealt on the consumer side (whether or not you need to compile deps)
> Publishing ES6+ Post 

- docs/core.md
Looks like there are a number of whitespace changes (my editor removes trailing whitespace) but there should only be 1 line of documentation edits.
> Adds documentation for the @babel/core cwd option

- website/versioned_docs/version-6.x/core-packages.md
- website/versioned_docs/version-6.x/plugins.md
- website/versioned_docs/version-6.x/preset-env.md
.md links for renamed plugins in https://babeljs.io/docs/en/plugins#transform-plugins are not working because of https://github.com/facebook/Docusaurus/issues/845. Until that is fixed we can switch to relative links.
> Fix v6 links for renamed plugins

- website/blog/2018-07-16-announcing-babels-new-partnership-with-trivago.md
> https://deploy-preview-1727--babel.netlify.com/blog/2018/07/16/announcing-babels-new-partnership-with-trivago
> Add trivago post

- js/repl/compile.js
Not the best but then it will run. The `onPresetBuild` option seems to be for debug info.
The one in https://github.com/yavorsky/babel-preset-env-standalone/blob/6287394270fdfbc8241f3816748cfffc704a3cc6/src/index.js#L189-L214 added a bunch of extra stuff to v6 that isn't in v7 (the one in the monorepo).
> so that preset-env will run on v7

- website/blog/2018-07-27-removing-babels-stage-presets.md
Gotta set a deadline (tomorrow?) otherwise I'll spend forever on this!
The purpose of this is to explain the decision to remove the Stage presets but also to give context into why and the history of not just TC39/Babel but the community and it's relationship with the process if that makes sense and where we are at today. Ideally we'd have some more takeaways regarding getting involved in the project.
Also this makes me think maybe I should rename the title.. (prepare for backlash)
> Blog: Removing Babel's Stage Presets

- docs/plugin-transform-runtime.md
- docs/runtime.md
For https://github.com/babel/babel/pull/8266
Preview:
- https://deploy-preview-1714--babel.netlify.com/docs/en/next/babel-runtime
- https://deploy-preview-1714--babel.netlify.com/docs/en/next/babel-plugin-transform-runtime
> runtime docs

- js/repl/ReplOptions.js
- website/pages/en/repl.js
- website/static/css/hide-footer.css
Hello.  I removed big footer on the REPL and fixed cutting off babel version tab in the bottom of left panel.
> Hide big footer in REPL

- docs/template.md
There was a parenthesis missing in the template doc when calling the `template` function.
> Add missing parenthesis to template doc

- README.md
Doesn't look like there's a Makefile anymore, so this line is out of date (probably?)
> Remove outdated reference to Makefile from readme

- website/static/css/code-blocks.css
Noticed all code block titles said `CSS`.
I renamed all class names matching `.hljs.*`to `.hljs.language-*` in `code-blocks.css`, since that matches the class names hljs produces.
> Fix Code Block Titles

- website/core/Footer.js
- website/pages/en/index.js
- website/siteConfig.js
Moved `docUrl`, `pageUrl`, and `DEFAULT_LANGUAGE` to `siteConfig`.
* Fix invalid footer links. In non-localized pages, `props.language` is an empty string, rather than `undefined`, causing default arguments not to be applied.
Closes #1715.
> Move `docUrl`, `pageUrl`, and `DEFAULT_LANGUAGE` to siteConfig

- js/repl/ExternalPluginsSearchBox.js
My browser otherwise interprets this input as a contacts form (it would be better as type=search and in a form, but didn't want to mess with the styling now)
(this is how it used to look)
> feat(repl): avoid browser autocompletion in plugin search

- js/repl/ExternalPluginsModal.js
The plugins are not only those that have the keyword; but also those that start with it. 
see https://github.com/algolia/npm-search/commit/a8a52650cc857e4cfb558538fa5e86b743dc5d86 to the change that did this, 
I already did https://github.com/babel/website/pull/1623 and https://github.com/babel/website/pull/1622, but it seems like that was reverted?
cc @xtuc
> fix(repl): search on computed plugins

- docs/v7-migration-api.md
Changes 'have been remove' to 'have been removed'
> Fix spelling of removed

- docs/v7-migration.md
The example appears to show addition of flow / typescript, not removal.
Slight rewording of the paragraphs in the "Separate of React and Flow presets" section to be more succinct.
> Example presets: s/remove/add/ + minor rewording

- docs/v7-migration.md
I found an easy mistake in "[Upgrade to Babel 7](https://babeljs.io/docs/en/v7-migration#only-helpers)".
It's a trivial fix, so please check it when you have time. 😉
> Trim unnecessary backquote in code example

- docs/cli.md
With Babel 7 the `--ignore` flag needs proper patterns to match files. This updates the documentation to reflect that change.
There is some more information in this issue https://github.com/babel/babel/issues/8631.
> Update ignore files section

- website/blog/2018-08-27-7.0.0.md
Makes the "P" in "WordPress" capital and changes "WordPress" to "WordPress.com", which is a more precise description of the Calypso frontend: it's part of the commercial service rather than the open source WordPress software itself.
> Fix "WordPress" spelling in the 7.0.0 release post

- docs/preset-env.md
> `targets.browser` => `targets.browsers`

- website/blog/2018-09-13-decorators.md
- website/blog/2018-09-17-decorators.md
I talked with Henry some time ago about this post; it would be nice to publish it alongside with the 7.1.0 release, which adds support for decorators.
Rendered: https://deploy-preview-1825--babel.netlify.com/blog/2018/09/17/decorators
> Article about decorators

- website/blog/2018-09-17-decorators.md
As mentioned in https://github.com/babel/website/pull/1825#issuecomment-422020573, we were thinking about a tool to make it easier to upgrade to the new decorators proposal.
https://github.com/nicolo-ribaudo/legacy-decorators-migration-utility :smile:
> Update decorators article

- website/data/videos.yml
Closes #1767
I've tried to dig all the info from the video links. Please do revise.
> Add more Babel talks

- _redirects
These pages still resolve, due to the way Docusaurus works:
https://babeljs.io/docs/en/babel-plugin-transform-class-properties
https://babeljs.io/docs/en/babel-plugin-transform-decorators
https://babeljs.io/docs/en/babel-plugin-transform-do-expressions
https://babeljs.io/docs/en/babel-plugin-transform-export-extensions
https://babeljs.io/docs/en/babel-plugin-transform-object-rest-spread
Let's redirect them to their new equivalents for now.
I'll follow this up with adding a note that these were previously named `transform-` to help those upgrading.
> Add redirects for some plugins that were renamed from 6->7

- docs/runtime.md
Change ```class A {}``` into ```class Circle {}```
> Fix Typo in Code Example

- docs/plugin-proposal-decorators.md
The `decoratorsBeforeExport` option is actually required, so I think the mention of a default is out-of-date - I removed it. I also moved the `false` example before the `true` version so it's easier to see when reading this for the first time that this option only applies to exports and doesn't make a difference otherwise.
> Correction in plugin-proposal-decorators.md

- package.json
Hey, folks, I've noticed that the js files under `pages` weren't being linted. I've made this change and now it works for me. Please check if this is useful for anyone else.
> Fix linting for page files

- js/repl/CodeMirrorPanel.js
Due to a CSS reset (I can't quite track down where it's coming from), `pre` tags aren't automatically styled as monospaced.  This causes the error and info panel to not be monospaced, which is especially annoying since the caret doesn't line up properly for parse errors:
Before:
After:
> Fix error and info panels to be monospaced in the REPL

- docs/preset-env.md
- website/versioned_docs/version-7.0.0/preset-env.md
- website/versioned_docs/version-7.1.0/preset-env.md
- Fixed the self link for the `ignoreBrowserslistConfig` option.
- Add a link to `babel-preset-latest` for where it's mentioned
> Fix links in preset-env

- docs/caveats.md
- website/versioned_docs/version-7.0.0/caveats.md
As mentioned on the upgrade guide:
> Some of the plugins had `-es3-` or `-es2015-` in the names, but these were unnecessary
https://babeljs.io/docs/en/v7-migration#remove-the-year-from-package-names-blog-2017-12-27-nearing-the-70-releasehtml-renames-drop-the-year-from-the-plugin-name
> docs(caveats): update IE transform classes plugin

- docs/options.md
I copy notices while i was copy pasting the code that it was declared two times in the scope. 
Now the code is `copy-past` ready :smile:
> Fix name conflict

- docs/preset-env.md
Since publishing [@babel/preset-env@7.0.0-rc.2](https://github.com/babel/babel/blob/v7.0.0-rc.2/packages/babel-preset-env/data/shipped-proposals.js#L4-L8), `optional-catch-binding` was included by default due to `stage-4`, and `es7.array.flat-map` was shipped by browser. The documentation is out of date.
> docs: fix preset-env options misleading

- docs/options.md
- website/versioned_docs/version-7.0.0/options.md
- website/versioned_docs/version-7.1.0/options.md
Fixes #1890
I also verified babel sources at 7.0.0 to fix that version of the doc.
> Fix documentation of sourceFileName option, fixes #1890

- docs/preset-env.md
This bit me while upgrading to babel 7 w/ present-env.
It says the default is commonjs, however that's not true. When I turn debug on and I don't specify a modules value it says it defaults to auto.
This adds auto as an option and denotes it being the default value.
> Update new default value

- docs/preset-env.md
- website/versioned_docs/version-7.0.0/preset-env.md
- website/versioned_docs/version-7.1.0/preset-env.md
This syncs up all the 7.x preset-env docs, since nothing changed between 7 -> 7.1, it makes more sense for those docs to fallback properly.
Also included the fix from https://github.com/babel/website/pull/1888 (thanks @monkindey!)
Closes https://github.com/babel/website/pull/1888.
Closes https://github.com/babel/website/issues/1886.
> Clean up preset-env versioned docs

- docs/node.md
- website/versioned_docs/version-7.1.0/node.md
- website/versioned_docs/version-7.1.0/options.md
The `--config-file` and `--env-name` flags were missing from the `@babel/node` docs pages so I've added them here.
Descriptions taken from the [PR that added them](https://github.com/babel/babel/pull/8010/files).
Doesn't look like any other flags have been added since then either. 👌 
I also updated the 7.1 docs for `options.md`. I recently made a PR that called this out but didn't realise there were versioned docs as well, so I had only updated next. (#1833). 
Give me a yell if that's not right.
Thanks!
> Updates babel/node docs to include missing flags

- website/blog/2018-12-03-7.2.0.md
Depends on https://github.com/babel/babel/pull/8289 (and https://github.com/babel/babel/pull/9115 for the repl demo to work, but it can be merged later).
> Add blog post for v7.2.0

- docs/cli.md
I was having trouble trying to follow the docs examples here:
https://babeljs.io/docs/en/babel-cli#using-plugins
https://babeljs.io/docs/en/babel-cli#using-presets
I couldn't get things to work correctly until I started specifying plugins and presets like `@babel/preset-env` instead of just `env`.
So, I'm guessing the recommended way to pass these cli args changed at some point and the docs weren't updated?
Hopefully these examples are a) correct, and b) will help someone else out. Let me know if I'm just a noob and am misunderstanding something basic.  Thanks!
> update cli examples for specifying plugins & presets

- docs/env.md
Docs tells the user to go to `babeljs.io/env` but does not provide a clickable link.
Note: `https://babeljs.io/env` actually redirects to `https://babeljs.io/docs/en/env/`, but I believe it's the expected behavior.
> Add link to `babeljs.io/env` reference

- docs/options.md
- website/versioned_docs/version-7.0.0/options.md
- website/versioned_docs/version-7.1.0/options.md
* Fix "specificed" typo in...
* babelrc docs options.md
* babelrc docs for version 7.1
* babelrc docs for version 7.0
> Fix "specificed" typo in babelrc docs

- docs/v7-migration-api.md
- website/versioned_docs/version-7.0.0/v7-migration-api.md
Linked PR states that `babel-plugin-module-resolver@3` should be used, not `@babel/plugin-module-resolver` which haven't been released yet.
> Fix babel-plugin-module-resolver info in v7 migration api notes

- docs/parser.md
- "comparison" instead of "comparsion"
- "ambiguous" instead of "ambigous"
> Typo fix in doc

- js/repl/replUtils.js
https://github.com/babel/website/pull/1915 broke the repl for many users (both on GitHub and Twitter): if someone always used the default repl, they have `version: 6.26.0` (or older) saved in their storage. Explicit version (https://babeljs.io/repl/version/7.2.0 or https://babeljs.io/repl/#?version=7.2.0) still work. If you want to debug this PR, don't trust the version shown in the sidebar since it is wrong (it will be fixed by https://github.com/babel/babel/pull/9467 for new versions) but check the unpkg requests in your browser's devtools.
@existentialism is working on removing the local storage alltogether (since it just causes bugs), but this will fix the repl in the short term.
> Always load the last version unless explicitly told otherwise

- js/repl/PluginConfig.js
This broke during the repl v7 update. If you enable the `Evaluate` option you'll see an "Unexpected identifer" error from `@babel/polyfill`: that file's contents are
```js
invalid tag
```
This is because bundle.run (which we use to load `@babel/polyfill`) doesn't support version ranges like `^7.0.0`: https://bundle.run/@babel/polyfill@^7.0.0. https://bundle.run/@babel/polyfill@7 works and has the same meaning.
> Fix polyfill loading

- docs/plugin-transform-typescript.md
- website/versioned_docs/version-7.0.0/plugin-transform-typescript.md
Moves the workarounds to their own line (but still inside the `<li>` ) - it makes the section read better.
> Minor update to plugin-transform-typescript.md

- README.md
- scripts/checkdocs.js
Looks like versioning is going to be rethought in docusaurus v2. Until then I think we should keep telling contributors to apply changes to the correct version(s) depending on whether it's a typo/fix or a new version-specific feature. That way we keep the versioned docs folders clean thanks to that fallback feature (and @existentialism's awesome backport PRs before cutting new versions).
The script I wrote to help with that was stuck on 7.1.0 for some time. This was creating more problems than it was solving, and it's a process that can't really be completely automated anyway. I'm changing it here so it doesn't copy files anymore, and just reminds the contributor that there are other files in the `versioned_docs` folders with the same filename as the one they edited at `docs/`.
> Simplify checkdocs script

- docs/tools/rails/install.md
- docs/tools/rails/usage.md
- docs/tools/sprockets/install.md
- docs/tools/sprockets/usage.md
The [Setup page](https://babeljs.io/setup) had some outdated documentation about integrating babel with the sprockets library and the rails framework. The sprockets plugin it was mentioning was stuck on babel 5 with no support for custom plugins/presets. I've updated both pages to link to more modern integrations that support the latest version of babel and arbitrary plugins/presets.
> Update Setup documentation for sprockets and rails

- docs/plugin-transform-runtime.md
Was not specified for plugin-transform-runtime.md. Needed if running babel-loader from a different directory than the current working directory.
See 
https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js#L41
https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js#L130
https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-runtime/src/index.js#L9
> fix: noted absoluteRuntime option

- website/versioned_docs/version-7.0.0/plugin-transform-runtime.md
Forgot this in https://github.com/babel/website/pull/1912
> Backport transform-runtime changes to 7.0.0

- website/blog/2019-03-19-7.4.0.md
Correct the import path to the correct package as noted in the core-js docs. https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babelpolyfill
> fix(docs): update regenerator import path

- docs/plugin-transform-classes.md
- website/versioned_docs/version-7.0.0/plugin-transform-classes.md
Closes https://github.com/babel/babel/issues/9183
> Document mixin pattern caveat when extending builtin classes

- js/repl/ExternalPlugins.js
- js/repl/ExternalPluginsModal.js
- js/repl/PluginConfig.js
- js/repl/Repl.js
- js/repl/ReplOptions.js
- js/repl/UriUtils.js
- js/repl/replUtils.js
- js/repl/types.js
Improvements on plugins selections:
> repl: improve UX for plugins

- website/pages/en/setup.js
Switch from a timestamp to a checksum, so that netlify does not see this file changed on every deployment.
> Use checksum to avoid regenerating file every time

- docs/plugin-transform-runtime.md
- docs/polyfill.md
- docs/preset-env.md
> Update docs for core-js 3

- docs/plugin-syntax-dynamic-import.md
The naming changed in the current version from `es6` to just `es`.
> Update name of core-js import for ES modules

- docs/v7-migration.md
`--compilers` is [deprecated](https://github.com/mochajs/mocha/wiki/compilers-deprecation)
> Update v7-migration for mocha

- docs/node.md
- website/versioned_docs/version-7.0.0/node.md
Got an error running `npx babel-node` and realized the docs were pointing to the old, non-scoped package.
I wasn't sure if it was semantically appropriate to change the references to `babel-node` made in the description as well. Is this project referred to as `babel-node` or `@babel/node`?
> Fix references to babel-node

- docs/standalone.md
- website/data/tools/browser/install.md
- website/versioned_docs/version-7.0.0/standalone.md
Updated the documentation with JSitor online web development tool details. 
JSitor also supports Babel 7.x versions.
Request you to get this also documented in your website documentation.
> Documentation updated with JSitor tool references

- docs/parser.md
Documents the changes from https://github.com/babel/babel/pull/9864 implemented by @nicolo-ribaudo.
> docs(@babel/parser): Document allowUndeclaredExports option.

- js/repl/ReplOptions.js
- js/repl/types.js
This adds the F# plugin proposal option. Should be usable as soon as 7.5.0 ships.
cc @nicolo-ribaudo @mAAdhaTTah
> Add F# option to pipeline proposal

- website/versioned_docs/version-7.5.0/plugin-proposal-pipeline-operator.md
Since they've now landed, we can remove this from the website.
> Remove Coming Soon! from fsharp pipelines

- docs/v7-migration.md
Found couple of possible typos in V7 migration docs:
* `monorepo's` -> `monorepos`
Previously: `For monorepo's we have added`
Now: `For monorepos we have added`
* `accidently` -> `accidentally`
In case these changes are inaccurate please let me know and I'll make the necessary changes. (^_^)
> docs(v7-migration): Fixed typo in V7 migration docs

- docs/usage.md
there was a typo that says "provided you use the [regenerator](plugin-transform-regenerator.md) plugin" which doesn't make sense
> fixed a typo in usage.md

- docs/plugin-transform-react-jsx.md
- website/versioned_docs/version-7.0.0/plugin-transform-react-jsx.md
👋
I think the code examples for `@babel/plugin-transform-react-jsx` could benefit from a small update, to keep them relevant!
* `deku` → `@emotion/core`
* es5 + cjs → esnext + esm
Let me know if this change would be undesirable, cheers!
> Modernize examples for plugin-transform-react-jsx

- docs/v7-migration-api.md
- website/blog/2016-08-26-babili.md
- website/blog/2017-12-27-nearing-the-7.0-release.md
- website/blog/2018-06-26-on-consuming-and-publishing-es2015+-packages.md
- website/blog/2018-07-19-whats-happening-with-the-pipeline-proposal.md
- website/blog/2018-08-27-7.0.0.md
- website/blog/2019-01-21-7.3.0.md
- website/blog/2019-07-02-the-babel-podcast.md
:blue_heart: Fix typos across **babel website repository**
<details><summary>See all fixed files</summary>
<p>
```
website/docs/v7-migration-api.md:153:75: "reccomended" is a misspelling of "recommended"
website/website/blog/2016-08-26-babili.md:194:10: "seperately" is a misspelling of "separately"
website/website/blog/2017-12-27-nearing-the-7.0-release.md:46:7: "definetely" is a misspelling of "definitely"
website/website/blog/2017-12-27-nearing-the-7.0-release.md:91:133: "abilitiy" is a misspelling of "ability"
website/website/blog/2017-12-27-nearing-the-7.0-release.md:101:120: "managable" is a misspelling of "manageable"
website/website/blog/2017-12-27-nearing-the-7.0-release.md:262:279: "maintainence" is a misspelling of "maintenance" …
```
> Fix typos across babel website repository

- docs/types.md
Fix docs for `t.classProperty` builder to accept `static` argument
```js
t.classProperty(key, value, typeAnnotation, decorators, computed, static);
```
> Fix docs for static property builder

- website/versioned_docs/version-7.0.0/v7-migration.md
These were the changes made in #2064 in the docs that wasn't reflected in versioned docs.
> Editorial:Ported #2064 typo fixes to versioned doc

- docs/node.md
- website/versioned_docs/version-7.0.0/node.md
Fixes #2083 
This PR reverts #2016, and deals with an [issue](https://github.com/babel/babel/issues/10246) reported on babel.
Per [npx synopsis](https://github.com/npm/npx#description), `npx` will execute the `<command>` from `node_modules/.bin`, if the command is not found, it will query `<command>` package from npm registry and install it. When `<command>` contains `@scope`, it will [strip off](https://github.com/npm/npx/blob/latest/parse-args.js#L138) the `@scope`. Therefore `npx @babel/node` simply run `node` without any babel-register hooks.
As `@babel/node` provides binary command `babel-node`, we should run `npx babel-node` to invoke it.
For those prefer to install dependencies on the fly, another example is offered:
```
npx --package=@babel/{core,node,preset-env} babel-node
```
cc …
> Fix `npx babel-node` usage

- docs/preset-typescript.md
This adds documentation for the proposed addition of `allowNamespaces` as an option for `babel-preset-typescript`.
> Add allowNamespaces to typescript preset

- docs/v7-migration.md
The `@latest` version of core-js is now v3, which has a different path to specific polyfills than v2.
> docs(v7-migration): add core-js v3 path for importing `flatMap`

- docs/parser.md
Related: https://github.com/babel/babel/pull/10148
/cc @mathiasbynens I couldn't find any official docs on v8 Compiler Intrinsics other than the source code you provided before. Could you spare some time write about it? I am more than happy to reference one in our docs.
> feat: add v8intrinsic language extensions

- js/repl/ReplOptions.js
At the moment, the links of the babel-preset-env on the repl page redirects to the github repository which does not contain the necessary documentation.
I replaced the babel-preset-env documentation links on the repl page.
1. Go to the repl page
2. Go to the env preset section
3. Click on any option
> Replace the babel-preset-env documentation links on the repl page

- website/yarn.lock
Notably, merges entries for `remarkable` which drops `underscore.string` vulnerability warning.
> Dedupe some website deps

- docs/config-files.md
This adds docs for `babel.config.json`, which is added in https://github.com/babel/babel/pull/10501.
> Add docs for babel.config.json and babel.config.cjs

- docs/plugin-transform-react-jsx.md
- docs/preset-react.md
This documentation is for https://github.com/babel/babel/pull/10572
> [transform-react-jsx] Add useSpread option doc

- docs/parser.md
- docs/plugin-syntax-top-level-await.md
https://github.com/babel/babel/pull/10449
> Add docs for top level await parsing

- website/static/css/video.css
- Clear floated videos responsively
- Uses `calc` to define the video container's widths instead of hardcoding.
/cc @nicolo-ribaudo
> Fix uncleared floating videos

- website/blog/2019-11-08-babels-funding-plans.md
I don't think this was intentional but it was disappointing to see the financial contributions of the companies I've worked for ignored, which I would consider fairly substantial since Babel would be nothing without it. It represents what was then a sustainable model for my work on Babel.
Happy to make changes, and discuss whether I am even considered a "maintainer" but the project and funding did not start when Henry quit his job.
> Update "Babel's Funding Plans" blog post to include Sebastian employment

- docs/learn.md
- website/versioned_docs/version-6.26.3/learn.md
- website/versioned_docs/version-7.0.0/learn.md
This PR fixes a minor typo in the documentation for Classes ([see here](https://babeljs.io/docs/en/learn/#classes)) where "simple sugar" was used instead of [syntactic sugar](https://en.wikipedia.org/wiki/Syntactic_sugar).
> Simple sugar typo fix

- js/repl/compile.js
- js/repl/types.js
In this PR we guess the REPL file extension from the loaded presets. By doing so we could apply proper TypeScript transform when `typescript` preset is enabled.
Compared to #2019, this PR does _not_ introduce `filename` option as we don't output error message that will point to `filename` configuration when parsing a TypeScript without transform enabled. Also we are not going to expose `filename` option in a such limited UI space.
Manually tested on local build.
Closes #2019 
Fixes #1666
> fix: guess file extension from preset

- docs/parser.md
- website/versioned_docs/version-7.4.0/parser.md
- website/versioned_docs/version-7.5.0/parser.md
- website/versioned_docs/version-7.6.0/parser.md
- website/versioned_docs/version-7.7.0/parser.md
Documents the changes from babel/babel#8025 implemented by @arv
> docs(@babel/parser): Document createParenthesizedExpressions option.

- .gitignore
- js/repl/CodeMirror.js
- js/repl/ReplOptions.js
- js/repl/Utils.js
- js/repl/styles.js
- package.json
- website/pages/en/repl.js
- yarn.lock
In this PR we bump CodeMirror to 5.49.2 so that the dark theme `darcula` is included. When the UA supports `(prefers-color-scheme)` media query, we will enable `darcula` theme in the CodeMirror panel, otherwise it will fallback to the `default` theme.
I am open to other [dark themes](https://codemirror.net/demo/theme.html#default) as long as we can reach consensus. In this PR `darcula` is chosen because it is the default dark scheme available in WebStorm.
Screenshots:
> Enable `darcula` theme in REPL when dark colour scheme is preferred

- docs/plugin-proposal-do-expressions.md
Original link to the great reading was dead.
Update to the current master branch link.
Mark the manual navigation location in case the link dies again.
> Update dead link & add description

- docs/cli.md
Documentation for https://github.com/babel/babel/pull/9144 which also adds docs for `--keep-file-extension`. It makes more sense to document these two flags together since they are mutually exclusive.
> feat(cli): Document --(keep|out)-file-extension

- js/repl/ExternalPlugins.js
The recently-introduced Dark Mode reveals a UI glitch in the external plugins section
The PR changes the `background-color` to be transparent. DOM structure is also simplified for better a11y and aesthetic view.
> fix: redundant pluginActions background-color

- js/repl/PluginConfig.js
- js/repl/Repl.js
- js/repl/UriUtils.js
- js/repl/types.js
Closes #1868 
Remove babel-minify toggle on the REPL since it is currently unmaintained.
> breaking: remove minify toggle

- website/data/sponsors.yml
- website/siteConfig.js
They are effectively a base support sponsor, but since they use the "one time" donation every year rather than using the yearly subscription, they aren't automatically showed on our website.
Also, they are currently our top sponsor after Handshake.
> Add trivago to the sponsors list

- js/repl/loadBundle.js
In this PR we load minified standalone bundle into workers. The network usage sees 25% decrease compared to loading the compressed unminimized versions.
> fix: use minified bundle

- docs/plugin-transform-runtime.md
- website/versioned_docs/version-7.0.0/plugin-transform-runtime.md
- website/versioned_docs/version-7.4.0/plugin-transform-runtime.md
Closes #2055
Caused a bundle reduction of ~1%: https://github.com/mui-org/material-ui/pull/18512#issuecomment-558086399
I don't know if the same applies for older version. I backported the change to the 7.4 docs (with example) and 7.0 (without example).
> feat(transform-runtime): Document `version` option

- docs/parser.md
The property is named `range`, not `ranges`: https://github.com/babel/babel/blob/master/packages/babel-parser/src/parser/node.js#L16
> parser.md: fix the name of the range property

- scripts/download-sponsors.js
There is a donation in this format which breaks our script:
```js
{
tier: null,
fromAccount: {
name: 'incognito',
slug: 'incognito-26c59fb7',
website: null,
imageUrl: 'https://images.opencollective.com/incognito-26c59fb7/avatar.png',
description: null
}
}
```
> Fix build script

- docs/options.md
- scripts/download-sponsors.js
Documented --copy-ignored (https://github.com/babel/babel/pull/10887/) in options section as per @existentialism  comment.
https://github.com/babel/website/pull/2146#discussion_r358862858
> Added doc for --copy-ignored flag

- docs/plugin-proposal-optional-chaining.md
Per #2142, the `7.8` release includes a change to the return value of a `delete` operation on a nullish base. Previously, it had returned `undefined`, but now returns `true`. This PR adds documentation that indicates this change.
[![Image from Gyazo](https://i.gyazo.com/8fd017b150ea3f333c6652c807c873d5.png)](https://gyazo.com/8fd017b150ea3f333c6652c807c873d5)
> Update optional chaining documentation with deletion change

- js/repl/Repl.js
- js/repl/ReplOptions.js
- js/repl/compile.js
Try opening this url in a private window, to have a clean state: https://babeljs.io/repl/#?presets=env&version=7.8.3
You will see an error message about `@babel/preset-env` being registered twice. This is because `@babel/standalone` already includes it, and then we are re-loading it.
In this PR I chose to load `env-standalone` together with `@babel/standalone` when using an older version. This will increase the loading time for old Babel version, but it improves removes the `isLoaded`/`isLoading` logic which isn't needed anymore with the new bundled preset.
**EDIT**: ~~It still doesn't work.~~
https://deploy-preview-2157--babel.netlify.com/repl#?presets=env&version=7.8.3 Try enabling and disabling the preset a few times.
**EDIT**: It's working now
> Fix preset-env when using Babel 7.8.0+

- docs/register.md
- website/versioned_docs/version-6.26.3/register.md
- website/versioned_docs/version-7.0.0/register.md
Doc fix for https://github.com/babel/babel/issues/11108
@nicolo-ribaudo @JLHwung PTAL. Thanks.
> Added note for babel-register not compiling native Node.js ESM

- website/data/videos.js
The video displays:
```
null
If the owner of this video has granted you access, please sign in.
```
when trying to watch.
> Remove dead video link

- docs/traverse.md
- website/blog/2018-12-03-7.2.0.md
- website/versioned_docs/version-6.26.3/traverse.md
- website/versioned_docs/version-7.0.0/traverse.md
A follow-up to https://github.com/babel/website/pull/2173#issuecomment-587211640
This PR includes commits from #2173 as therefore should be reviewed after #2173 is merged.
> Replace emoji transcription

- js/repl/PluginConfig.js
- js/repl/ReplOptions.js
- js/repl/compile.js
- js/repl/replUtils.js
- js/repl/types.js
Simply adds a new option to select which core-js version to target.
> Add corejs option to preset env

- docs/preset-env.md
- website/versioned_docs/version-7.0.0/preset-env.md
- website/versioned_docs/version-7.4.0/preset-env.md
- website/versioned_docs/version-7.8.0/preset-env.md
Add caveats and state that we are ignoring the `op_mini all` browserslists query.
Resolves https://github.com/babel/babel/issues/11155
> add preset-env caveats

- docs/standalone.md
- website/versioned_docs/version-7.8.0/preset-env-standalone.md
- website/versioned_docs/version-7.8.0/standalone.md
`@babel/preset-env-standalone` has been deprecated since v7.8.0. Now it's time to update its docs.
> Remove docs of preset-env-standalone

- docs/options.md
- website/versioned_docs/version-7.0.0/options.md
- website/versioned_docs/version-7.1.0/options.md
- website/versioned_docs/version-7.8.0/options.md
- website/versioned_docs/version-7.8.4/options.md
The purpose of this PR is to update the description of `MatchPattern` function, specifically:
- Change `callee` parameter name to `caller`
- Describe `dirname` property that is a part of the `context`
Link to the source code that confirms the validity of these updates:
https://github.com/babel/babel/blob/779f00b8e9ce568ece4859501dd79682798c7fbf/packages/babel-core/src/config/config-chain.js#L698-L700
> docs: Update MatchPattern function description

- docs/v7-migration.md
- website/versioned_docs/version-7.0.0/v7-migration.md
- website/versioned_docs/version-7.6.0/v7-migration.md
Add link to most recent revision of the README.md before it was deleted in
https://github.com/babel/babel/commit/5e589032509126b68278ea1cb9f1c00f84012871
> docs(Migration): Fix broken link in section Stage Presets Deprecations

- docs/cli.md
- website/versioned_docs/version-7.0.0/cli.md
- website/versioned_docs/version-7.8.0/cli.md
- website/versioned_docs/version-7.8.4/cli.md
`npx babel` will install `babel` v6 if `@babel/cli` is not installed locally. In babel 8 we can propose the `npx @babel/cli` usage, before that we should notice users that `@babel/cli` must be installed locally before running `npx babel`.
> add note on `npx babel` usage

- docs/cli.md
- website/versioned_docs/version-7.0.0/cli.md
- website/versioned_docs/version-7.8.0/cli.md
- website/versioned_docs/version-7.8.4/cli.md
add `--config-file` example for `@babel/cli`.
Resolves https://github.com/babel/babel/issues/11174.
> add config file example

- docs/generator.md
- website/versioned_docs/version-6.26.3/generator.md
- website/versioned_docs/version-7.0.0/generator.md
Docs related to https://github.com/babel/babel/pull/11028 .
/cc: @nicolo-ribaudo @JLHwung PTAL. Thanks.
> Added docs for numbers in jsescOption in babel-generator

- docs/plugin-transform-typescript.md
- docs/preset-typescript.md
- website/versioned_docs/version-7.0.0/plugin-transform-typescript.md
- website/versioned_docs/version-7.0.0/preset-typescript.md
- website/versioned_docs/version-7.5.0/plugin-transform-typescript.md
- website/versioned_docs/version-7.6.0/preset-typescript.md
- website/versioned_docs/version-7.7.0/plugin-transform-typescript.md
- website/versioned_docs/version-7.8.0/plugin-transform-typescript.md
- website/versioned_docs/version-7.8.0/preset-typescript.md
Refs https://github.com/babel/babel/pull/11173#issuecomment-591707329
This PR adds documentation for the new `onlyRemoveTypeImports` configuration option in the upcoming 7.9.0 release.
Questions:
1. This is my first time working in this repo. Did I miss anything?
2. I fixed up the docs so that they matched and did a little editing. Is it okay that I didn't backport these changes to the older versions of the docs?
> docs: add onlyRemoveTypeImports to (preset|plugin-transform)typescript

- js/repl/PluginConfig.js
- js/repl/Repl.js
- js/repl/ReplOptions.js
- js/repl/Utils.js
- js/repl/compile.js
- js/repl/replUtils.js
- js/repl/types.js
This PR adds a new `bugfixes` toggle to the preset env options tab in REPL.
Because we validate the top level options, the `bugfixes` toggle is only available when babel version is gte 7.9.0.
Related: https://github.com/babel/babel/pull/11083
> Add bugfixes preset env option to REPL

- js/repl/compile.js
This PR is a follow-up to #2194 . #2194 only controls the UI entry of bugfixes option, but we should also control the config passing, otherwise preset-env will throw on invalid options.
> fix: do not set bugfixes when Babel.version is not >= 7.9.0

- docs/plugin-transform-react-jsx.md
- docs/preset-react.md
This PR adds `automatic | classic` runtime options and `importSource` to the `plugin-transform-react-jsx` docs.
> add new options to `plugin-transform-react-jsx` docs

- docs/preset-env.md
- website/versioned_docs/version-7.9.0/preset-env.md
- Looks like `bugfixes` is not `true` by default but is rather an opt-in.
> fixes documentation for bugfixes

- website/sidebars.json
Removed sidebar entries of deprecated/unmaintained presets. For general reference people can still access it from docs search.
> chore: remove deprecated preset sidebar entries

- js/repl/Repl.js
This PR fixes a regression introduced at #2157: When `Prettify` is not enabled, the compilation is never invoked so the transformed code is not print to the right panel.
Manually tested on my local build.
[This PR](https://deploy-preview-2217--babel.netlify.com/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1oGIAOBuF0C2AFAJSK6oBmA9gE7QEAuAFgJYQB0m0l50A2gLpEcqAL5IRQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-3%2Cenv&prettier=false&targets=&version=7.8.7&externalPlugins=) vs. [master](https://babeljs.io/repl#?browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYGwhgzhAEDC0G8BQ1oGIAOBuF0C2AFAJSK6oBmA9gE7QEAuAFgJYQ …
> fix: compile code when no plugins are enabled

- docs/usage.md
When running with the config provided in the usage guide there's a warning.
```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:
npm install --save core-js@2    npm install --save core-js@3
yarn add core-js@2              yarn add core-js@3
```
This follows the warning recommendation and sets the `corejs` …
> Fix warning about corejs in provided config

- js/minirepl.js
As a follow up to #2223 , after we updated the mini repl preset to a more modernized one, it turns out some of our code examples does not get transformed at all.
This PR update code examples to showcase some of the latest ES features that we still need to apply babel transforms.
> update landing page code example

- js/repl/PluginConfig.js
- yarn.lock
- Updated default presets to `"env, react, stage-2"`, since "env" does not contains stage-2 proposals
- Update env node.js version to 10.13 since node 8 is EOL
- Update env browserslists targets to `"defaults, no ie"`
- Enable env "bugfixes" by default
> Update REPL defaults

- js/repl/PluginConfig.js
- js/repl/Repl.js
- js/repl/WorkerApi.js
- js/repl/loadPlugin.js
This reverts commit 51f182619eaddab8e64611bcbb0019f962dd93ca.
Credits to @xtuc who fixed the `bundle.run` backend.
> Revert "hotfix: use unpkg.com (#2228)"

- docs/standalone.md
- Add a summary before discussing use cases
- Make it easier to see how to use standalone in browser tags
- Document async parameter
- Document data-type="module" https://github.com/babel/babel/pull/11466
> Revamp standalone documentation

- docs/plugin-proposal-private-methods.md
**Problem:** The name in the docs referencing `@babel/plugin-proposal-class-properties` was listed as `@babel/proposal-class-properties`, which doesn't exist.
**Solution:** Fix the name.
> Fix package name for plugin-proposal-class-props

- js/repl/ReplOptions.js
If you ever select a different pipeline proposal than minimal, you cannot select minimal again, cause the option value prop was misspelled.
May all your bug fixes be this easy.
> Fix pipeline proposer picker

- docs/plugin-proposal-private-property-in-object.md
- docs/plugins.md
Re: https://github.com/babel/babel/pull/11372
Re: https://github.com/tc39/proposal-private-fields-in-in
> Add doc for private-property-in-object transform

- docs/preset-env.md
Docs for https://github.com/babel/babel/pull/11434
> docs(preset-env): add browserslistEnv option

- website/blog/2018-09-17-7.1.0.md
- website/blog/2018-12-03-7.2.0.md
- website/blog/2019-01-21-7.3.0.md
- website/blog/2019-03-19-7.4.0.md
- website/blog/2019-07-03-7.5.0.md
- website/blog/2019-09-05-7.6.0.md
- website/blog/2019-11-05-7.7.0.md
- website/blog/2020-01-11-7.8.0.md
- website/blog/2020-03-16-7.9.0.md
Noticed by reviewing https://github.com/babel/website/pull/2260
There's only 1 h2, which is "highlights" so it is unnecessary. Seems like I just added that in for 7.1 post for no reason so my bad 😄
> remove empty highlights section, change others to h2

- docs/plugin-transform-spread.md
- website/versioned_docs/version-7.0.0/plugin-transform-spread.md
- website/versioned_docs/version-7.10.0/plugin-transform-spread.md
Adds documentation as suggested here: https://github.com/babel/babel/issues/11683#issuecomment-639753629
This explains the scenario where `[...Array(2)].map((_, index) => index)` produces `[1,2]` in the browser, but an array with two holes after transpiling.
Resolves https://github.com/babel/babel/issues/11683
> Document loose babel-plugin-transform-spread behaviour on array with holes

- js/repl/CircleCI.js
- js/repl/loadBundle.js
The repl for `master` is currently not loading: try opening https://babeljs.io/repl/build/master in an incognito window.
This is because the repl always gets the _last_ CI build from Circle CI. However, it could happen that it's not `build-standalone` but `e2e-*` (https://circleci.com/api/v1.1/project/github/babel/babel/tree/master?filter=successful&limit=1): in that case, it won't find the artifact.
This PR fixes it by loading the last 10 builds and then finding the correct one.
> [repl] Get the correct job id from CircleCI

- docs/plugin-transform-typescript.md
I published this plugin a while back - it originally was in the Jest codebase, but we broke it out to use in `eslint-plugin-jest` as well.
In theory the same logic could be applied to handle `import =`, so happy to do that if people think it would be useful.
> Suggest `babel-plugin-replace-ts-export-assignment` plugin as workaround for TS

- docs/preset-flow.md
- docs/preset-typescript.md
- website/versioned_docs/version-7.9.0/preset-flow.md
- website/versioned_docs/version-7.9.0/preset-typescript.md
We linked to React Get Started Page: https://babeljs.io/docs/en/babel-preset-react#installation
I think it makes sense to extends to TypeScript/Flow.
Fixes #2287
> docs: link getting started page on flow/typescript preset

- website/data/tools/rollup/install.md
- website/data/tools/rollup/usage.md
Adjusted several things for the Rollup setup guide:
* [`rollup-plugin-babel`](https://github.com/rollup/rollup-plugin-babel) has been deprecated for a while now, replaced this with the maintained version `@rollup/plugin-babel` and adjusted the links as well.
* Removed the installation instruction for `babel-preset-es2015-rollup`. The base ES2015 preset from Babel itself is deprecated and so installing it will present the user with...well...deprecation warnings.
> Update Rollup usage/setup guide

- website/data/team.yml
Well as you noticed I am not really active in babel, I'm struggling with live and the pandemic is not helping with that. But what I wanted to say: I don't feel it's fair to be represented as core member anymore. I'm happy to help in the future and I'm always reachable, but I'm already so far away from the project and it feels that will not change any time soon. 
I also noticed that Huáng is not represented on the team page, but looking at the babel commits I only see his face :joy: So I guess you should be added.
> Move me to contributors, add JLHwung, order core by name

- docs/configuration.md
Added usage on `BABEL_SHOW_CONFIG_FOR`.
I also added an explainer about how Babel merges config items. I wish I could backport this section but it may seems confusing without the context of config items, which is revealed by `SHOW_CONFIG`.
> feat: add SHOW_CONFIG docs

- docs/options.md
- docs/preset-env.md
- website/versioned_docs/version-7.0.0/options.md
- website/versioned_docs/version-7.0.0/preset-env.md
- website/versioned_docs/version-7.1.0/options.md
- website/versioned_docs/version-7.10.0/preset-env.md
- website/versioned_docs/version-7.4.0/preset-env.md
- website/versioned_docs/version-7.8.0/options.md
- website/versioned_docs/version-7.8.0/preset-env.md
- website/versioned_docs/version-7.8.4/options.md
- website/versioned_docs/version-7.9.0/options.md
- website/versioned_docs/version-7.9.0/preset-env.md
`{ modules: false }` has been long used as a fast switch to "preserve ES module" so bundlers can leverage from the module syntax. However the defaults `{ modules: "auto" }` should be preferred because it reads caller support data and reduces cognitive loads -- Idea like "I want to disable module transforms so Webpack can do tree shaking" is not straightforward, it is the defaults that should work out of that for you.
Since Babel 7.11, `preset-env` will assume `{ modules: false }` as to "preserve ES module" _and_ the compiled code will be served without bundling. By doing so `preset-env` can determine whether it should transpile `export * as ns` based on the targets. This assumption only works when it is _not_ passed to bundlers, where bundlers may not support latest module syntax, (e.g. …
> docs: clarify modules option in preset-env

- website/blog/2020-07-13-the-state-of-babel-eslint.md
Noticed a few typos in the post 🙃
> fix: typos in State of babel-eslint blog post

- docs/caveats.md
- website/versioned_docs/version-6.26.3/caveats.md
- website/versioned_docs/version-7.0.0/caveats.md
We have mentioned this assumption before 
https://github.com/babel/babel/pull/7043#discussion_r157670067
https://github.com/babel/babel/pull/11372#discussion_r403355516
https://github.com/babel/babel/issues/11744#issuecomment-649573846
but never state it clearly.
> add builtins assumptions

- docs/preset-env.md
- website/versioned_docs/version-7.0.0/preset-env.md
- website/versioned_docs/version-7.4.0/preset-env.md
- website/versioned_docs/version-7.8.0/preset-env.md
- website/versioned_docs/version-7.9.0/preset-env.md
Attempts to address:
* Adds an explicit "No targets" subsection to the `targets` option
* Improves description around preset-env's current behavior wrt to browserslist `defaults` query
* Remove and tweak the description of the `debug` option (didn't really read well)
* Fix a broken link in v7.0.0 docs
* Removed an extraneous `[Options](options.md#presets)` link from the browserslist section
> Tweak preset-env docs

- website/data/tools/mocha/install.md
- website/data/tools/mocha/usage.md
I ran into below while I was following setup recommendations with mocha
```
error: bundling failed: Error: Requires Babel "^7.0.0-0", but was
loaded with "6.26.3". If you are sure you have a compatible version of
@babel/core, it is likely that something in your build process is
loading the wrong version. Inspect the stack trace of this error to
look for the first entry that doesn't mention "@babel/core" or
"babel-core" to see what is calling Babel.
```
Doc says to import `babel-register` although it sounds like this has been moved to `@babel/register`
See more info in the [bug ticket](https://github.com/babel/website/issues/2305) and [stackoverflow post](https://stackoverflow.com/questions/51873516/requires-babel-7-0-0-0-but-was-loaded-with-6-26-3)
> Update mocha doc telling to import @babel/register instead of babel-register

- js/repl/PluginConfig.js
- js/repl/compile.js
`parser-babylon.js` is deprecated in favor of `parser-babel.js`
> fix: prettier babel parser filename

- docs/preset-env.md
To avoid potential confusion like https://github.com/babel/babel/issues/12123
> Mention mobileToDesktop in preset-env docs

- _redirects
There are some broken links of the pattern `/docs/FOO` which don't work and give 404. The should be instead linked to `/docs/en/FOO`.
As suggested by @JLHwung [here](https://github.com/babel/website/pull/2388#issuecomment-705781835) That is now implemented.
> Fixed broken links in docs

- docs/plugin-syntax-module-string-names.md
Add plugin docs for `@babel/plugin-syntax-module-string-names` introduced in 7.12
> Module string names

- docs/core.md
https://github.com/babel/babel/pull/11907
> Add docs for loadPartialConfig file handling changes

- docs/plugin-transform-property-literals.md
Previous demo is not working, because foo keys are not reserved words
> Update plugin-transform-property-literals demo

- docs/parser.md
- docs/preset-env.md
Add parser documentation for syntax added in 7.12. I also think the `moduleStringNames` should be mentioned, but I don't know where to put it.
> Add missing parser plugins

- docs/configuration.md
The missing quote causes syntax highlighting issues in the docs website.
> Fix syntax error which breaks syntax highlighting

- _redirects
Fixed broken link introduced in #2391 
Related: https://github.com/babel/babel/pull/12287
You can test the link redirection on https://deploy-preview-2410--babel.netlify.app/docs/en/next/babel-preset-env.html
> fix: versioned URL redirect

- docs/parser.md
Generally updates `@babel/parser` docs, this PR includes commits from #2412 
fixes #2397
> Polish babel parser

- docs/plugin-transform-react-jsx.md
This caused quite some confusion on my side. 😄
> Fix incorrect import paths in @babel/plugin-transform-react-jsx docs

- js/repl/CircleCI.js
We have added so many CircleCI tasks that the standalone build task is not included in limit=10 jobs.
This PR increases `limit` to CircleCI defaults: https://circleci.com/docs/api/v1/#recent-builds-for-a-single-project
Fixed issue: Can not access Babel REPL main build (https://babel.dev/repl/build/main) even the build is successful.
> fix: increase the limits on recent builds to CircleCI API defaults

- docs/standalone.md
Removing mentions of merged or defunct repos:
* babel-standalone-bower
* babel-standalone
> doc: update standalone installation

- js/repl/ReplOptions.js
They have been deprecated since 7.0.0, and they are not even available anymore on npm (the npm packages are empty).
Since existing repl urls and existing settings saved in localStorage still have those presets, I didn't fully remove the option (to avoid breaking existing URLs). Instead, they are just hidden if they are not already enabled.
I also moved the "targets" option to the top: if we are removing the yearly presets it should have a more prominent role, since it's the main way to choose what to transpile. Also, this will better align with the top-level option of Babel 7.13.0.
Preview: https://deploy-preview-2439--babel.netlify.app/repl
Preview with the es2017 preset enabled: https://deploy-preview-2439--babel.netlify.app/repl#?presets=es2017
> Remove yearly presets from the REPL

- docs/plugin-transform-runtime.md
Docs for https://github.com/babel/babel/pull/12632
> Add deprecation warning for `useESModules`

- docs/plugin-transform-typescript.md
Companion PR of https://github.com/babel/babel/pull/12765.
> docs: allowNamespaces in typescript now defaults to true

- docs/options.md
- docs/preset-env.md
These docs are mostly copied from `preset-env`'s docs, except for a few small edits.
> Add docs for top-level targets

- docs/core.md
- docs/node.md
Related to https://github.com/babel/babel/pull/11498
> Add cjs to default babel-node extensions

- docs/plugin-transform-react-constant-elements.md
"whitelist" is considered non-inclusive by some - figured it's easy enough to reword so might as well 🙂
> docs(plugin-transform-react-constant-elements): use inclusive language

- docs/plugin-transform-typescript.md
`allowNamespaces` now defaults to true
> docs: allowNamespaces now defaults to true

- _redirects
- docs/cli.md
- docs/code-frame.md
- docs/core.md
- docs/generator.md
- docs/helpers.md
- docs/options.md
- docs/parser.md
- docs/plugin-transform-runtime.md
- docs/plugin-transform-typescript.md
- docs/plugins.md
- docs/polyfill.md
- docs/preset-env.md
- docs/preset-flow.md
- docs/preset-react.md
- docs/preset-typescript.md
- docs/presets.md
- docs/register.md
- docs/runtime.md
- docs/standalone.md
- docs/template.md
- docs/traverse.md
- docs/types.md
- docs/v7-migration.md
- website/sidebars.json
- website/siteConfig.js
changed sidebar a bit, will do more in a next pr.
- showing the full name of package (removed the sidebar_label, which caused some misc formatting but should be ok)
- only updated docs/presets and doc/plugins pages so can ignore the others mostly.
- Fixes https://github.com/babel/website/issues/2179 (just change javascript to typescript code block in 2 places)
> fixup sidebar, modidy parts in plugins/presets

- docs/preset-typescript.md
When I checked the documentation of [`babel-preset-typescript`](https://babeljs.io/docs/en/babel-preset-typescript), I noticed some problems with the language of some sample codes:
After TypeScript code is converted, JavaScript should be generated.
The typed code should be TypeScript.
So I try to change it. Next, if I have time, I will check all the code formats in the webpage and try to fix the errors
> Modify the language type of some codes (in babel-preset-typescript)

- scripts/download-sponsors.js
- website/pages/en/index.js
- website/siteConfig.js
- website/static/css/index.css
> it's not that different from current
The new sponsors download graphql code is via https://github.com/webpack/webpack.js.org/blob/master/src/utilities/fetch-supporters.js. I think it is a more reliable than the old way of using "active" and "tier" because this would do it based on transactions within the last period of time (say a month or year) vs. just because someone happens to sign up at a certain tier (I recall some issues with it earlier but maybe it's fixed), either way haven't looked at any of it in a long time.
I would also like to show the total amounts donated (say for handshake or anyone else who has donated previously but just not currently), could just do it at the bottom, on another page, or make it a toggle. I forgot docu v1 doesn't really have interactivity so we'll …
> redo current monthly sponsors calculation, mostly from webpack

- docs/helper-compilation-targets.md
- website/sidebars.json
Drafted a doc on `@babel/helper-compilation-targets`.
Related: https://github.com/babel/babel/pull/13131
[Preview](https://deploy-preview-2484--babel.netlify.app/docs/en/babel-helper-compilation-targets)
> add helper-compilation-targets docs

- website/blog/2020-05-25-7.10.0.md
Previously it pointed to https://babel.dev/blog/2020/05/25/github.com/JLHwung due to being relative.
> Fix link in blog post

- docs/helper-hoist-variables.md
Drafted a basic docs for `@babel/helper-hoist-variables`.
I think it is okay to leave it off the "Helper Packages" section since this helper serves a very specific purpose. It is sufficient for those who follow the link from the npm README.
[Preview](https://deploy-preview-2500--babel.netlify.app/docs/en/babel-helper-hoist-variables)
> Add helper-hoist-variables docs

- docs/plugin-syntax-decorators.md
[This was changed a few years back](https://github.com/babel/babel/commit/d79b5eeeffab14f89c5be92888965e57fcab6436#diff-201cce1951d30fd696d97469efdf4451f2f406ac45317d947013b70a72c076d3), but this page was never updated to reflect that the `decoratorsBeforeExport` option no longer defaulted to `false`
> docs: Correction for plugin-syntax-decorators

- docs/parser.md
- docs/plugin-proposal-async-do-expressions.md
- docs/plugin-syntax-async-do-expressions.md
- website/sidebars.json
add docs on async-do-expressions
Related: https://github.com/babel/babel/pull/13116
| Page | Preview Link |
| --- | --- |
| `syntax` | [Link](https://deploy-preview-2486--babel.netlify.app/docs/en/babel-plugin-syntax-async-do-expressions) |
| `transform` | [Link](https://deploy-preview-2486--babel.netlify.app/docs/en/babel-plugin-proposal-async-do-expressions) |
> add `async-do-expressions` docs

- docs/parser.md
Add docs for https://github.com/babel/babel/pull/13113
> Add docs for `dts` new parser option for typescript plugin

- docs/parser.md
Add docs for error codes https://github.com/babel/babel/pull/13098#issuecomment-818289549
> Add docs for parser error codes

- docs/roadmap.md
- website/sidebars.json
This was an internal roadmap written by me and other team members for a possible sponsorship. We can make it public, to show the future direction of the project (or at least, its how the current core team would like to evolve the project).
I didn't delete the old roadmap (from 3 years ago), I just commented it out. About half of the things it contained have been done; the others seem more like ideas that are hard to implement with the Babel architecture.
> Update Babel roadmap

- docs/parser.md
Update parser docs for https://github.com/babel/babel/pull/13175
> Update parser docs for plugins enabled by default since 7.14.0

- docs/faq.md
- docs/index.md
- docs/plugin-proposal-class-properties.md
- docs/plugin-proposal-class-static-block.md
- docs/plugin-proposal-decorators.md
- docs/plugin-proposal-nullish-coalescing-operator.md
- docs/plugin-proposal-object-rest-spread.md
- docs/plugin-proposal-optional-chaining.md
- docs/plugin-proposal-private-methods.md
- docs/plugin-proposal-private-property-in-object.md
- docs/plugin-transform-classes.md
- docs/plugin-transform-computed-properties.md
- docs/plugin-transform-destructuring.md
- docs/plugin-transform-for-of.md
- docs/plugin-transform-modules-commonjs.md
- docs/plugin-transform-parameters.md
- docs/plugin-transform-spread.md
- docs/plugin-transform-template-literals.md
- docs/preset-env.md
In this PR we promote the alternative `assumptions` usage on the previous `loose` mode docs. I hope it can facilitate the transition from the vague `loose` mode to explicit assumptions.
This PR covers all the `loose` mode docs except `babel-preset-stage-*` since they are deprecated.
> Promote assumptions on loose docs

- docs/plugin-transform-typescript.md
Constantly we have feature requests like https://github.com/babel/babel/issues/10690 https://github.com/babel/babel/issues/12030 to include staged 3 features that are supported in TypeScript compilers. Since we are not making `preset-typescript` a `preset-whatever-tsc-can-do`, we should clarify this point on the docs.
Resolves https://github.com/babel/babel/issues/12030
Fixes #2311
> Clarify typescript preset/plugin scope

- docs/options.md
Instead correctly say 'options object'
Fixes #2535
> Fix Options page saying 'objects object'

- docs/configuration.md
- docs/options.md
I realize that we didn't mention how we merge `parserOpts`, `generatorOpts` and `assumptions`. This PR documents current merging strategies and updates the examples.
[Preview](https://deploy-preview-2531--babel.netlify.app/docs/en/configuration#how-babel-merges-config-items)
Resolves #2536
> docs: refine Babel config merging strategies

- docs/polyfill.md
- `https://github.com/zloirock/core-js#commonjs` to `https://github.com/zloirock/core-js#commonjs-api`
- `https://github.com/facebook/regenerator/blob/master/packages/regenerator-runtime/runtime.js` to `https://github.com/facebook/regenerator/blob/master/packages/runtime/runtime.js`
> Fix outdated link in polyfill.md

- docs/config-files.md
Ref: https://github.com/facebook/jest/issues/11444
@SimenB Btw, `babel-jest` could add `export { createTransformer }` (other than the `default` export) to avoid the need of `.default` when used from CommonJS or native ESM.
> Update `babel-jest` example

- docs/plugin-transform-typescript.md
- docs/preset-typescript.md
Docs for https://github.com/babel/babel/pull/13324
> Add docs for TS `optimizeConstEnums` option

- docs/parser.md
Docs PR of https://github.com/babel/babel/pull/13229
> docs: add attachComment

- docs/assumptions.md
- docs/plugin-transform-modules-commonjs.md
Add docs for changes in babel/babel#13290
> docs: add `noIncompleteNsImportDetection` assumption

- website/pages/en/index.js
Updated link to newest babel version blog post :).
Congratulations with the [new release](https://github.com/babel/babel/releases/tag/v7.15.0) 🎉 !
> docs: index: babel v7.14 -> v7.15

- docs/plugin-proposal-async-generator-functions.md
- docs/plugin-proposal-class-properties.md
- docs/plugin-proposal-class-static-block.md
- docs/plugin-proposal-export-namespace-from.md
- docs/plugin-proposal-json-strings.md
- docs/plugin-proposal-logical-assignment-operators.md
- docs/plugin-proposal-nullish-coalescing-operator.md
- docs/plugin-proposal-numeric-separator.md
- docs/plugin-proposal-object-rest-spread.md
- docs/plugin-proposal-optional-catch-binding.md
- docs/plugin-proposal-optional-chaining.md
- docs/plugin-proposal-private-property-in-object.md
- docs/plugin-proposal-unicode-property-regex.md
- docs/plugin-syntax-bigint.md
- docs/plugin-syntax-dynamic-import.md
- docs/plugin-syntax-import-meta.md
- docs/plugin-syntax-top-level-await.md
- docs/plugin-transform-async-to-generator.md
- docs/plugin-transform-dotall-regex.md
- docs/plugin-transform-exponentiation-operator.md
- docs/plugin-transform-named-capturing-groups-regex.md
- docs/plugins-list.md
- website/sidebars.json
Ref https://github.com/babel/babel/pull/13717, similar to https://github.com/babel/website/pull/2477
> move plugins to stage 4, es2022

- docs/usage.md
In [Usage Guide](https://babeljs.io/docs/en/usage), I can see the presets named "@babel/env". However, I cannot see this name elsewhere in the document, instead of "@babel/preset-env". So I modify all the "@babel/env" to "@babel/preset-env" in Usage Guide page.
> modify @babel/env to @babel/preset-env

- docs/plugin-proposal-pipeline-operator.md
Adds option for `"topicToken": "^"` to the Hack pipe operator to match the [current proposal](https://github.com/tc39/proposal-pipeline-operator).
See babel/babel#13749.
> pipe operator: Add topicToken: ^ (caret) option

- docs/plugin-proposal-function-bind.md
Fix misleading documentation on function bind.
A missing new line made the first example very confusing.
**From**
```js
obj::func;
// is equivalent to:
func.bind(obj)::obj.func;
// is equivalent to:
obj.func.bind(obj);
```
**To**
```js
obj::func;
// is equivalent to:
func.bind(obj)
::obj.func;
// is equivalent to:
obj.func.bind(obj);
```
> docs: fix misleading documentation

- docs/preset-env.md
The note is outdated, because the branch that supports ES6+ in UglifyJS is not maintained anymore, which means UglifyJS will never be compatible with ES6+. 
But there's a fork called `Terser` that supports ES6+ and acts as a successor of UglifyJS.
> Update ES6 minifier recommendation note

- docs/options.md
- docs/preset-env.md
Clarify difference between targets.node and a browserslist node query.
Context: https://github.com/babel/babel/issues/14167#issuecomment-1014844151
> docs: target.node vs browserslist node query

- docs/register.md
Babel PR: https://github.com/babel/babel/pull/14087
> Add docs for `@babel/register/experimental-worker`

- docs/plugin-proposal-unicode-sets-regex.md
- docs/plugin-syntax-unicode-sets-regex.md
Babel PR: https://github.com/babel/babel/pull/14091
> Add docs for the new `unicode-sets-regex` plugin

- docs/plugin-proposal-decorators.md
- docs/plugin-syntax-decorators.md
Babel PR: https://github.com/babel/babel/pull/13827
cc @pzuraq
> Add docs for the new decorators transform

- docs/plugin-proposal-pipeline-operator.md
- docs/plugin-syntax-pipeline-operator.md
Adds topic tokens `@@` and `^^` and deprecates `%` and `^`, as per the champion group’s consensus in the 2021-11 incubator call. (Does not deprecate `#`, which is still a candidate topic token.)
Also deprecates minimal-F# and F#+await styles in addition to smart mix, as per TC39’s decision in the 2021-08 plenary meeting.
See also babel/babel#13973. A separate pull request in babel/babel will add the deprecations.
> pipe: Add topicToken: ^^ and @@; prefer Hack style

- docs/options.md
I found two commas here. So I deleted it
See also
- https://babeljs.io/docs/en/options#output-targets
> Remove redundant comma

- docs/preset-env.md
Currently, for the uninitiated, if they (or me in this case) installs babel, uses it, and encounters an issue where `useBuiltIns` is the solution, they will come across documentation that shows how to specify "useBuiltIns", but will encounter a warning:
```
WARNING (@babel/preset-env): We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the …
```
> Demonstrate how to specify a core-js version.

- docs/plugin-transform-modules-amd.md
- docs/plugin-transform-modules-commonjs.md
- docs/plugin-transform-modules-umd.md
It looks like the `umd` and `amd` plugins also support `importInterop` in the code, but don't mention it in the docs. Should I just copy/paste the entire `importInterop` section from the CJS docs? It's not obvious to me that that will be accurate. :smile:
https://github.com/babel/babel/pull/14456
> [7.18.0] Update docs for `importInterop` option

- docs/preset-react.md
https://github.com/babel/babel/blob/main/packages/babel-preset-react/src/index.ts
I couldn't find plugin-transform-react-pure-annotations.md under [website/docs](https://github.com/babel/website/tree/main/docs) directory.
Even so it would be worth to list this plugin to prevent duplicate use.
> Add `transform-react-pure-annotations` to preset-react.md

- docs/preset-react.md
The link to [`@babel/plugin-transform-react-pure-annotations`](https://babeljs.io/docs/en/plugin-transform-react-pure-annotations.md) returned a 404 page
> Removed 404 page

- docs/config-files.md
Currently, the list of possible configs can be hard to understand for some of the users.
To address this, and simplify the information a bit, I have changed the initial filenames with wildcard and listed all possible extensions after that, instead of using `json` as a base, which might lead to the creation of files like `babel.config.json.mjs`.
Same has been done to the `.babelrc` entry, however I have also extracted the no extension possibility to the separate line, since this was the most confusing part of the previous entry.
Additionally, to avoid repetition, I have changed the "Supported file extensions" intro sentence, so it link to the "Configuration File Types" section, instead of listing the possible configuration file options again.
> config-files: rephrase entries in list of configs

- docs/generator.md
Fixes https://github.com/babel/babel/issues/13617
Added a note that babel-generator does not guarantee the output format
> Clarify that generator does not guarantee the output format

- docs/preset-typescript.md
"@babel/preset-typescript"  need a filename for transformSync function.
> docs: update babel preset typescript example

- docs/assumptions.md
Simple typo fix for `classess` in docs on `assumpitons`
> fix: typo 'classess' in assumptions docs

- docs/plugin-proposal-duplicated-named-capturing-groups-regex.md
- docs/plugins-list.md
Docs for https://github.com/babel/babel/pull/14805
> Add docs for duplicated-named-capturing-groups-regex

- docs/parser.md
- docs/plugin-proposal-decorators.md
Docs for https://github.com/babel/babel/pull/14836
> Document decorators 2022-03 version.

- docs/parser.md
Fixed example for `destructuringPrivate`. Without `class name` it will throw en error.
> docs: parser: example: fixed `A class name is required.` error for `destructuringPrivate`

- docs/editors.md
Hi @existentialism & @nicolo-ribaudo  , I noticed that on the [editors](https://babeljs.io/docs/en/editors) page, we don't have Emacs, although Vim has its place. So having in mind that Vim and Emacs aren’t going anywhere anytime soon, it would be fair for the Emacs crowd to have their place next to Vim on the [editors](https://babeljs.io/docs/en/editors) page :D
> adding-Emacs-editor

- docs/cli.md
ref: https://github.com/babel/babel/pull/14950
http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/ is broken.
> doc: Modify `babel-cli` documentation

- docs/plugins-list.md
private-methods were missed from the TC39 list
> Added private-methods

- docs/plugin-transform-runtime.md
When I tried to transform with `polyfill: false` I got this runtime error:
https://github.com/babel/babel/blob/aad7eb743d1354a5475f9d43226bfedc5f149e4b/packages/babel-plugin-transform-runtime/src/index.ts#L161-L165
> Remove the note about polyfill being a default behavior of the `@babel/plugin-transform-runtime`

- docs/plugin-syntax-typescript.md
- docs/plugin-transform-typescript.md
Added docs for https://github.com/babel/babel/pull/14923
> docs: document `dts` and `disallowAmbiguousJSXLike` options

- docs/parser.md
The docs for parser currently includes `function.sent` in the list of syntax "already enabled on the latest version of @babel/parser, and cannot be disabled because they are part of the language".
This does not appear to be correct.
With `@babel/parser` v7.20.5 (latest at time of writing):
```js
const {parse} = require('@babel/parser');
parse('function* f() { return function.sent; }');
```
throws error `SyntaxError: This experimental syntax requires enabling the parser plugin: "functionSent". (1:32)`
This PR revises the docs to reflect that `functionSent` plugin must be manually enabled to parse this syntax.
> Parser `function.sent`requires plugin

- docs/parser.md
Docs for https://github.com/babel/babel/pull/15114
> Docs for `allowNewTargetOutsideFunction`

- .gitattributes
- docs/parser.md
Docs for https://github.com/babel/babel/pull/15320
> Add docs for `@babel/parser`'s `annexb` option

- js/repl/ReplOptions.tsx
Current buggy behavior:
New behavior:
> Fix REPL sidebar bottom style

- js/repl/PluginConfig.ts
- js/repl/Repl.tsx
- js/repl/ReplOptions.tsx
- js/repl/UriUtils.ts
- js/repl/compile.ts
- js/repl/replUtils.ts
- js/repl/types.ts
Added `modules` option toggle to REPL, also updated REPL docs links.
Preview link: https://deploy-preview-2738--babel.netlify.app/repl
> feat: add modules option toggle

- docs/standalone.md
- Added examples of `data-plugins`
- Added (and how to access) list of available presets / plugins
Preview link: https://deploy-preview-2736--babel.netlify.app/docs/babel-standalone
> Refine @babel/standalone docs

- docs/assumptions.md
- docs/generator.md
The MDX requires line breaks after `<summary>` tag.
> fix summary table

- _redirects
This should add redirect to repl? 
fixes https://github.com/babel/website/issues/2735
> chore: add redirect for repl

- website/src/pages/versions.js
This is a follow-up to #2733, I forgot to replace the last `customFields.baseUrl` occurrence.
> fix 6.23.0 blog post link

- docs/plugin-transform-runtime.md
A note is added to remind developers that, when `@babel/plugin-transform-runtime` is enabled, they should unset the `useBuiltIns` option in `@babel/preset-env`. Otherwise, global scope pollution may not be completely stopped.
> Add notes when use with @babel/preset-env

- docs/plugin-proposal-pipeline-operator.md
Also added supported topic tokens.
Preview link: https://deploy-preview-2743--babel.netlify.app/docs/babel-plugin-proposal-pipeline-operator
> update pipeline operator proposal links

- js/repl/PluginConfig.ts
- js/repl/ReplOptions.tsx
- js/repl/replUtils.ts
See https://twitter.com/richardiii/status/1636477045143379968.
It's been a while, and the old one really isn't recommended for new projects.
Haven't tested.
> Make automatic JSX runtime default in REPL

- docs/helper-bindify-decorators.md
- docs/helper-builder-binary-assignment-operator-visitor.md
- docs/helper-call-delegate.md
- docs/helper-check-duplicate-nodes.md
- docs/helper-create-class-features-plugin.md
- docs/helper-create-regexp-features-plugin.md
- docs/helper-define-map.md
- docs/helper-explode-assignable-expression.md
- docs/helper-explode-class.md
- docs/helper-function-name.md
- docs/helper-module-transforms.md
- docs/helper-optimise-call-expression.md
- docs/helper-regex.md
- docs/helper-remap-async-to-generator.md
- docs/helper-replace-supers.md
- docs/helper-skip-transparent-expression-wrappers.md
- docs/helper-string-parser.md
- docs/helper-validator-option.md
- scripts/generate-helper-docs-template.mjs
In this PR we add placeholder docs for all helper packages. So users won't see a 404 error when visiting such links from npm/github.
- For maintaining helpers, added a pending docs note and point to the GH source
- For archived helpers, added an archived note and point to the Babel archives
> Add placeholder docs for helpers

- docs/cli.md
Added an example of transpiling TypeScript directories, and so that we can add a link to the Babel default extensions requested in https://github.com/babel/babel/issues/15503#issuecomment-1476508274.
Also refined the set file extensions sections.
> refine babel-cli docs

- docs/plugin-transform-react-constant-elements.md
The behavior of `@babel/plugin-transform-react-constant-elements` has already been changed since 2021, see https://github.com/babel/babel/pull/12967.
The PR updates the documentation page.
> Update outdated plugin-transform-react-constant-elements.md

- docs/plugin-proposal-decorators.md
Resolves https://github.com/babel/website/issues/2768
In this PR we
- updated the examples of decorators to the "2023-01" version 
- marked the version option as required
- removed the CLI usage because this plugin requires at least one plugin option, which can not be passed from command line
- linked the spec repo for a brief summary of different decorator versions
- recommend to use `preset-env` when using with class properties / private methods transform, c.f. https://github.com/babel/babel/discussions/15582
Preview link: https://deploy-preview-2770--babel.netlify.app/docs/babel-plugin-proposal-decorators
> update decorators docs

- docs/plugin-transform-flow-strip-types.md
- docs/plugin-transform-react-jsx.md
- docs/plugin-transform-typescript.md
- website/sidebars.json
This is an experimental PR. I would like learn about your opinions.
Previously the plugins have dedicated sidebars, so there are no means to navigate to the plugin pages unless you already know the plugin name _and_ either 1) search on the docs website or 2) visit the plugin docs link from npm package readme.
In this PR we moved most plugins (except modules / proposals) under the presets page. So users can learn from the sidebar that which plugins are included in which presets and then they can check it out if they want to learn more about the presets.
The "presets" category now displays contents of "config reference / presets" page now that docusaurus 2 supports category link.
Preview link: https://deploy-preview-2739--babel.netlify.app/docs/
> sidebar: move plugins under presets

- scripts/download-sponsors.js
Recently our netlify builds are failing because we introduced the babel-next build, which eventually hit the OC free API rate limit: 10 / min. ([ref](https://graphql-docs-v2.opencollective.com/access))
In this PR we will add a personal token when the environment variable `OC_API_TOKEN` is available. When a token is provided, the rate limit is 100 / min, it should be enough for the netlify jobs.
> support OC_API_TOKEN

- docs/options.md
Companion of https://github.com/babel/babel/pull/15551
> Docs: add Babel 8 default targets

- website/docusaurus.config.js
- website/sidebars.js
Use `sidebars.js` so that we can provide different sidebar items on Babel 8 docs based on the `BABEL_8_BREAKING` env toggle.
> Use sidebars.js

- docs/v7-migration.md
Use possessive "its", not contraction "it's".
> Fix typo in v7-migration.md

- js/repl/Repl.tsx
- js/repl/Worker.ts
- js/repl/WorkerApi.ts
- js/repl/types.ts
In this PR we provide builtin plugins available in `@babel/standalone` when the external plugins is an official Babel plugin. In this way we can reduce dependency on the rollup service and improve external plugin loading time.
Then we provide default options for decorators and pipeline plugins. Ideally we should provide an UI to modify such options, but for now at least we can provide a working plugin demo.
[Preview link (decorator transform only)](https://deploy-preview-2783--babel.netlify.app/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=AIMw9mBQDGA2CGBnRACAwig3pFKDEADgNw4qIAu85AltCgLYAUAlFgL6RtA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSi …
> Use builtin plugins when available and provide default options for some external plugins

- docs/plugin-transform-typescript.md
Docs for https://github.com/babel/babel/pull/15497
> TS `import =` and `export =` are now supported

- docs/plugin-transform-modules-amd.md
- docs/plugin-transform-modules-systemjs.md
- docs/plugin-transform-modules-umd.md
Add docs for module options supported in v7.9.0. The current docs are copied from `options.md`.
This is a docs PR for https://github.com/babel/babel/pull/11194
> Add module options docs

- js/repl/index.html
- webpack.config.js
The REPL CI build is broken because the script `./repl.js` can not be found from `/repl/build/12345`. In this PR we manually inject `/repl/repl.js` so that it can be imported under `/repl/build/12345`
We also remove another unused js import `minirepl` as it has been handled by docusaurus.
Preview URL:
https://deploy-preview-2781--babel.netlify.app/repl/build/54393
https://deploy-preview-2781--babel-next.netlify.app/repl/build/54393
> Fix repl CI build

- docs/plugin-proposal-explicit-resource-management.md
- docs/plugin-syntax-explicit-resource-management.md
- website/sidebars.js
Docs PR for https://github.com/babel/babel/pull/15633.
[Preview link](https://deploy-preview-2792--babel-next.netlify.app/docs/babel-plugin-proposal-explicit-resource-management)
> add docs for plugin-proposal-explicit-resource-management

- docs/parser.md
- docs/plugin-proposal-unicode-sets-regex.md
- website/sidebars.js
Docs PR for https://github.com/babel/babel/pull/15636 and https://github.com/babel/babel/pull/15638.
> add unicode-sets-regex to preset-env

- docs/plugin-proposal-import-attributes-to-assertions.md
- website/sidebars.js
Docs PR for https://github.com/babel/babel/pull/15620.
[Preview Link](https://deploy-preview-2793--babel-next.netlify.app/docs/babel-plugin-proposal-import-attributes-to-assertions/)
> add docs for plugin-proposal-import-attributes-to-assertions

- docs/plugin-proposal-decorators.md
Docs for https://github.com/babel/babel/pull/15570
> Add docs for decorators 2023-05

- _redirects
- docs/plugin-syntax-unicode-sets-regex.md
- docs/plugin-transform-unicode-sets-regex.md
- website/sidebars.js
> rename proposal-unicode-sets-regex to transform

- docs/assumptions.md
Resolves https://github.com/babel/babel/issues/15686.
> note on setClassMethods limit

- docs/plugin-bugfix-safari-id-destructuring-collision-in-function-expression.md
- docs/plugin-bugfix-v8-spread-parameters-in-optional-chaining.md
- website/sidebars.js
Added missing docs for bugfix plugins.
Preview Link:
https://deploy-preview-2800--babel.netlify.app/docs/babel-plugin-bugfix-safari-id-destructuring-collision-in-function-expression
> add bugfix plugins docs

- docs/parser.md
Capitalized `Tuple` in `recordAndTuple` plugin name.
> docs: parser: recordAndtuple -> recordAndTuple

- docs/v8-migration-api.md
- docs/v8-migration.md
- website/sidebars.js
This is a WIP as I am going through all the Babel 8 changes. The migration docs has two parts: the first is for general users and the second is for integration users / plugin developers, following what we did in Babel 7 migration docs.
Preview link:
Babel 8 Migration: https://deploy-preview-2765--babel.netlify.app/docs/v8-migration
Babel 8 Migration (Integration): https://deploy-preview-2765--babel.netlify.app/docs/v8-migration-api
> Add Babel 8 migration docs

- docs/learn.md
This is not mentioned in the standard:
https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#table-proxy-handler-methods
> learn.md: Remove enumerate from Proxy handler

- docs/v8-migration-api.md
As I see `extra` contains `parenthesized`:
> docs: v8-migration-api: parenthesized instead of parens

- docs/v8-migration.md
https://github.com/babel/babel/pull/15956
> [babel 8] Document removal of `-gc`/`-d` in `@babel/node`

- docs/parser.md
Docs for https://github.com/babel/babel/pull/15751 (partial), https://github.com/babel/babel/pull/15829, https://github.com/babel/babel/pull/15845
> Parser docs for 7.23.0

- docs/plugin-proposal-import-defer.md
- docs/plugin-proposal-import-source.md
- docs/plugin-proposal-optional-chaining-assign.md
- docs/plugin-syntax-import-defer.md
- docs/plugin-syntax-import-source.md
- docs/plugin-syntax-optional-chaining-assign.md
Docs for https://github.com/babel/babel/pull/15870, https://github.com/babel/babel/pull/15751, https://github.com/babel/babel/pull/15878
> Add docs for new 7.23.0 plugins

- docs/plugin-transform-react-jsx.md
- docs/preset-react.md
Companion of https://github.com/babel/babel/pull/12630
Babel 8 Preview: https://deploy-preview-2778--babel-next.netlify.app/docs/babel-preset-react
> add default jsx runtime in Babel 8

- docs/plugin-transform-react-jsx.md
- docs/preset-react.md
Companion of https://github.com/babel/babel/pull/12593.
> remove useBuiltIns and useSpread for Babel 8

- js/repl/PluginConfig.ts
- js/repl/ReplOptions.tsx
- js/repl/compile.ts
- js/repl/index.html
- js/repl/types.ts
I'm trying to fix old version babel support.
By the way, can your repl work normally when `yarn start`? An exception will occur in my repl locally.
> Some improvements and fixes

- docs/preset-env.md
- website/docusaurus.config.js
Docs for https://github.com/babel/babel/pull/15838
> [babel 8] Remove core-js 2 from preset-env docs

- docs/learn.md
In [learn section](https://babeljs.io/docs/learn) links that refer to ES6 Compatibility table is moved from https://kangax.github.io/compat-table/es6 to https://compat-table.github.io/compat-table/es6
> update broken links

- docs/preset-flow.md
- docs/preset-typescript.md
Add `ignoreExtensions` docs introduced in Babel 7.21.4.
Companion PR of https://github.com/babel/babel/pull/14955
<s>This PR depends on #2772, I will rebase after it is merged.</s>
> Add `ignoreExtensions` docs

- docs/v8-migration-api.md
https://github.com/babel/babel/pull/16126
> [babel 8] Remove `CodeGenerator` from `@babel/generator`

- babel.config.js
- docs/caveats.md
- docs/core.md
- docs/options.md
- docs/parser.md
- docs/plugin-proposal-decorators.md
- docs/plugin-transform-classes.md
- docs/preset-env.md
- js/repl/CodeMirror.tsx
- js/repl/CodeMirrorPanel.tsx
- js/repl/Modal.tsx
- js/repl/ReplOptions.tsx
- js/repl/index.html
- js/repl/index.tsx
- package.json
- webpack.config.js
- website/blog/2016-08-24-6.14.0.md
- website/blog/2017-09-12-planning-for-7.0.md
- website/blog/2020-05-25-7.10.0.md
- website/docusaurus.config.js
- website/package.json
- website/src/components/v1/MarkdownBlock.js
- yarn.lock
In this PR we update docusaurus to v3 and React to v18. 
1. Docusaurus updates MDX to v3. Impacts to our docs:
- `{` must be escaped `\{` if it is intended to be a literal left brace in the docs
- `<=` is invalid in MDX. Most usages are `IE <= 10`. We replace them with `IE &leq; 10`
- When markdown directives are nested, for example when `:::babe7` directive contains a `:::tip` directive. The outer directive must contain _more_ colons than the inner ones. For example
```md
::::babel7
:::tip
This feature will be overhauled in Babel 8
:::
::::
```
If the outer directive starts with `:::`, the MDX parser will _not_ throw any error, but an extra `:::` text will be visible because the MDX parser ends the outer directives whenever it reads `:::`, even if the inner directive has not been closed …
> Update to Docusaurus 3

- docs/core.md
- docs/options.md
Closes https://github.com/babel/babel/issues/16152
Also updated the `#options` link in `core.md` to the `options.md`.
> docs: clarify `.babelignore` file loading

- docs/plugin-transform-runtime.md
- docs/preset-env.md
- docs/v8-migration.md
Docs for https://github.com/babel/babel/pull/16141 and https://github.com/babel/babel/pull/16043
> [babel 8] Remove `loose`/`spec` from `preset-env`, and `useESModules`

- js/repl/Repl.tsx
You can try it, and change something in the left panel, then it will be compiled correctly.
[babel repl demo](https://babeljs.io/repl#?browsers=chrome%20%3E%3D%2049&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=NoQwNABARguhC8FgwNxA&debug=false&forceAllTransforms=false&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=8.0.0-alpha.2&externalPlugins=&assumptions=%7B%7D)
> :bug: fix: compile code not work when page reload

- docs/types.md
Updated `@babel/types` docs for [Babel v7.23.9](https://github.com/babel/babel/releases/tag/v7.23.9).
> docs: update babel types

- docs/assumptions.md
Docs for https://github.com/babel/babel/pull/16267
> Add `noUninitializedPrivateFieldAccess` assumption docs

- docs/preset-flow.md
For https://github.com/babel/babel/pull/16284
> Add docs for `experimental_useHermesParser`

- docs/plugin-proposal-optional-chaining-assign.md
- website/sidebars.js
When installing this plugin I received this error and needed to fix it as such
Error: [BABEL] /Users/blackmad/Code/gen2-blackmadeco/src/index.tsx: @babel/plugin-syntax-optional-chaining-assign: '.version' option required, representing the last proposal update. Currently, the only supported value is '2023-07'. (While processing: "/Users/blackmad/Code/gen2-blackmadeco/node_modules/@babel/plugin-proposal-optional-chaining-assign/lib/index.js$inherits")
> Update plugin-proposal-optional-chaining-assign.md docs to work

- website/data/tools/babel_cli/usage.md
Hey there. If I'm right, the link is broken. This change aims to fix it.
> For full documentation on the Babel CLI see the [usage docs](https://babel.dev/docs/usage/cli/).
> Fix page not found error

- docs/plugin-bugfix-firefox-class-in-computed-class-key.md
- website/sidebars.js
Add docs for https://github.com/babel/babel/pull/16390.
> Add docs for bugfix-firefox-class-in-computed-class-key

- docs/v8-migration.md
Docs PR for https://github.com/babel/babel/pull/16457.
> Bump Babel 8 node.js requirements

- docs/parser.md
`import * as ns from ''` differs between Babel AST and ESTree.
> docs: update Babel/estree ast difference

- website/src/css/custom.css
before:
after:
for light mode it stays without changes:
> fix(docsearch): better text contrast for active hit in dark mode

- docs/assumptions.md
Assuming I'm not being daft, `noObjectSuper` & `noUndeclaredVariablesCheck` do not seem to be a supported assumptions.
> docs(assumptions): Remove references to `noObjectSuper` & `noUndeclaredVariablesCheck`

- docs/v8-migration-api.md
Ref: https://github.com/babel/babel/pull/16504
Thanks to https://github.com/babel/babel/pull/16504#pullrequestreview-2166965866
> Add migration docs for removing methods starting with `_`

- docs/plugin-bugfix-safari-class-field-initializer-scope.md
- website/sidebars.js
See https://github.com/babel/babel/pull/16569
Doc structure adapted from `plugin-bugfix-firefox-class-in-computed-class-key`
> Add docs for plugin-bugfix-safari-class-field-initializer-scope

- docs/options.md
- docs/plugin-transform-runtime.md
- docs/preset-react.md
Hi!
I notice rubbish on [options](https://babeljs.io/docs/options#no-targets) page. My PR drop unused text.
> fix(options): drop visual noise

- docs/options.md
Proper anchor is `#pluginpreset-entries`:
https://babeljs.io/docs/options#pluginpreset-entries
Now link about entries works in plugins / preset options sections:
https://deploy-preview-2930--babel.netlify.app/docs/options#plugins
https://deploy-preview-2930--babel.netlify.app/docs/options#presets
> fix(options): fix plugin / present entries anchors

- website/data/sponsors.yml
I got an email from this sponsor asking why it was not there. I re-triggered website builds a few times, but then I realized that it's because it's from GH sponsors.
<details>
</details>
> Add Route4Me sponsor logo

- docs/v8-migration.md
For https://github.com/babel/babel/pull/16800
> Migration: min Node.js version for Babel 8

- website/data/sponsors.yml
Igalia is now paying for me to work on Babel, so that I don't rely on OpenCollective anymore.
> Add Igalia as a base support sponsor

- package.json
- yarn.lock
The build is failing when bumping from 8.0.0-alpha.2 to 8.0.0-alpha.12. 
The error is confusing since babel-loader 9 did not issue `loadPartialConfig` calls. I am still investigating the diff highlight regression, if you have bandwidth, please take a look.
To reproduce the build error, one can run `yarn start:repl`.
> bump Babel 8 to 8.0.0-alpha.12

- docs/parser.md
the default branch of [facebook/jsx](https://github.com/facebook/jsx/) has changed to `main`, the link is better to be updated, too
> Update facebook/jsx link

- docs/generator.md
Docs for https://github.com/babel/babel/pull/16708
> Add docs for generator's `experimental_preserveFormat` option

- docs/parser.md
Adds documentation for the new `@babel/parser` `startIndex` api.
https://github.com/babel/babel/pull/16849
> docs: @babel/parser  `startIndex` option

- docs/parser.md
- docs/plugin-syntax-import-attributes.md
- docs/v8-migration.md
Docs for https://github.com/babel/babel/pull/16850
> docs: `import attributes` enabled by default

- docs/v8-migration.md
Docs for https://github.com/babel/babel/pull/16792
> Add migration docs for flow `enums` option

- docs/parser.md
- docs/plugin-proposal-pipeline-operator.md
Docs for https://github.com/babel/babel/pull/16801
> [babel 8] Add docs for minimal/smart pipeline modes removal

- docs/parser.md
:wave: Capital S in TypeScript
Hope things are going well in babel-land
> Minor typo fix in parser.md

- js/minirepl.js
- website/src/pages/index.js
Closes https://github.com/babel/website/issues/2551
> update landing page examples

- docs/parser.md
- website/docusaurus.config.js
Current main:
https://babel.dev/docs/babel-parser
This PR:
This error is caught by https://github.com/facebook/docusaurus/pull/9394. 
@slorber Can docusaurus throw on unused MDX directives? I can't find such an option so if I missed anything please let me know, thank you.
> Fix unused markdown directives warning

- js/repl/ExternalPluginsModal.tsx
- js/repl/ExternalPluginsSearchBox.tsx
- package.json
- yarn.lock
The `react-instantsearch-dom` library has been deprecated in favor of `react-instantsearch`. In this PR we migrate to `react-instantsearch` and cleaned up the search box autofocus function.
Manual UI test:
1. Open REPL, click plugins tab on the left, click add plugin, the search input should be autofocused.
1. Type a few words and see if the plugin search modal works as expected
> Migrate `react-instantsearch-dom` v6 to `react-instantsearch` v7

- docs/compat-data.md
- website/sidebars.js
Closes https://github.com/babel/babel/pull/16953.
Preview link: https://deploy-preview-3015--babel.netlify.app/docs/babel-compat-data
> add compat-data docs

- docs/v8-migration-api.md
Added migration notes for two babel-types builder breaking changes due to the AST change.
> docs: add implied babel-types breaking changes

- docs/v8-migration-api.md
Docs PR for https://github.com/babel/babel/pull/17017
> Migration notes for `typeArguments` renaming for `TSClassImplements` and `TSInterfaceHeritage`

- docs/plugin-proposal-decorators.md
In reference to the issue raised in the babel repository: https://github.com/babel/babel/issues/16838
> Note section for Symbol.metadata in the plugin-proposal-decorators doc

- docs/v8-migration-api.md
Also grouped other typeArguments renaming into a single note.
Docs for https://github.com/babel/babel/pull/17020
> add docs for typeArguments renaming

- docs/v8-migration-api.md
- Split AST changes in JS vs TS
- Always use the imperative form of verbs in the bullet points
- Remove migration steps when the migration is "adapt to the new behavior", or when it's just repeating the change.
> Make Babel 8 API migration more uniform

- docs/v8-migration-api.md
Docs PR for https://github.com/babel/babel/pull/16979
> docs: add TSEnumBody migration

- docs/v8-migration-api.md
Docs PR for https://github.com/babel/babel/pull/17059
> add TSTypeQuery exprName migration note

- docs/v8-migration-api.md
Docs PR for https://github.com/babel/babel/pull/17073.
> add migration note for TSImportEqualsDeclaration AST change

- docs/v8-migration-api.md
Docs PR for https://github.com/babel/babel/pull/17066
> Add migration note for TSTemplateLiteralType

- docs/options.md
Countless devs have fallen into the trap of trying to use full `glob` patterns for matching. 
This PR...
- Clarifies the string matching logic 
- Notes that it's *not* a glob
- Provides examples on how matching works
Closes https://github.com/babel/website/issues/1986
> Expand docs about `MatchPattern`

- js/repl/ReplOptions.tsx
I can make `usebuiltins` option use less space, but feel use `minWidth` more flexible.
> Make ReplOptions wider

- docs/v8-migration-api.md
Also listed the new node types in the details summary, aligning with other changelogs.
> missing right paren in TSExpressionWithTypeArguments change note

- docs/compat-data.md
- docs/v8-migration-api.md
Marking as "medium" because it will make your program crash at startup, but you are only affected if you are already using native ESM with this package. It's also trivial to fix.
Docs for https://github.com/babel/babel/pull/17267
> Add migration docs for compat-data JSON

- docs/v8-migration-api.md
- website/sidebars.js
This guide was already in an overall good shape :)
I renamed it to "API", like we did for Babel 6->7, because it's not just about integrating Babel in a larger project (e.g. in a bundler) but also for plugin authors.
> Update Babel 8 API migration guide intro, and add to sidebar

- docs/v8-migration.md
Hopefully this will simplify the migration, as it will help people incrementally prepare their codebase for Babel 8.
> Add v8 migration summary for steps to take during Babel 7

- js/minirepl.js
Removed record and tuple plugin since the proposal has been withdrawn.
For pipeline operators, added an example taken from https://github.com/tc39/proposal-pipeline-operator/issues/314.
> update landing page REPL examples

- js/repl/Monaco.tsx
- js/repl/Repl.tsx
Because of https://github.com/microsoft/monaco-editor/issues/1883 we have to use `javascript` type for output.
> Fix REPL bugs

- website/blog/2025-06-30-7.28.0.md
This pull request includes a minor correction to the documentation in the `website/blog/2025-06-30-7.28.0.md` file. The change fixes a grammatical error in the description of the `"commonjs"` mode.
> release note polish

- docs/eslint-parser.md
- docs/eslint-plugin.md
- website/sidebars.js
The contents are mostly copied from the original docs, plus small modifications on the `eslint-parser` docs:
- Removed the "Question and Support" section, since the QA channel would be obvious now that the content has been on the Babel website
- Modify the `.eslintrc.js`, ... sections within the "Additional parser configuration" subsection to h4, as suggested by the markdownlint.
The original hyper references to babeljs.io have been replaced by markdown relative links as well.
Preview Links:
https://deploy-preview-3119--babel.netlify.app/docs/babel-eslint-parser
https://deploy-preview-3119--babel.netlify.app/docs/babel-eslint-plugin
> migrate eslint-{parser,plugin} docs to website

- docs/configuration.md
- docs/eslint-parser.md
- docs/eslint-plugin.md
In this PR we add ESLint Flat config examples for ESLint 9 and usage example for the `@babel/eslint-parser/experimental-worker`.
> Add eslint flat config examples

- .prettierignore
- eslint.config.mjs
- package.json
- website/src/components/HeroRepl.tsx
- yarn.lock
The landing page REPL is not responding to both simulated inputs and user inputs:
https://github.com/user-attachments/assets/e9840f14-d76a-437c-943a-f5d86fb6a7d5
This regression was introduced in https://github.com/babel/website/pull/3109. In this PR we updated the dependencies and reverted the `onChange` listener change.
> Fix: The Landing REPL should respond to user inputs
